aws/amazon-cloudwatch-agent

logs/logs.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

patch from telegraf: https://github.com/influxdata/telegraf/pull/4785
empty value of tags will cause the cloudwatch return error
like:
```
2020-09-19T04:25:37Z E! cloudwatch: code: InvalidParameter, message: 1 validation error(s) found., original error: InvalidParameter: 1 validation error(s) found.
caused by: ParamMinLenError: minimum field size of 1, PutMetricDataInput.MetricData[0].Dimensions[0].Value.
2020-09-19T04:25:37Z W! 0 retries, going to sleep 200ms before retrying.
2020-09-19T04:25:37Z E! WriteToCloudWatch failure, err:  InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutMetricDataInput.MetricData[0].Dimensions[0].Value.
```
It was been fixed in telegraf, just patch it from https://github.com/influxdata/telegraf/pull/4785
And exclude "host" dimension …

fix: Skip tags with empty values

---

translator/totomlconfig/sampleConfig/delta_config_linux.conf
translator/totomlconfig/sampleConfig/delta_config_linux.json
translator/totomlconfig/toTomlConfig_test.go
translator/translate/metrics/metrics_collect/diskio/diskio_test.go
translator/translate/metrics/util/deltasutil.go

Translator return error when configure rename metrics in diskio input plutin.
```
"diskio": {
"resources": [
"*"
],
"measurement": [
{
"name": "iops_in_progress",
"rename": "test_in_progress",
"unit": "Count"
},
{
"name": "read_time",
"rename": "test_READ_TIME",
"unit": "Milliseconds"
},
{
"name": "diskio_write_time",
"rename": "test_WRITE_TIME",
"unit": "Milliseconds"
}
]
},
```
DiskIo can not handle such map object.
1. supports map in diskio
2. supports diskio prefix in metricname, like "diskio_write_time"
added unit test

fix: diskio plugin can not use metric rename

---

go.mod
go.sum

gopsutil upgrade results in the "Device" dimension changed from the name
of the symbolic link under /dev/mapper to the actual device by resolving
the symbolic link. This is a breaking for customers thus we added the
original path under /dev/mapper back as "Source" in gopsutil in pull
request:
https://github.com/shirou/gopsutil/pull/957
And make use of this "Source" when it is available in the aws/Telegraf
fork:
https://github.com/aws/telegraf/commit/f7742938b37806a4b1d98f81f3fb5bf50b9bcb3f
In this commit, we pick up the modified gopsutil and telegraf for the
fix, and would revert to later versions when the changes are upstreamed.

fix: use name under /dev/mapper as device for LVM volumes for disk plugin

---

packaging/debian/preinst
packaging/debian/prerm

Current preinst and prerm script does not start with '#!' as suggested by debian documentation:
https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
Added '#!/bin/sh' to both scripts

chore: add #! to preinst and prerm for debian pkg for compliance

---

plugins/outputs/cloudwatch/util.go
plugins/outputs/cloudwatch/util_test.go

md5 may have security fisk.
use random instead
make

chore: remove md5 from jitter caculation

---

translator/translate/util/placeholderUtil.go

We want to be able to truncate old data from our Cloudwatch logs; so we decided to break the Log Streams into individual chunks based on date.
This PR adds a new placeholder variable `{date}` which can be put in the Log Stream template definition, and will be replaced with the current date in ISO-8601 format (such as "2020-11-02").
We've been using this commit in a custom build for over a month now, without issue.

Add formatted date as a variable

---

Makefile

https://github.com/aws/amazon-cloudwatch-agent/issues/123
need to disable cgo for test target, otherwise the test will fail caused by gcc missing.
make release

chore: disable cgo for test target

---

cmd/start-amazon-cloudwatch-agent/start-amazon-cloudwatch-agent.go
translator/config/envconst.go
translator/util/sdkutil.go

When running CloudWatch Agent on Fargate the agent container determines the environment as `OnPrem` since the metadata service is unavailable on Fargate. Afterwards the generated `toml` expects a credentials file at `.aws/credentials` instead of using the attached role. #118 
This PR adds an ENV flag `RUN_IN_AWS=True` that would force the agent to skip metadata check allowing it to fallback to the usual credentials procedure. The downside is that the agent is unable to automatically determine the region and other variables that are dependent on the metadata service e.g. `{instance_id}` don’t work.

enable flag to force ec2 mode

---

plugins/processors/emfProcessor/metricDefinition_test.go

deepequal in go will not sort the elements in slice and array, it make the unittiest unstable.
sort the slice before doing comparasion.
make

chore: fix unstable unittest

---

Tools/src/create_deb.sh
Tools/src/create_rpm.sh
Tools/src/create_win.sh

create_rpm deb win.sh will not report error if there is something wrong.
add "set -e"  to let shell exit when error occurs

chore: exit the build script when error occurs

---

packaging/dependencies/amazon-cloudwatch-agent-ctl

Closes #131
https://github.com/aws/amazon-cloudwatch-agent/issues/131
It is possible that in some systems the command `systemctl | grep -c '\-\.mount'` will return a value greater than zero. In these circumstances the `amazon-cloudwatch-agent-ctl` script doesn't detect `systemd` correctly. This patch is intended to fix this behavior.
Given that
```
$ systemctl | grep '\-\.mount'
-.mount                                                                                  loaded active     mounted   Root Mount                                                                
tmp-.mount_jetbraP6HI4I.mount …
```

Fix incorrect systemd detection

---

amazon-cloudwatch-container-insights/CHANGELOG.md
amazon-cloudwatch-container-insights/container-insights-manifest-update.sh
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/cwagent/cwagent-daemonset.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit-compatible.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit-configmap.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluentd/fluentd.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluent-bit-quickstart.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/prometheus-eks.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/sample_cloudwatch_dashboards/fluent-bit/README.md
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/sample_cloudwatch_dashboards/fluent-bit/cw_dashboard_fluent_bit.json

Need to migrate from FluentD to Fluent-Bit. 
Added new Fluent-Bit configurations as well as a new dashboard and updated prometheus-eks.yaml to scrap Fluent-Bit prometheus metrics.
Ran integration tests as well as a couple of reviews from internal CloudWatch and container team.

Added New Fluent-Bit configs

---

internal/ecsservicediscovery/README.md
internal/ecsservicediscovery/config.go
internal/ecsservicediscovery/config_test.go
internal/ecsservicediscovery/decoratedtask.go
internal/ecsservicediscovery/decoratedtask_test.go
internal/ecsservicediscovery/processorstats.go
internal/ecsservicediscovery/servicediscovery.go
internal/ecsservicediscovery/servicediscovery_test.go
internal/ecsservicediscovery/serviceendpointdiscoveryprocessor.go
internal/ecsservicediscovery/serviceendpointdiscoveryprocessor_test.go
internal/ecsservicediscovery/taskfilterprocessor.go
internal/ecsservicediscovery/taskfilterprocessor_test.go
internal/ecsservicediscovery/taskprocessor.go
translator/config/schema.go
translator/config/schema.json
translator/totomlconfig/sampleConfig/prometheus_config_linux.conf
translator/totomlconfig/sampleConfig/prometheus_config_linux.json
translator/totomlconfig/sampleConfig/prometheus_config_windows.conf
translator/totomlconfig/sampleConfig/prometheus_config_windows.json
translator/totomlconfig/toTomlConfig.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/ruleSDContainerNamePattern.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/ruleSDJobName.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/ruleSDMetricsPath.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/ruleSDMetricsPorts.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/ruleSDServiceNamePattern.go
translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/serviceendpoint/serviceendpoint.go

This enables CWAgent ECS service discovery based on service name. This functionality is enabled by the following changes to the ecsservicediscovery package, and the config translator.
**EcsServiceDiscovery:**
config.go has been updated to include a ServiceNameConfig struct, which includes the following parameters:
1. ContainerNamePattern (regex, JSON/TOML key: "sd_container_name_pattern")
2. JobName (JSON/TOML key: "sd_job_name")
3. MetricsPath (JSON/TOML key: "sd_metrics_path")
4. MetricsPorts (JSON/TOML key: "sd_metrics_ports")
5. ServiceNamePattern (regex, JSON/TOML key: "sd_service_name_pattern")
These parameters mirror the parameters for task definition-based discovery, facilitating feature parity between the two discovery methods.
servicediscovery.go now calls a new class, …

Add ecs service endpoint-based discovery for prometheus

---

plugins/inputs/prometheus_scraper/metric_type_handler_test.go
plugins/inputs/prometheus_scraper/metrics_type_handler.go

counter with suffix "_total" may be discarded by agent. It is because prometheus is using openmetrics format, refer to https://www.robustperception.io/openmetrics-is-released, "_total" will be removed for openmetrics format.
remove the suffix "_total" to retrieve the metricdata if it can not get metricdata with original name.
tested by eks cluster with grafana.

fix: correct the metrictype for suffix _total

---

packaging/linux/amazon-cloudwatch-agent.spec

amazon-cloudwatch-agent own /opt/aws directory, it may conflict with other packages.
do not own /opt/aws in rpm spec

chore: do not own /opt/aws in rpm spec

---

cfg/aws/credentials.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go
translator/translate/logs/metrics_collected/kubernetes/k8sdecorator/ruleClusterName.go
translator/translate/logs/util/get_eks_cluster_name.go

Currently the agent does not specify any httpclient when constructing aws clients, which in turn uses the default http client provided by go, which does not have any timeout settings. This means if the backend becomes unresponsive, or connection had issue due to networking issues that prevented the request from finish, it may hang the agent forever.
Add http timeout to where aws client are created with a custom http
client describe in:
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/custom-http.html
Only a single Timeout is specified since there is no special reason to
specify the timeout of each part of the request, as the goal is to
prevent unresponsive backend or networking error from hanging the agent
forever.
The timeout parameter covers the whole request as described in: …

fix: Add timeout to aws client, prevent agent hang from unresponsive backend

---

plugins/inputs/logfile/fileconfig_test.go
translator/translate/logs/logs_collected/files/collect_list/collect_list_test.go
translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go

if the format startswith "%-m" or "%-d", there is an "\\s{0,1}" at the beginning of timestamp_regex.
like "timestamp_format": "%-m %-d %H:%M:%S" will be converted into following layout and regex
timestamp_layout = "1 2 15:04:05"
timestamp_regex = "(\\s{0,1}\\d{1,2} \\s{0,1}\\d{1,2} \\d{2}:\\d{2}:\\d{2})"
following timestamp string " 2 1 07:10:06" matches the regex, but it can not match the layout.
Remove the \\s{0,1} prefix 
Unittest

chore: fix timestamp parse error if timestamp_format starts with space

---

plugins/inputs/cadvisor/container_info_processor.go
plugins/inputs/cadvisor/container_info_processor_test.go
plugins/inputs/cadvisor/extractors/cpu_extractor.go
plugins/inputs/cadvisor/extractors/extractor.go
plugins/inputs/cadvisor/extractors/mem_extractor.go

When using `systemd` instead of `cgroupfs` as docker cgroup driver the pattern in cgroup path has changed due to the prefix. And it breaks two places
- nested container detection, we were counting the prefix, so all the container got treated as nested container
- the detection is for https://github.com/aws-samples/amazon-cloudwatch-container-insights/issues/21 and introduced in #5 
- pod name, we are using `podPodId` but now it is `kubepods-burstable-podPodId`
- count number of segments to detect if it is a nested container
- use parent folder of a container as a pod
- create a new cluster using latest eksctl unmanged node group
- deploy the old …

Fix cadvisor name pattern for docker systemd cgroup driver

---

plugins/inputs/prometheus_scraper/calculator.go
plugins/inputs/prometheus_scraper/delta_calculator.go
plugins/inputs/prometheus_scraper/metrics_receiver.go
plugins/inputs/prometheus_scraper/metrics_receiver_test.go

When prometheus metrics contain "+Inf" or "-Inf" values, cloudwatchlog fails to convert the metrics to emf log: https://github.com/aws/amazon-cloudwatch-agent/blob/master/plugins/outputs/cloudwatchlogs/cloudwatchlogs.go#L230-L233. In this case, cloudwatch agent sends the ill-formatted log which cause a backend error:
```
2021-01-30T21:51:57Z E! [outputs.cloudwatchlogs] Aws error received when sending logs to /aws/containerinsights/lon-dev-2/prometheus/kubernetes-apiservers: InvalidParameter: 1 validation error(s) found.
minimum field size of 1, PutLogEventsInput.LogEvents[44].Message
```
This prevents the creation of log stream and blocks other normal metrics from publishing. 
Since those Inf values are not useful, we should ignore them. 
By submitting this pull request, I confirm that …

ignore +/-Inf values in prometheus metrics

---

Makefile

Currently, all CWAgent binaries are compiled without `-buildmode=pie`, which means the binaries are built without (ALSR)[https://en.wikipedia.org/wiki/Address_space_layout_randomization] mode enabled.
Adding `-buildmode=pie` would enable ALSR, though golang is generally considered memory safe, but adding ALSR as an extra layer of defense would further enhance the security of the agent
No logic change done to the code base, basic building and feature test done manually

chore: Use PIE buildmode to enable ALSR for better security

---

plugins/inputs/prometheus_scraper/metric_type_handler_test.go
plugins/inputs/prometheus_scraper/metrics_receiver.go
plugins/inputs/prometheus_scraper/metrics_type_handler.go
plugins/inputs/prometheus_scraper/start.go

Fix #190 
Save name before relabel using relabel.

prom: Save __name__ before relabel for look up metric type

---

plugins/inputs/prometheus_scraper/metric_type_handler_test.go
plugins/inputs/prometheus_scraper/metrics_receiver.go
plugins/inputs/prometheus_scraper/metrics_type_handler.go
plugins/inputs/prometheus_scraper/start.go

Fix #193 
Similar to #191  save label using relabel because they can get relabeled during relabel.
- remove old job relabel look up logic
```yaml
- source_labels: [__meta_kubernetes_pod_name]
action: replace
target_label: instance
- action: replace
source_labels:
- __meta_kubernetes_pod_controller_name
target_label: job
```

prom: Save job and instance label before relabel for look up metric type

---

Makefile
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/combination/combination.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/cwagent/cwagent-daemonset.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluent-bit-quickstart.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml
internal/containerinsightscommon/const.go
plugins/inputs/cadvisor/container_info_processor.go
plugins/inputs/cadvisor/extractors/cpu_extractor.go
plugins/inputs/cadvisor/extractors/diskio_extractor.go
plugins/inputs/cadvisor/extractors/extractor.go
plugins/inputs/cadvisor/extractors/fs_extractor.go
plugins/inputs/cadvisor/extractors/mem_extractor.go
plugins/inputs/cadvisor/extractors/net_extractor.go
plugins/inputs/cadvisor/merger.go

Fix #188 k8s cluster using containerd runtime was not able to get pod metrics because
- contained socket is not mounted
- pod detection logic relies on pause container with name 'POD`, which is only the case for docker

cadvisor: Fix pod detection for containerd runtime on k8s

---

RELEASE_NOTES

Release v1.247347.6 https://github.com/aws/amazon-cloudwatch-agent/milestone/1?closed=1
- prometheus relabel for job, instance and __name__
- contianerd support (without out container filesystem #192 )
N/A

release: v1.247347.6

---

go.mod
go.sum

proxy.golang.org has versions of golang.zx2c4.com/wireguard with leading v's, whereas the git repo has tags without
leading v's: https://git.zx2c4.com/wireguard-go/refs/tags
So, fetching this module with version v0.0.20200121 (as done by the transitive dependency
https://github.com/WireGuard/wgctrl-go/blob/e35592f146e40ce8057113d14aafcc3da231fbac/go.mod#L12 ) was not working when
using GOPROXY=direct.
Replacing with the pseudo-version works around this.

Work around direct proxy version issue with golang.zx2c4.com/wireguard.

---

plugins/processors/k8sdecorator/stores/podstore.go
plugins/processors/k8sdecorator/stores/podstore_test.go

Having metrics come in for each CI job with unique names is polluting our metrics and costs more money. I wanted to ignore some pods.
In the `podstore.Decorate` method of the k8s processor, after we're confident we've got a pod, check the annotations and return false so as to not handle that pod.
I have this running in our devops cluster where Jenkins is creating pods with these annotations. Automated tests pass, but nothing explicitly tests the method I changed, and I couldn't in a reasonable time figure out how to write a good test for it. If somebody wants to help out let me know.

Allow ignoring pods with the aws.amazon.com/cloudwatch-agent: ignore annotation

---

amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/prometheus-eks.yaml

It is now `$namespace_$servicename-default-backend_http`, it was `_default_backend` when using helm chart 0.11.4. This new regex should work for 0.12.0
A new regex 'or'
Internal integ test

prom: Add more regex to match new haproxy backend format

---

plugins/inputs/logfile/logfile.go

There is a typo in https://github.com/aws/amazon-cloudwatch-agent/blob/v1.247347.6/plugins/inputs/logfile/logfile.go#L170 .
Fix the typo  by replacing public_multi_logs with publish_multi_logs
make build && make test

fix: typo in logfile.go s/public_multi_logs/publish_multi_logs/

---

plugins/outputs/cloudwatchlogs/pusher.go

Update the warning message to indicate that there will be missing logs when cloudwatch agent received non-aws errors from backend. It is assumed that the non-aws errors can't be recovered automatically so there will be no retry (for performance concerns)
N/A

update warning message to indicate missing log

---

plugins/inputs/prometheus_scraper/metrics_receiver.go

We were logging all the prometheus metrics.  See #209 for detail
Removed the log.
Compile

prom: Remove logging all the metrics introduced in #193

---

RELEASE_NOTES

Release v1.247348.0 https://github.com/aws/amazon-cloudwatch-agent/milestone/1?closed=1
Enhancements and bug fixes:
* Allow ignoring pods metrics with a specific annotation to remove the metrics not needed. (#163)
* Fix the unnecessary logging entries (#210)
* Update aws-otel-collector version to v0.10.0 (#216)
N/A

release v1.247348.0

---

README.md

This is fixed PR of #225.
There is a typo in https://github.com/aws/amazon-cloudwatch-agent/blob/v1.247348.0/README.md.
Fix the typo by replacing `Cloudwatch` with `CloudWatch`. (Amazon) CloudWatch is the official service name, so it should be consistant.
make build && make test

fix: typo in README.md s/Cloudwatch/CloudWatch/

---

.gitignore

According to 93ed049dcca2173cb2209ea06226847a03fe7ba5 and https://github.com/aws/amazon-cloudwatch-agent/blob/v1.247348.0/Makefile, both are not needed as source file now and removed by `make clean`. It is safer to ignore these files not to commit them by mistake.
Add `CWAGENT_VERSION` file and `build` folder to `.gitignore`
`make build && make test` is succeeded.

add `CWAGENT_VERSION` file and `build` folder to .gitignore

---

Makefile

From https://github.com/aws/amazon-cloudwatch-agent/pull/228#issuecomment-863431047 We were assuming the arm binary is build on x86 using cross compile. This is case for our internal build and has been working fine for arm docker image, but if user build the binary on arm machines, then cgo is enabled and the binary no longer runs in scratch container.
Set `CGO_ENABLED=0` explictly
```
make <whatever binary targets>
```

build: Disable CGO for arm64 explicitly

---

Makefile
amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/README.md
amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/source/Dockerfile

We were using deb when building image from source, i.e. source -> deb -> docker image. But we have composite agent, which is not used when running as image.
- Add two new targets (x86_64 and arm64) to only build binary required for docker image
- Make amd64 the default target
- Use the new target in `Dockerfile`
Run the new commands (in a place that does not block go mod proxy)
```
docker buildx build --platform linux/amd64,linux/arm64 -f amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/Dockerfile .
```

build: Build docker without open telemetry collector

---

cmd/config-downloader/downloader.go

Currently, if the configuration file is stored in a `ParameterStore` as a `SecureString`, the `config-downloader` will successfully retrieve the file, but will not decrypt it, so the translator is unable to successfully parse it.
```
Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm_SecureStringConfig.tmp ...
unable to scan config dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d with error: unable to parse json, error: invalid character 'A' looking for beginning of value
```
Updated `ssm.GetParameter` to include the `WithDecryption` flag to support `SecureString` parameters. According to the SSM API (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html), the flag is ignored for `String` and …

Support SSM SecureString parameters.

---

.gitignore
plugins/inputs/logfile/fileconfig_test.go
tool/data/config/metric/aggregationDimensions.go
tool/data/config/metric/aggregationDimensions_test.go
tool/data/config/metrics.go
tool/data/config/metrics_test.go
tool/processors/basicInfo/basicInfo.go
tool/processors/defaultConfig/defaultConfig.go
tool/processors/defaultConfig/defaultConfig_test.go
tool/runtime/context.go
translator/translate/logs/logs_collected/files/collect_list/collect_list_test.go

In order to support EC2 metrics published by the CW Agent on Metrics Explorer, the dimensions of the metrics should be set as "Instance Id". This is something we achieve for the existing customers using some guideline docs. But for new customers who will onboard for the first time, we would like to offer this support by default by arranging these settings in the CW Agent config file.
Added a yes/no prompt in `defaultConfig.go` as part of the config wizard to add the `aggregation_dimensions` field to the `metrics` config. By default, the `aggregation_dimensions` will have a single dimension of "Instance Id". Moved pricing disclaimer from prompt to welcome message.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Default config metrics exporter

---

go.mod
go.sum

There is a transitive dependency on tencentcloud/tencentcloud-sdk-go through hashicorp/go-discover. Tencent downgraded their versioning from v3.x.xx to v1.x.xx (https://github.com/TencentCloud/tencentcloud-sdk-go/issues/103), but the change hasn't been merged into go-discover. Still waiting on the PR (https://github.com/hashicorp/go-discover/pull/173) to get merged.
Added a replace directive for the tencentcloud-sdk-go version to downgrade it.

go.mod tencentcloud-sdk-go workaround.

---

amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/combination/combination.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluentd/fluentd.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/cwagent-fluentd-xray/cwagent-fluentd-xray-quickstart.yaml

Update the fluentd configurations:
* disable watch for kubernetes metadata
Manually test the new configuration with fluentd integration tests.

disable fluentd watch on kubernetes_metadata

---

translator/cmdutil/userutil.go
translator/cmdutil/userutil_darwin.go
translator/cmdutil/userutil_linux.go
translator/cmdutil/userutil_test.go

The Cloudwatch agent change ownership of directories to the user the service is running as.
Excluding executable file and Suid Sgid when change file ownership with chown. Prevent possible privilege escalation. Files with o+w permission are also skipped
Added unit test that creates regular files, executable files, symbol links and verified the behavior of ownership change does not affect executable files and suid/sgid files.

Change ownership of files excluding executable files and Suid Sgid files.

---

internal/k8sCommon/k8sclient/endpoint.go
internal/k8sCommon/k8sclient/job.go
internal/k8sCommon/k8sclient/node.go
internal/k8sCommon/k8sclient/pod.go
internal/k8sCommon/k8sclient/replicaset.go

Performance fix for interaction of Container Insights code with Kubernetes API server.
When running in a Kubernetes cluster, one leader-elected instance of the agent stays up to date with metadata such as
the full list of pods and nodes in the cluster, in order to post metrics for Container Insights.  It does this using a
Go client called the Reflector which performs API calls against the Kubernetes API server for each resource type.  The
Reflector works in two phases:
1. Perform an initial List call to receive the current set of resources (e.g., pods), at whatever version the API server
happens to return.  The List call is paginated in case there are a large number of resources, so this phase might
entail several API calls.
2. Thereafter, perform long-lived Watch calls to receive updates …

Performance fix for interaction of Container Insights code with Kubernetes API server.

---

plugins/outputs/cloudwatchlogs/pusher.go

There is a line using wrong variadic parameters at https://github.com/aws/amazon-cloudwatch-agent/blob/6af763a6496d4d07b96a4e67e9b2b68f2c202657/plugins/outputs/cloudwatchlogs/pusher.go#L289
Fix wrong variadic parameters with the proper one
make build && make test

fix wrong variadic parameters when request dropped

---

plugins/inputs/windows_event_log/windows_event_log.go
plugins/inputs/windows_event_log/windows_event_log_test.go

Also changed the filename to be more unique and allow LogGroup to be used more than once.
https://github.com/aws/amazon-cloudwatch-agent/issues/266
Currently cannot monitor the Windows "Application" and "System" event logs using the same "LogGroup" value.
"StateFile" name is now a combination of the "event_config"'s values for "event_name", "log_group_name", and "log_stream_name".
Manual testing.
Before change:
```
2021-09-24T16:09:16Z I! [windows_event_log] The state file for Amazon_CloudWatch_WindowsEventLog_Application does not exist: CreateFile Amazon_CloudWatch_WindowsEventLog_Application: The system cannot find the file specified. …
```

Fixed windows event log plugin to use proper StateFile path.

---

plugins/outputs/cloudwatchlogs/pusher.go
plugins/outputs/cloudwatchlogs/pusher_test.go

Currently, the pusher resend will not exit the loop even after the maximum allowable time for retries has been reached.
Added resetting and returning after the logging the error to drop the request.
Added a unit test.

Fix request drop on max retries

---

go.mod
go.sum
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go
translator/cmdutil/set_uid_gid.go
translator/cmdutil/set_uid_gid_1_15_x32.go
translator/cmdutil/set_uid_gid_1_15_x64.go
translator/cmdutil/userutil_linux.go
translator/cmdutil/userutil_linux_test.go

The agent has a dependency on `github.com/opencontainers/runc v1.0.0-rc10`, which requires an upgrade. While the version could be bumped up to `v1.0.0-rc95`, that would affect the dependency on `github.com/google/cadvisor v0.36.0`, which depends on `v1.0.0-rc10`. Without updating the cadvisor dependency, which would require more evaluation and incremental changes, the next best step would be to remove the local dependency.
See https://github.com/aws/amazon-cloudwatch-agent/pull/254 for more details.
Removed dependency on runc in userutil_linux.
Replaced with golang os/user lookup and version/arch specific setUid/setGid.
Tested on EC2 linux …

Removed runc dependency

---

.github/workflows/build.yml

GitHub CI build times are long because we always have to download dependencies for each build, fresh.
Uses the [cache](https://github.com/actions/cache/blob/main/examples.md#go---modules) action to cache build output from Go. 
Pushed this to my fork and confirmed that (1), the new step ran, and (2) that the matrix picked the correct paths for the different OS types. See [my build](https://github.com/SaxyPandaBear/amazon-cloudwatch-agent/runs/4041624140?check_suite_focus=true).

add cache step to build action

---

cmd/config-translator/translator_test.go
plugins/plugins.go
translator/cmdutil/userutil_test.go
translator/config/sampleSchema/validNvidiaGpuConfig.json
translator/config/schema.go
translator/config/schema.json
translator/isValid.go
translator/totomlconfig/sampleConfig/advanced_config_linux.conf
translator/totomlconfig/sampleConfig/advanced_config_linux.json
translator/totomlconfig/toTomlConfig.go
translator/translate/metrics/config/deny_list_tags.go
translator/translate/metrics/config/plugin_alias_map.go
translator/translate/metrics/config/registered_metrics.go
translator/translate/metrics/metric_decoration/metric_decoration_test.go
translator/translate/metrics/metrics_collect/gpu/nvidiaSmi.go
translator/translate/metrics/metrics_collect/gpu/nvidiaSmi_test.go
translator/translate/metrics/util/commonconfigutil.go
translator/translate/metrics/util/measurementutil.go

Fix Darwin build and add support for GPU metrics.
GPU metrics feature not usable yet.
Unit tests.

Fix Darwin build and add support for GPU metrics

---

plugins/inputs/logfile/logfile_test.go

`TestLogsFileRecreate()` intermittently fails on Windows OS.
example: https://github.com/aws/amazon-cloudwatch-agent/runs/4156147013?check_suite_focus=true
There are actually 2 issues.
First is that there is a `for` loop that will does not end until Go does a `panic`.
Second, the delay between deleting the monitored temp file and recreating it is a fixed 100 ms.
These 2 changes are minimally required.
The loop will timeout after 10 seconds if the LogSrc is not found, instead of `Panic` after 10 minutes.
The fixed delay between deleting and recreating the temp file has been increased from 100ms to 1 second.
I added some info messages to describe what the test is doing.
I was just going to add code comments, but logging what the test is doing makes it easier to correlate with what the …

Fix TestLogsFileRecreate.

---

.github/workflows/build.yml
codecov.yml

Unable to view files on codecov
Sets the correct base path to find files on github

Codecov file browser fix

---

internal/ecsservicediscovery/decoratedtask.go
internal/ecsservicediscovery/decoratedtask_test.go

Fixes #330.
https://github.com/aws/amazon-cloudwatch-agent/issues/330
With this change, if `NetworkMode` is not specified as part of the `TaskDefinition`, which is allowed, it will act as if `NetworkMode==bridge`.
Added tests.

Added support for implicit NetworkMode.

---

plugins/inputs/windows_event_log/wineventlog/sys_call.go
plugins/inputs/windows_event_log/wineventlog/utils.go
plugins/inputs/windows_event_log/wineventlog/utils_test.go
plugins/inputs/windows_event_log/wineventlog/wineventlog.go
plugins/inputs/windows_event_log/wineventlog/wineventlog_notwindows.go
plugins/inputs/windows_event_log/wineventlog/wineventlog_test.go
plugins/inputs/windows_event_log/wineventlog/wineventlogrecord.go
plugins/outputs/cloudwatch/cloudwatch.go
translator/translate/logs/logs_collected/windows_events/collect_list/collectlist.go

Closes https://github.com/aws/amazon-cloudwatch-agent/issues/199
CloudWatch Agent reads from the Windows event logs in batches.
Currently, if the Agent has issues reading or rendering _any_ event in the batch, it will drop all the events in the batch.
In this specific case there was an event related to the install of Google Chrome for which `EvtOpenPublisherMetadata()` failed.
Change `getRecords()` to `continue` when an error is encountered, instead of `return`.
Fixed another bug in `windowsEventLog.Open()` so it returns an error when `EvtSubscribe()` fails.
Manual test:
1. Start an EC2 instance running Windows Server 2019 with …

Fix missing Windows events by changing getRecords().

---

translator/totomlconfig/sampleConfig/log_filter.conf
translator/totomlconfig/sampleConfig/log_filter.json

Depending on the environment that is running tests, the log stream name for this test can change, because of env vars on the test runner that could be picked up by the test and injected into the translation output.
Reading from the environment is a design choice of the agent, so rather than trying to refactor/modify that, I'm opting to just specify a log stream name so that it remains consistent in this test without causing a breaking change in existing functionality.
Supplied a `log_stream_name` value in the test config json so that it consistently uses that in the test, regardless of the environment that the test is run.
Ran the test locally to …

force consistent log stream name

---

plugins/inputs/logfile/logfile.go
plugins/inputs/logfile/logfile_test.go

There was a customer issue where when retention in unset (and automatically set to -1), checkForDuplicateRetention would assume that there was multiple retention sets
https://github.com/aws/amazon-cloudwatch-agent/issues/315
Add a check that if retention is set to -1, do not assume that retention is considered duplicate since its a default value and considered unset
Added additonal Unit tests `checkForDuplicateRetention`

fix duplicate retention check

---

plugins/inputs/logfile/tailersrc_test.go

`tailersrc_test` tests for log filtering added in #327 are flaky in GitHub.
1. Noticed that older tailer tests had a 10x difference between the multilineWaitPeriod and the sleep timer (100ms vs 1s), so tweaked the sleep time in the log filter tests to match that. 
2. The single line log filter test sometimes would fail and not consume any logs. Added a sleep to allow the tailer to keep up with the log publication to (hopefully) keep it consistent
Kept PR in draft mode and reran the GitHub Actions to manually test several times to see if the tests passed more consistently.

Address flaky tests in GitHub CI

---

cmd/config-translator/translator_test.go

Fixing spelling and grammer in Translator test naming.

Grammer and spelling touch up for translator tests

---

cfg/agentinfo/info.go
cfg/agentinfo/info_test.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs_test.go

We don't have the ability to see how much usage comes from `Container Insights` right now. Adding this so that we can have an idea what plugins/features are in use and potentially make users more willing to use these features.
- As discussed, the outputs plugin name should be `container_insights`
- Update the output plugin list (in the user agent info) when the log group name matches the pattern of `Container Insights`
Added a new unit test `TestUserAgent`

Add a feature flag to user agent for container insights

---

plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go
translator/config/sampleSchema/validLinuxMetrics.json
translator/defaultKeyCase.go
translator/totomlconfig/sampleConfig/drop_origin_linux.conf
translator/totomlconfig/sampleConfig/drop_origin_linux.json
translator/totomlconfig/toTomlConfig.go
translator/totomlconfig/toTomlConfig_test.go
translator/translate/metrics/config/cloudwatch_output_plugin_config_keys.go
translator/translate/metrics/drop_origin/drop_origin.go
translator/translate/metrics/drop_origin/drop_origin_test.go
translator/translate/metrics/metric_decoration/metric_decoration_test.go
translator/translate/metrics/metrics.go

1. Transalte drop original flags config at metrics level
2. Drop metrics based on the metric names when the output plugin is configured
3. Unit tests for config translation and config reading

Adding support for Drop original dimensions when aggregating

---

.github/workflows/build-test-windows.yml
.github/workflows/build.yml
.github/workflows/integrationTest.yml

Currently, there are two issues I want to address: 
- When we add changes to readme doc, create a PR out of it, merge into main; we would trigger the workflow build; however, that's not needed since relating to docs are not needed to trigger the build. 
- When creating a PR with multiple commits or merging into main, the Github Runners will scale based on the commits and the PRs have been merged into main. Therefore, to reduce the needed Github Runners, we can use [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to avoid running simultaneously.
Add paths ignore when merging into master and add concurrency to reduce GitHub Runners running a PR for a single branch.
By submitting this pull request, I confirm that you can use, …

Add concurrency for pr

---

packaging/dependencies/amazon-cloudwatch-agent.service

Closes #298 
Using the `After=network.target` only indicates that the device is available but not configured (see [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/systemd-network-targets-and-services_configuring-and-managing-networking)).
Changing the systemd configuration to use `After=network-online.target` puts a delay on activation until the device designates itself as "up" (see [here](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)).

update systemd network target

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-macos.yml
.github/workflows/build-test-windows.yml

The "build.yml" workflow does both linux and macos build and test. This could lead to the failure of both of them if one of them fails and then require to rerun everything all over again for both OS, which is both costly and time consuming.
Link to the issue: https://github.com/aws/amazon-cloudwatch-agent/issues/353
Split the "build.yml" workflow into "build-test-linux.yml" and "build-test-macos.yml".
Pushed the same code in another fork and have run both of these workflow successfully .

Breakout unit testing per OS. Issue: #353

---

internal/ecsservicediscovery/decoratedtask.go
internal/ecsservicediscovery/decoratedtask_test.go
plugins/inputs/logfile/tailersrc_test.go
plugins/outputs/cloudwatch/aggregator_test.go

Metrics exported to Prometheus don't include the cluster name or task ID, making it harder to map the metric back to the particular task that generated it using the AWS web UI.
The task ID doesn't appear to be directly accessible, but the last part of the task's ARN (the resource) includes the cluster name and ID. This PR extracts this part of the ARN and exports it.
Automated tests have been updated and pass, and the changes have also been manually tested using a Fargate cluster.

Export Task ARN resource via Prometheus

---

translator/cmdutil/set_uid_gid_1_15_x64.go

The `setGid` function was using the `SYS_SETUID` syscall, which was causing the user to be changed to the gid and preventing the actual user from being set.
Fixed syscall name.

Fix typo in setGid function.

---

RELEASE_NOTES

Update release notes based on https://github.com/aws/amazon-cloudwatch-agent/compare/v1.247349.0...v1.247350.0
https://github.com/aws/amazon-cloudwatch-agent/compare/v1.247349.0...v1.247350.0
No tests needed. This is just a README update

update release notes with the 350 release

---

README.md

Add example of Log Filtering in README

update README with log filtering info 

---

packaging/debian/preinst
packaging/linux/amazon-cloudwatch-agent.spec

Currently, if you perform the following:
1. Install older version of CloudWatch agent
2. Configure/start agent
3. Install a newer version of CloudWatch agent (I did it via `sudo rpm -U amazon-cloudwatch-agent.rpm`)
The result is that the agent will be upgraded, but **stopped**. The agent should be able to gracefully restart after an upgrade. This would coincide with an existing AWS SSM integration which automatically installs and attempts to update the CloudWatch agent on managed fleets every 30 days. 
1. Add `%posttrans%` scriptlet to the spec file when building the RPM in order to conditionally restart
2. Add `prep-restart` call pre-upgrade in order to correctly perform the conditional restart after the upgrade action
3. Create the `aoc` user/group that is required for the bundled OTEL …

Restart agent on RPM upgrade

---

.github/workflows/integrationTest.yml
integration/msi/tools/amazon-cloudwatch-agent.wxs
integration/msi/tools/create_msi.ps1
integration/msi/tools/manifest.json
integration/msi/tools/msiversion/msiversionconverter.go
integration/msi/tools/permission.ps1

Need a way to build msi for windows tests 
Build the msi and upload to s3
Ran action on my fork

Build MSI For Integration Test (#388)

---

integration/msi/tools/msiversion/msiversionconverter.go

Fix MSI Version Converter By Adding Imports

---

cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go

As reported in #393, currently `--help`, `-help`, `-h` produces no output / empty output
Brings back the default `flag.Usage` implementation (currently it's overridden with a function that just exits without printing anything). 
Manual test on the cli
Closes #393

Bring back -help output

---

internal/ecsservicediscovery/decoratedtask.go
internal/ecsservicediscovery/decoratedtask_test.go

I originally submitted https://github.com/aws/amazon-cloudwatch-agent/issues/330 with the goal of correcting the service discovery behavior of a task when its definition did not specify a network mode.
Very graciously, @javabrett submitted a fix for this via https://github.com/aws/amazon-cloudwatch-agent/pull/335. Upon testing this out today, I found out we're not _quite_ there.
Crucially, when network mode is undefined in a task definition, it will parse as `nil`, not the empty string. Correcting this in our unit tests reveals the behavior isn't working as desired, since the `getPrivateIp` function isn't properly handling the `nil` case. I believe this addresses the issue.
1. Updated unit tests to more accurately reflect the value of a task's network mode when unset in ECS and …

ECS Service Discovery: Fixup implicit network mode

---

packaging/dependencies/amazon-cloudwatch-agent.service
translator/util/ec2util/ec2util.go

Closes #395 
Add a simple retry in the EC2 util so that if the network is not immediately available, it can recover gracefully once network is available.
1. Reproduced issue on a CentOS 8 EC2 instance with the 349 version of the agent
2. Confirmed that the network target change in #344 with v350 fixes the issue
3. Ran locally built agent and config-translator binary on the host, after reverting the systemd configuration change
4. Output below shows that at initial startup, the host could not connect to EC2 metadata after the reboot, but recovered after one retry: `2022/03/08 17:51:05 I! 2022/03/08 17:51:04 E! [EC2] network not available yet. …

retry on network failure for detecting EC2

---

plugins/inputs/windows_event_log/wineventlog/utils.go

Performance degrade when high log throughput 
reduce the number of bytes scanning when determine the buffer used returned by Microsoft windows event log api should be doubled.
Manually test new build on soaking host and observe the usage of CPU and mem back to good stat.

cut scan length to 20 bytes

---

plugins/inputs/logfile/logfile_test.go

The `TestLogsFileAutoRemoval` has been in a race condition of removing the first file by using `auto_removal`; however, in some case, the first file has not been removed by the time the [check first file exists](https://github.com/aws/amazon-cloudwatch-agent/blob/master/plugins/inputs/logfile/logfile_test.go#L441-L442) occurs. Therefore, adding `WaitGroup` to wait for the second file to be completely created, then it would delete the first file and the [check first file exists](https://github.com/aws/amazon-cloudwatch-agent/blob/master/plugins/inputs/logfile/logfile_test.go#L441-L442) will be able to pass. 
Add [WaitGroup](https://www.golangprograms.com/goroutines.html) for `TestLogsFileAutoRemoval`.
By submitting this pull request, I confirm that you can use, modify, copy, and …

Add wait group for avoiding checking file exists before removing file

---

translator/translate/csm/rulePort.go
translator/translate/logs/logs.go
translator/translate/util/placeholderUtil.go
translator/translate/util/placeholderUtil_test.go
translator/util/ec2util/ec2util.go

Closes #371
Uses the EC2 metadata to pull the account ID from the instance, and exposes it as a placeholder value that can be replaced as part of the log configuration, so that customers can use the account ID to identify where logs are coming from.
Manually ran test on an EC2 and confirmed that the log group with my account ID was created, and logs were flowing to it.
Note that I tested this by using the account ID as a placeholder replacement for the log group, but it's the same logic for replacing the value in the log stream name, so I'm not super concerned about that. 
```
[ec2-user@ip-172-31-27-74 ~]$ sudo …
```

Allow account ID as placeholder value for log configuration

---

.github/workflows/build-test-linux.yml

Need way to prevent people from merging without go tidy
Add go tidy check
My fork

Add Go Tidy Check To PR

---

.github/workflows/integrationTest.yml

Fails this job when previous test passes. 
do not run this job on previous pass. 
None

Do Not Run montudor/action-zip@v1 When Previous Build Pass

---

.github/workflows/integrationTest.yml
.gitignore
integration/terraform/ec2/linux/main.tf
integration/terraform/ec2/win/main.tf
integration/terraform/ec2/win/providers.tf
integration/terraform/ec2/win/variables.tf

Create windows instance using terraform
Create windows instance using terraform
Ran action on my fork

Add Terraform For Windows Test

---

plugins/outputs/cloudwatchlogs/pusher.go
plugins/outputs/cloudwatchlogs/pusher_test.go

Closes #415 
Currently, when we try to create a log stream and log group (typically when the agent first starts up and sends its first log), there is a potential race condition that can occur when two different instances of the agent attempt to create the same log group. In `pusher.go`, we reuse the same `error` variable, so in the scenario where:
1. Agent A tries to push to CWL and log group doesn't exist
2. Agent B tries to push to CWL and log group doesn't exist
3. Agent B creates log group
4. Agent A fails to create log group because it already exists
The agent log will be confusing, because there will be an instance where the log says the log group does not exist yet, and simultaneously there will be an error that says the log group already exists.
1. Moved all of the log statements …

update error handling to account for ResourceAlreadyExists gracefully

---

.github/workflows/integrationTest.yml

Ubuntu has a non null chance of not install cw agent
Wait until apt lock is opened to install agent. 
Ran on my fork

Use aptdcon Ubuntu Fixes (#426)

---

.github/workflows/build-test-linux.yml
.github/workflows/nightly-build.yml

A change in the GitHub runner to allow using go1.18 breaks releasing because of a dependency in golang/sys/unix. Using the `^1.15` made the runner pick up go1.18 but all of the other build workflows are pinned to `~1.15.15`, so just updating this to match

sync Go version used in GitHub actions to 1.15.15

---

cmd/config-downloader/downloader.go
cmd/config-translator/translator.go
packaging/darwin/amazon-cloudwatch-agent-ctl
packaging/dependencies/amazon-cloudwatch-agent-ctl
packaging/windows/amazon-cloudwatch-agent-ctl.ps1
translator/cmdutil/translatorutil.go
translator/config/mode.go
translator/context/context.go
translator/util/sdkutil.go

There are two changes:
- Add executable path for Darwin since it confuses for the customer when using Darwin but [their executable config json for using is Linux as default for other OS.](https://github.com/aws/amazon-cloudwatch-agent/blob/master/translator/cmdutil/translatorutil.go#L74-L76)
- Change config-translator, config-downloader's `onPrem` mode to `onPremise` mode since it would consistent with [`amazon-cloudwatch-agent-ctl` binary](https://github.com/aws/amazon-cloudwatch-agent/blob/master/packaging/dependencies/amazon-cloudwatch-agent-ctl#L64) and aws-otel-collector is using [`onPremise` too](https://github.com/aws-observability/aws-otel-collector/blob/86d542ef6c9afbab2f5fc94d52a1a2e1f7b839c2/tools/ctl/linux/aws-otel-collector-ctl#L178-L189).
By submitting this pull request, I …

Change to onPremise for all CWAgent component binaries and add executable path for Darwin

---

.github/workflows/build-test-windows.yml
plugins/inputs/windows_event_log/wineventlog/wineventlog.go

Fixes #351 
Fix failing windows event log unit test.
Ignore EvtFormatMessage() errors if data is returned.
Ran `go test` on Windows server 2022 host:
```
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log> go test
C:\Users\ADMINI~1\AppData\Local\Temp\2\CloudWatchAgentTest\Amazon_CloudWatch_WindowsEventLog_MyGroup_MyStream_SystemEventLog
C:\Users\ADMINI~1\AppData\Local\Temp\2\CloudWatchAgentTest\Amazon_CloudWatch_WindowsEventLog_My__Group_____My__Stream_____System__Event__Log__
PASS
ok      github.com/aws/amazon-cloudwatch-agent/plugins/inputs/windows_event_log 0.032s
```
and
```
PS …
```

Fix failing windows event log unit test.

---

.github/workflows/integrationTest.yml

We use over 1 gb of cache for binary and it is not needed. we only get 5gb per repo. 
Just cache the go mod
None

Do Not Cache Full Binary Files As We Use S3

---

.github/workflows/integrationTest.yml

Comments from https://github.com/aws/amazon-cloudwatch-agent/pull/438
Use env var instead of export
None

Gpg sign packages

---

integration/terraform/ec2/linux/README.md
integration/test/agent_util.go
integration/test/cloudwatchlogs/publish_logs_test.go
integration/test/cloudwatchlogs/resources/config_log_rotated.json
integration/test/cloudwatchlogs/resources/write_and_rotate_logs.py
integration/test/cwl_util.go
plugins/inputs/logfile/logfile.go
plugins/inputs/logfile/logfile_test.go
plugins/inputs/logfile/tail/tail.go
plugins/inputs/logfile/tailersrc.go

Closes #447 
Adapted from #455 
1. Added an additional channel in the tailer to capture when the process encounters an error from the log file being deleted
2. Added a cleanup step to delete the state file if the FileDeleted channel is closed (- I was apprehensive about this, but found out that according to https://www.gopl.io/ it's fine to leave a channel unclosed because it will get garbage collected. 
3. Added integration test to validate repro case
4. Updated unit test to reflect new behavior after log file is deleted, to not read from the stored offset
Same tests done in #455.
Integration test output:
```
aws_instance.integration-test …
```

Delete statefile when tailer terminates due to an error

---

.github/workflows/integrationTest.yml

Typo in the integration test YAML file causes the integration tests to not run. 
Fix typo
Ran integration test on my fork and made sure that it actually executed instead of failing immediately.

Fix YAML for terraform destroy

---

RELEASE_NOTES

Missing announcement of GPU metrics in V350 release note.
Release note updated.
N/A

update Release note with GPU metrics info

---

cmd/config-translator/translator_test.go
logger/lumberjack_logger_test.go
plugins/inputs/logfile/logfile.go
plugins/inputs/logfile/logfile_test.go
plugins/inputs/logfile/tail/tail.go
plugins/inputs/logfile/tail/tail_test.go
plugins/inputs/logfile/tailersrc.go
plugins/inputs/windows_event_log/windows_event_log_test.go
plugins/outputs/awscsm/metametrics/listener_test.go
translator/toenvconfig/toEnvConfig_test.go

Fix #381 
Fix Tail.sendLine() to NOT drop log lines when the tailer is dying because of errStopAtEOF.
Updated existing unit tests.
Ran all tests and verified they pass.
```
go test ./plugins/inputs/logfile -run TestLogsFileAutoRemoval -count=100 -v
=== RUN   TestLogsFileAutoRemoval
logfile_test.go:376: Created temp file, /var/folders/7c/rx6r0v6n44j4pwnc_77gt46w0000gs/T/file_auto_removal2801393868
2022/05/16 08:41:34 The state file  for /var/folders/7c/rx6r0v6n44j4pwnc_77gt46w0000gs/T/file_auto_removal2801393868 does not exist: stat : no such file or directory
logfile_test.go:397: Fill temp file with sufficient lines to be read.
2022/05/16 08:41:34 …
```

Fix auto_removal feature so log lines are NOT dropped from old file

---

packaging/windows/amazon-cloudwatch-agent-ctl.ps1

After the introducing of using`cmd /c` for PowerShell ISE and Windows 2022, I accidentally make ADOT Collector exit immediately during CloudWatch Agent execution script. However, CWAgent and Adot Collector should be two independent agents as much as possible (not affecting each other). Therefore, revert the change for exit immediately for Windows CTL Script.
Revert the change for exit immediately with ADOT Collector for Windows CTL Script.
Running the new Windows Script on Windows Server and running our `verify-windows-script` which are in our internal integration test.
1. Run `make fmt` and …

Avoid exit immediately when ADOT Collector fails

---

.github/workflows/integrationTest.yml

Each time we merge a PR, the GitHub workflow will spin up an [integration test](https://github.com/aws/amazon-cloudwatch-agent/blob/master/.github/workflows/integrationTest.yml) to validate our integration test. However, in the EC2 Linux and ECS Fargate, similar OS with different test cases are using the same key cache `ecs-fargate-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}`. This would cause the workflow to always return success after a second retry even though the test failed (e.g Linux RHEL Test has two different tests such as: Check Dimension, Rotating Log; if one of them succeeds, it would submit the same key cache and it would make the second retry return successful for the other test case even though that other test case failed originally).
Therefore, I propose: 
* …

Using different cache key for different test case

---

.github/workflows/integrationTest.yml

CA Bundle Time out 
https://github.com/aws/amazon-cloudwatch-agent/runs/6919650158?check_suite_focus=true
Increase timeout
N/A
Possible better solution would be to download the go mod on instances during the instance builder phase so this is cached in the ami. Since the go mod download took 10 minutes in this test.

Increase Timeout, Sometimes CA Bundle Test Needs More Time To Run

---

integration/test/cloudwatchlogs/publish_logs_test.go

CloudWatch Logs integration tests on GitHub have been flaky, specifically only on the log filter tests.
Deleting the log file after writing forces the agent to flush everything before stopping, so that ensures that everything is published before the next test. It also cleans up any statefile on the test host. I think an obfuscated issue could be that since I'm publishing the same logs in both tests and just applying a filter the second time, is that when the agent starts up it sees there's no new data to read since the offset is the same - this correlates with the fact that just sleeping longer after running the test does not resolve the flakiness so it is not likely that it is a problem or delay in publishing the logs. 
By submitting this pull request, I confirm that you can use, modify, …

Delete log file after done writing in CWL integ test

---

translator/totomlconfig/sampleConfig/complete_windows_config.conf
translator/totomlconfig/sampleConfig/complete_windows_config.json
translator/translate/metrics/config/registered_metrics.go
translator/translate/metrics/metrics_collect/gpu/nvidiaSmi.go
translator/translate/metrics/util/commonconfigutil.go
translator/translate/metrics/util/measurementutil.go

Current Nvidia GPU metrics plugin only works on Linux
Adding a config translation rule for Windows so that with proper configuration, Nvidia GPU metrics will be collected on Windows instances.
Manually tested the feature, unit test the config translation, will add integration test in another PR

Nvidia windows

---

integration/terraform/ec2/linux/main.tf

Need to execute go in non interactive shell. 
Export go path
On my fork
https://github.com/sethAmazon/amazon-cloudwatch-agent/runs/7012889647?check_suite_focus=true

Export Go Bin Path

---

plugins/outputs/cloudwatch/aggregator_test.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go
plugins/outputs/cloudwatch/util.go
plugins/outputs/cloudwatch/util_test.go
plugins/outputs/cloudwatchlogs/pusher.go

When the agent is configured to monitor StatsD, and there is a burst of 10,000 metrics collected and aggregated every minute (same issue if it is done every 5 minutes), the agent's internal buffer of batches will fill up and it will immediately try pushing to CloudWatch. And as soon as that is published the batch will fill up again, and the agent will push again, and again...
This becomes problematic if there are _many_ hosts, because they will all try pushing during the first second of each minute, and will repeat with little to no delay.
Inevitably this will reach the PutMetricData API throttle limit of 150 transaction per second.
Change CloudWatch.publish() to avoid bursting backend when datumBatchChan is full.
Change CloudWatch.backoffSleep() to use jitter.
Update tests.
1. Change API …

Fix CloudWatch.publish() sometimes not jittering.

---

.github/workflows/integrationTest.yml

Change to `${GITHUB_SHA}` since Github Action only recognizes `${GITHUB_SHA}`, `$GITHUB_SHA` or `${{env.GITHUB_SHA}}`
Before changing: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/2636869905
After changing: https://github.com/khanhntd/amazon-cloudwatch-agent/actions/runs/2638538645

Change to env for GITHUB SHA

---

internal/atomiccounter/atomiccounter.go
logs/logs.go
plugins/inputs/logfile/tail/tail.go
plugins/inputs/logfile/tail/tail_test.go
plugins/inputs/logfile/tailersrc_test.go
profiler/profiler.go

Close #432 
Add atomic counter which is modified when files are opened and closed.
Counter is logged once a minute at info level.
Manual test on a Windows 2016 EC2 instance.
Sample log:
```
2022-07-08T20:48:08Z I! [logagent] open file count, 2
2022-07-08T20:49:08Z I! [logagent] open file count, 2
2022-07-08T20:50:08Z I! [logagent] open file count, 2
2022-07-08T20:51:09Z I! [logagent] open file count, 2
2022-07-08T20:51:20Z I! [logagent] piping log from banana.log/i-086864b800a839c94(C:\adam\banana.log.2) to cloudwatchlogs with retention 30
2022-07-08T20:52:10Z I! [logagent] open file count, 3
```
_Before commit the code, please do the following …

Log the open file count once a minute to aid debugging.

---

integration/test/performancetest/performance_query_utils.go
integration/test/performancetest/transmitter.go

The performance benchmarking of CloudWatch Agent does not currently calculate statistics on the data it receives.
Adds statistics calculations on GetMetricData data before it pushes the data into the database.
Unit testing to verify statistics are calculated correctly.

Performance Tracker Statistics Calculation

---

RELEASE_NOTES
cmd/config-downloader/downloader.go
packaging/windows/amazon-cloudwatch-agent-ctl.ps1
translator/util/ec2util/ec2util.go

#471 originally identified an issue related to some debug logging that was added. We tried getting around this with changes to the PS1 script in #473 but this just caused more problems, primarily in that the current state works for Windows OS except for Win2012R2. 
Moved to using the `fmt` package instead of `log`, which pipes the output to stdout instead of stderr, alleviating the original problem, such that we can revert the bandaid fixes that were put on top of it. 
Tested manually the same way I did in #471 to verify no regression in Win2022, and then did a similar manual test on Win2012R2 to confirm that it doesn't break there anymore
_Before …

Fix debug logging and revert Windows ctl script PS1 changes

---

translator/totomlconfig/sampleConfig/log_metric_and_log_on_prem.conf
translator/totomlconfig/sampleConfig/log_metric_only_on_prem.conf
translator/totomlconfig/toTomlConfig_test.go
translator/translate/logs/metrics_collected/kubernetes/kubernetes.go

EC2Tagger is enabled for kubernetes while onPrem which causes agent to fail translation and not start up
Disable ec2tagger for kubernetes while onPremise flag is present
Unit tests confirming ec2tagger is disabled when onprem is enabled

disable ec2tagger for kubernetes when onprem

---

.github/workflows/integrationTest.yml

Go and binary is not caching in integration tests
Remove not needed lines of code. This caused cache to start working again. Not sure what line fixed it. 
Tested cache on my fork 
N/A

Fix Cache Go And Binary

---

.github/workflows/codeql-analysis.yml

Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
https://github.com/github/codeql-action
Update to code ql 2
N/A
N/A

Update Deprecated CodeQL

---

.github/workflows/integrationTest.yml

Do not use zip action
Use install zip then write bash zip.
N/A

Do Not Use Zip Action

---

.github/workflows/clean_ami.yml
.github/workflows/clean_dedicated_host.yml
.github/workflows/integrationTest.yml
.github/workflows/internal-pipeline-dedicated-host-cleaner.yml
.github/workflows/nightly-build.yml
.github/workflows/releaseTest.yml
integration/terraform/ec2/README.md

Still using user roles in tests. 
Remove all user role use
N/A
3. N/A

Only Use Assume Role Creds

---

integration/test/performancetest/performance_query_utils.go

The data returned for memory used is returned in bytes, which can be difficult to interpret easily.
Converts the memory values returned from GetMetricData from bytes to megabytes.
Ran as integration test.

Performance Tracking convert memory byte to megabyte

---

Makefile
cmd/config-translator/translator.go
integration/msi/tools/amazon-cloudwatch-agent.wxs
translator/config/mode.go
translator/context/context.go

support onprem and onpremise and support windows msi installer w silent exec

---

.github/workflows/releaseTest.yml
integration/test/performancetest/performance_query_utils.go
integration/test/performancetest/performance_test.go
integration/test/performancetest/transmitter.go

The release test updates the isRelease attribute but not the hash. We cant to make it so that it also updates the Hash attribute to release's tag's name. This makes it easier to distinguish in frontend and backend.
* releaseTest.yml now feeds in the release tag's name as a env. variable
* UpdateReleaseTag now takes in a release name as a parameter and sets it as Hash in a packet.
* UpdateItem now requires a hash as a separate parameter
* UpdateItem now generates expressionAttributeNames similar to expressionAttributeValues
* PacketMerger now also merges hashes with the updated version similar to isRelease
* Bug Fix: all commits were saved like releases due to a bug in if condition inside PacketMerger, now fixed.
By submitting this pull request, I confirm that you can use, modify, copy, …

Release's Name Update

---

packaging/dependencies/amazon-cloudwatch-agent-ctl

Currently, CWA ctl stop cmd uses `service` cmd instead of `systemctl`. For older linux kernels that come bundled with an older version of `service` cmd, it looks for the `.service` file in a diff location and is unable to properly redirect to `systemctl`.
To avoid relying on `service` cmd properly redirecting to `systemctl`, this change updates to directly use `systemctl`. This brings the stop action in sync with other actions such as disable and runStatus.
Tested `install CWA -> start CWA -> uninstall CWA` on the following EC2s with and without change:
* Amazon Linux 2 Kernel 5.10 AMI 2.0.20220719.0 x86_64 HVM gp2
* Amazon Linux 2 Kernel 4.14 AMI …

Update cwa ctl agent stop to use systemctl instead of service cmd

---

plugins/inputs/logfile/tailersrc.go

An error from removing this file is benign, so it doesn't make sense to make it at error level, but should still distinguish it from regular logs since it is not expected to have a failure. Forgot to add the error in the log that gets emitted, so added that too.

update statefile cleanup error log

---

logs/logs.go
logs/logs_test.go
plugins/outputs/cloudwatchlogs/pusher.go
translator/translate/logs/logs_collected/files/collect_list/collect_list_test.go
translator/translate/logs/logs_collected/windows_events/collect_list/collectlist_test.go
translator/translate/logs/util/validate_retention.go

[todo] https://github.com/aws/amazon-cloudwatch-agent/issues/554
When the same retention is set multiple times for a log group, retention will be set as long as any file_path is created for that log group.
Unit tests + manual tests linked below
3.

Fix duplicate retention case

---

amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/prometheus-eks.yaml

Can't get metric haproxy_backend_http_responses_total
Missing proxy information. Added proxy. 
Created eks cluster in my personal aws account. Use the latest haproxy helm chart. Prometheus scrape worked. 

Fix Source Label Proxy For haproxy_backend_http_responses_total

---

translator/translate/metrics/metrics_collect/ethtool/ethtool_test.go

Ethtool test never ran.
Run ethtool test. Fix type issue in test. 
Ran unit test in intelij. 

Fix Type Issue In Ethtool Test

---

.github/workflows/integrationTest.yml
integration/terraform/ec2/README.md
integration/terraform/ec2/linux/main.tf
integration/terraform/ec2/linux/variables.tf
integration/terraform/ec2/localstack/main.tf
integration/terraform/ec2/localstack/variables.tf
integration/terraform/ec2/win/main.tf
translator/translate/metrics/metrics_collect/ethtool/ethtool.go
translator/translate/metrics/metrics_collect/ethtool/ethtool_test.go

Reduce code for ethool test and change variables and some small fixes for terraform script (both ec2 windows and ec2 linux)
Trigger integration test on my fork: https://github.com/khanhntd/amazon-cloudwatch-agent/actions/runs/2959576825

Reduce code for ethool test and change variables for terraform script

---

translator/totomlconfig/tomlConfigTemplate/tomlConfig.go

Test translator/totomlconfig/toTomlConfig_test.go not translating input config Ethtool struct name correctly
Change struct input Config Ethtool to proper name
Ran test in intelij 

Fix Ethtool Name In Input Config

---

go.mod
go.sum

Upgrade `containerd` to v1.6.8
There are 2 tests I have done:
* `make build` and `make test`
* Using prometheus and k8s container insight to ensure backward compatibility. 
**Prometheus with mem cache app**
**EKS Container Insight**

Upgrade containerd to v1.6.8

---

integration/terraform/ec2/README.md

All e2e tests eventually think they failed because resource cleanup failed, with the initial readme I added. 
Added a couple more policies in order to succeed cleanup after tests.
Verified that cleanups were successful for the test jobs in my personal fork.

Add iam role policy in readme for test cleanup

---

.github/workflows/integrationTest.yml
Makefile
Tools/src/create_darwin.sh
integration/pkg/tools/create_pkg.sh

We only support arm64 mac via rosseta 2 package not natively 
Support arm64 mac natively 
Manually looked at mac basic metrics

Add ARM64 Darwin Support

---

integration/generator/test_case_generator.go
integration/test/metric/cpu.go
integration/test/metric/metric_value_query.go
integration/test/metric/query-json.json
integration/test/metric/stat.go
integration/test/metric_value_benchmark/agent_configs/base_config.json
integration/test/metric_value_benchmark/metrics_value_benchmark_test.go
integration/test/status/test_status.go

Based on our testing decisions, we need to add benchmark testing for metric values. To create a foundation for that, we are starting with adding sanity tests to verify we get values and they are greater than zero for all metrics.
- Added CPU metric value sanity test and query logic, with extensibility for future tests in mind.
- Note that some metrics weren't reporting with this set up, so this test currently fails (see test result below). Need to verify with subject matter experts in the team whether who need. Might need to change validation logic or figure out what to change in the testing environment in order to have those metrics get reported for testing purposes.
- Will refactor the main test function and structure in a way that improves readability and even easier to add new sanity …

Test CPU metric values greater than zero

---

plugins/outputs/cloudwatch/aggregator.go
plugins/outputs/cloudwatch/aggregator_test.go

This test is flaky.
It passes quite often on my dev machine, but fails frequently when github actions runs the unit tests.
The point of this test case is to shutdown before aggregation has "naturally" occurred.
The problem is mainly because the `aggregating()` method has this line:
```
time.Sleep(now.Truncate(durationAgg.aggregationDuration).Add(durationAgg.aggregationDuration).Sub(now))
```
Whch means when a new metric name is first seen and a `durationAggregator` is started, it could take between `aggregationInterval` and `2*aggregationInterval` for the first Aggregation.
You would think the test shouldn't care, it can just shutdown right after `AddMetric` is called and expect the shutdown/flush to happen ASAP.
You'd be wrong because of the randomness of selecting when 2 cases are …

Fix flaky aggregator shutdown test.

---

.github/workflows/integrationTest.yml

Test package is being separated, which meant that changes were needed in our workflow definition files
Make changes to all github workflow steps to make tests run with the new test package
Ran integration test workflow in my fork using the new test package https://github.com/aws/amazon-cloudwatch-agent-test

E2e test package separation

---

go.mod
go.sum

A vulnerable version of kardianos/service is being installed
Upgrades version 1.2.1 to 1.2.2

Upgrade vulnerable kardainos/service 1.2.1 to 1.2.2 to address CVE-2022-29583  

---

.github/workflows/integrationTest.yml

DDB primary index shouldn't be YEAR+CommitDate as that makes the workflow fail if there were two commits on the same day
Commented out as discussed with the team
Tested github workflow and verified the performance test step is gone

Comment out performance test that is buggy and no public release

---

plugins/inputs/windows_event_log/wineventlog/utils.go
plugins/inputs/windows_event_log/wineventlog/utils_test.go
plugins/inputs/windows_event_log/wineventlog/wineventlog.go
plugins/inputs/windows_event_log/wineventlog/wineventlogrecord.go
plugins/inputs/windows_event_log/wineventlog/wineventlogrecord_test.go

In some cases, `EvtFormatMessage` from `wevtapi.dll` does not format the message correctly and leave the message with insertion string placeholders. For example: 
```
Successfully scheduled Software Protection service for re-start at %1. Reason: %2
```
If we find the data from `EventData` attribute,
```
<EventData>
<Data Name='param1'>2022-10-28T22:33:25Z</Data>
<Data Name='param2'>RulesEngine</Data>
</EventData>
```
we should format the message again with these values and the message would become
```
Successfully scheduled Software Protection service for re-start at 2022-10-28T22:33:25Z. Reason: RulesEngine
```
- Update `windowsEventLogRecord` to include `EventData` and `UserData` attribute so that it can unmarshal correctly
- Add helper function `insertPlaceholderValues` to locate …

Fix parsing win event log message

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-macos.yml
.github/workflows/build-test-windows.yml
.github/workflows/integrationTest.yml
.github/workflows/nightly-build.yml
.github/workflows/releaseTest.yml
go.mod

My last PR uses a feature introduced in go 1.19 (sync/atomic).
The GitHub Actions that run unit tests are now failing:
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/3396628110/jobs/5647902403
```
Error: plugins\inputs\logfile\tail\tail.go:27:37: undefined: atomic.Int64
```
CloudWatch Agent is already being built and released using Golang 1.19.2.
Use go 1.19 in GitHub Actions.
```
make release
```

Fix github actions to use go 1.19.

---

go.mod
go.sum

This reverts commit 7f1ad9e65ccf34dc9a22edfa566cec1dea0d5db8. Windows Start-Service will fail when using kardianos/service 1.2.2. Revert to 1.2.1.
kardianos/service 1.2.2 causes this failure:
```
PS C:\Program Files\Amazon\AmazonCloudWatchAgent> .\amazon-cloudwatch-agent-ctl.ps1 -a start
****** Processing amazon-cloudwatch-agent ******
Start-Service : Service 'Amazon CloudWatch Agent (AmazonCloudWatchAgent)' cannot be started due to the following
error: Cannot start service AmazonCloudWatchAgent on computer '.'.
At C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1:132 char:12
+     $svc | Start-Service
+            ~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], …
```

Revert "CVE-2022-29583 (#624)"

---

Tools/src/create_rpm.sh

When trying to build and release CloudWatch Agent I encountered this issue:
```
cp  /tmp/1.247356.0b252215/amd64/amazon-cloudwatch-agent-pre-pkg/amazon-cloudwatch-agent.conf.rpm /tmp/1.247356.0b252215/amd64/amazon-cloudwatch-agent-pre-pkg/amazon-cloudwatch-agent.conf && ARCH=amd64 TARGET_SUPPORTED_ARCH=x86_64 BUILD_SPACE="/tmp/1.247356.0b252215" PREPKGPATH="/tmp/1.247356.0b252215/amd64/amazon-cloudwatch-agent-pre-pkg" ./create_rpm.sh
*************************************************
Creating rpm file for Amazon Linux and RHEL amd64
*************************************************
cat: /tmp/1.247356.0b252215/bin/CWAGENT_VERSION: No such file or directory
```
I verified the above commands work if I modified create_rpm.sh` like so.
This is not an issue for `create_deb.sh` because it does …

Fix create_rpm.sh from reading a file that does not exist.

---

.github/workflows/integrationTest.yml

Fix gpg key singing
Sync changes from private fork
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/3526117643

Sync Use crazy-max/ghaction-import-gpg@v5 From Private Repo

---

packaging/dependencies/amazon-cloudwatch-agent-ctl

On ol9 service alias not starting agent. 
Use systemctl command directly instead to start agent
[_Describe what tests you have done._](https://github.com/sethAmazon/amazon-cloudwatch-agent/actions/runs/3570899143/jobs/6002383229)

Use Systemctl Command To Restart Agent

---

plugins/inputs/logfile/logfile.go
plugins/inputs/logfile/logfile_test.go

Avoid returning a negative offset so that CWA never tries seeking to a negative offset.
add a conditional block.
1. Added to the existing test case
```
go test -count=1 -v ./plugins/inputs/logfile -run TestRestoreState
=== RUN   TestRestoreState
2022/11/30 15:53:50 Reading from offset 9323 in /tmp/logfile.log
--- PASS: TestRestoreState (0.00s)
PASS
ok  	github.com/aws/amazon-cloudwatch-agent/plugins/inputs/logfile	0.739s
```
3. Run `make linter`
I just ran `go fmt` on the 2 modified files.

Change LogFile.restoreState() so it does not return negative offset.

---

.github/workflows/integrationTest.yml

Need to add ECS tests for metrics
Added ECS EC2 Launch Type Daemon Deployment test workflow
Tested on local fork. Need the test package to merge first: https://github.com/aws/amazon-cloudwatch-agent-test/pull/26

Add ECS EC2 Launch Type Daemon Deployment test workflow

---

translator/util/sdkutil.go
translator/util/sdkutil_test.go

In the `DetectAgentMode` function, if `auto` is passed in as the mode and it detects it as on premise, it should return `onPrem` or `onPremise`. Currently, it will return the value passed in which is `auto`. This causes the `SetMode` function in the context to panic (https://github.com/aws/amazon-cloudwatch-agent/blob/main/translator/context/context.go#L109-L120)
Changed the function to return `onPrem` and added a simple unit test.
Added a unit test to cover the auto cases.

Fix DetectAgentMode so auto resolves to onPrem if not ec2

---

.github/workflows/integrationTest.yml

Khanh needed to specify branch for ec2 tests too, not just ecs
Added a way to specify branch for ec2 tests as well
N/A

Add branch feature for ec2 test

---

plugins/inputs/logfile/tailersrc.go

Added log output when log files are deleted with [auto_removal feature](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection). This is related to #636. 
It seems that assignee (pradeepnnv) is  not working on the issue but fewer changes required. So I worked on the issue although suddenly.
It will become more clear that CloudWatch Agent deleted old log files with auto_removal feature.
- Run local test with ```make test```
- Verify behavior in my Amazon Linux 2 instance.
```
$ cat /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log …
```

Add log output when log files are deleted with auto_removal feature #636

---

.github/workflows/integrationTest.yml

Test info is being cut off. 
Reduce test name size to increase test info shown. 
None

Reduce Name Of EC2LinuxIntegrationTest To Show More Test Info In GHA

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-macos.yml
.github/workflows/build-test-windows.yml
.github/workflows/integrationTest.yml
.gitignore

1. Listed more files that don't need to trigger CI checks (namely RELEASE_NOTES)
2. Cleaned up gitignore

ignore unrelated files for CI

---

.github/workflows/clean-aws-resources.yml
go.mod
go.sum
tool/clean/clean_ami/clean_ami.go
tool/clean/clean_dedicated_host/clean_dedicated_host.go
tool/clean/clean_file_system/clean_file_system.go
tool/clean/clean_util.go

You have reached the maximum number of mount targets (400) in your VPC vpc-72252d0a. Delete a mount target and add a new one, use an existing mount target, or work in another VPC.
Remove 30 day old efs
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4246475983/jobs/7383434533

Clean Old File System

---

.github/workflows/build-test-macos.yml
.github/workflows/integrationTest.yml
.github/workflows/nightly-build.yml
Makefile

Mac cpu does not work when not built on mac
Build on mac
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4369091318/jobs/7642769858
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4376206737/jobs/7657975307

Build Make Binary On Mac OS

---

Makefile

CPU plugin does not work when building mac amd64 when trying to run on arm64
Enable cgo for darwin arm64 to allow the go c compiler for arm64 work on amd64
Manually built on my laptop (amd64) and run on mac2 ec2 instance (arm64)

CGO Enable 1 For Darwin arm64

---

Makefile

https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4409404032/jobs/7725650615
Can't enable cgo for arm64 mac when running on linux. 
Add cgo enable only when running on mac.
Unit test

Only Enable CGO For Mac Build On Mac

---

metric/distribution/seh1/seh1_distribution_test.go

Closes #729 
On ARM, the SEH1 unit test fails because one of the expected keys in the map is truncated by one digit of precision, so it can't do an exact match or lookup.
Changed the test to round precision up. There's still 8 digits of precision, which frankly is more than enough. I could have kept it as `map[float64]float64{}`, but this keeps the truncation logic simple. 
After fixing the test:
```
[ec2-user@ip-172-31-57-99 amazon-cloudwatch-agent]$ uname -m
aarch64
[ec2-user@ip-172-31-57-99 amazon-cloudwatch-agent]$ go test -v -run TestSEH1Distribution ./metric/distribution/seh1/
=== RUN   TestSEH1Distribution
--- PASS: TestSEH1Distribution …
```

update SEH test to round

---

.github/workflows/integration-test.yml

Cloudwatch Agent integration test workflow uses a single hardcoded Windows OS for integration tests which is not good test range.
Make the workflow read in the AMI images that were added in the amazon-cloudwatch-agent-test repo for a wider selection of Windows OS
Tested on fork action https://github.com/zhihonl/amazon-cloudwatch-agent/actions/runs/4812727528. All other integration tests have been disabled for this workflow for time efficiency purpose however they should not affect the Windows test since they are not dependencies for it.
Verified that each test instance is using unique AMI ID
```
+ resource "aws_instance" "cwagent" {
+ ami …
```

Use multiple Windows OS for testing

---

.github/workflows/integration-test.yml

Support running EKS integration tests. Dependent on https://github.com/aws/amazon-cloudwatch-agent-test/pull/209
Tested on my fork: https://github.com/SaxyPandaBear/amazon-cloudwatch-agent/actions/runs/4897367790/jobs/8745372731

Add support for running EKS integration tests

---

.github/workflows/integration-test.yml

- Add kubernetes version as a test param
- Add tf directory path param to execute a set of terraform files dynamically 
```
null_resource.validator (local-exec): 2023/05/18 16:45:30 >>>>>>>>>>>>>>Successful<<<<<<<<<<<<<<
null_resource.validator (local-exec): 2023/05/18 16:45:30 ==============EKSStatsD==============
null_resource.validator (local-exec): 2023/05/18 16:45:30 ==============Successful==============
null_resource.validator (local-exec): statsd_counter_1   Successful
null_resource.validator (local-exec): statsd_gauge_2     Successful
null_resource.validator (local-exec): 2023/05/18 16:45:30 ============================== …
```

update eks integration test

---

.github/workflows/integration-test.yml
tool/clean/clean_host/clean_host.go

Currently when terraform fails during integration test, some resources will not get destroyed. Sometimes when the test fails the terraform data on instance launch is lost therefore making it difficult to enforce cleanup after test failure.
Add a name regex to daily resource cleanup code that terminates instances with tag name value of `cwagent-integ-test-ec2` when the instance existed for longer than a day which is sufficient time to run the current tests. Also adds OS names to the instance names for better readabiilty.
In this [test run](https://github.com/zhihonl/amazon-cloudwatch-agent/actions/runs/5017645071/jobs/8996025587), the name regex is …

Add daily cleanup for integration test resource

---

.github/workflows/integration-test.yml

Adds a new github action for testing prometheus on EKS
- Adds an eks_deployment_matrix to generate matrix for the eks prometheus test.
- Creates a EKSPrometheus github action for testing prometheus on eks. 
Tested in a branch of the main repo

Add EKS Prometheus Integration Test

---

.github/workflows/integration-test.yml

Userdata test is incorporated into the larger Linux integration test therefore the test matrix is no longer needed.
Remove userdata test matrix and job strategy from the terraform workflow to reduce unnecessary test cases
[Test run with userdata ran as subset of Linux test](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5248142140/jobs/9479568424). This shows the separate job strategy for userdata test is no longer necessary

Remove uesrdata test from workflow

---

.github/workflows/integration-test.yml

The current setup does not work as a result of a bad merge in the past that mixes up both stress & performance tests.
Cleanup the GHA to only run performance tests for now and the stress tests need some additional work on the test repo itself.
GHA run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5293201956 shows passing performance tests.

Replace stress tests with performance tests

---

.github/workflows/integration-test.yml

macOS tests depend on all Linux tests to pass in order to run. This often prevents macOS test from running at all even though the results of Linux tests should not be relevant for macOS tests.
Remove Linux test as dependency for macOS test
[Test run ](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5286575006)that shows macOS tests running after Linux test failure

Remove Linux test as dependency of macOS test

---

.github/workflows/integration-test.yml

Some stress tests timing out at 30 mins. And since we will add more workloads to these soon, increasing the timeouts to an hour.
Increase timeouts
N/A

Increase timeouts for stress and performance tests

---

tool/clean/clean_host/clean_host.go

We currently do not cleanup windows, performance & stress test stale instances.
Update the name filters to include these.
N/A

Cleanup stale windows, performance & stress test instances

---

.github/workflows/integration-test.yml

Terraform does not support retrieving a list of available dedicated hosts and the filter option is not specific enough to target a single host, therefore we have to use AWS License Manager to help with automatically selecting available host for testing. Adding ARN is necessary to access the resource group.
Add ARN to macOS workflow so it can access the correct resource group
[Test run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5358187762/jobs/9721735913) passed. Required one additional run due to terraform timing out.

Add License Manager ARN for macOS test

---

.github/workflows/integration-test.yml

When terraform_dir is set, we cd into it for `terraform apply` step but when doing the `terraform destroy` step, we always cd into the default dir. This leads to an error saying tf state was never initialized in the default dir.
Example error:
```
This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
```
Apply cd into `terraform_dir` consistently for all steps.
Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5380796203

Apply cd into terraform_dir logic consistently

---

.github/workflows/integration-test.yml

The default duration for the assumed role session is 1 hours. We occasionally see errors due to expired tokens when tests take longer or get rerun due to retries and at fail at the time of terraform destroy.
Increase the role assume duration to 4 hours.
Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5381929551

Increase terraform aws assume role duration to avoid expired token errors

---

.github/workflows/integration-test.yml

In order to exclude test for specific OS, using variables from the test matrix is necessary. We have to modify the flag for `terraform apply` so it can exclude the correct subset of tests 
Add `excludedTests` flag to Linux integration test's `terraform apply`
[Test run](https://github.com/zhihonl/amazon-cloudwatch-agent/actions/runs/5360603893/jobs/9725712414) that removes collectd and mem tests from SLES12. All others OS have complete tests except RenameSSM test because the document is only present on CWAgent test account.

Add excluded_tests flag to Linux test workflow

---

.github/workflows/ec2-integration-test.yml
.github/workflows/integration-test.yml

Onprem tests have been added but not yet automatically run. 
Refactored the existing workflow to share logic with EC2 test workflow since it should be almost 100% same spec-wise.
Tested with https://github.com/aws/amazon-cloudwatch-agent-test/pull/290
Need to merge after that merges. 

Workflow refactor and add onprem test jobs

---

.github/workflows/integration-test.yml

Current performance test only runs for Linux. We should add the workflow for Windows to get a better understanding on how the agent performs on Windows.
Add Windows performance test workflow to integration test.
[Test run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5614285048) showing `family` being read separately for Linux and Windows 

Add family flag to performance test

---

.github/workflows/integration-test.yml

Current stress test only runs for Linux. We should add the workflow for Windows to get a better understanding on how the agent performs on Windows.
Add Windows stress test workflow to integration test.
[Test run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5626361075/job/15247039570) showing the stress test running and retrieving performance metrics as it runs.
Note: system stress tests breached the threshold which is why they are failing. This is an indication that the stress test is working as intended and it is out of scope for this PR to fix the performance issue.
1. Run …

Windows stress test setup

---

.github/workflows/integration-test.yml

Windows performance and stress tests are depending on old names for the build action and causing tests to not run at all. Example: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5658955241 
Change to newest build action name
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5731945038 Made change on a branch and the test started running

Fix dependency action for Windows performance and stress test

---

plugins/inputs/logfile/globpath/globpath.go
plugins/inputs/logfile/globpath/globpath_test.go

The CloudWatch agent does not properly enforce glob patterns in its file configurations. In the scenario where a user supplies something like `[!abc]at`, the agent determines that this has a meta character `[`, but no super meta character `**`. Thus, when the agent tries to find matching files, it defaults to `filepath.Glob`, which does not interpret the `!` inversion operator for the glob pattern. 
Updated the `Match` function so that it doesn't use `filepath.Glob` when there are nonstandard glob characters that are not operable with `filepath.Glob`, such as `!`. Updated the `Compile` function to change the short-circuit behavior, since there is technically a glob that needs to be compiled, even for the characters that can be interpreted in `filepath.Glob`. 
To illustrate this, I added a …

fix file glob matching

---

.github/workflows/integration-test.yml

We want to to test if EMF still works with EC2 metadata turned off. 
Add `metadataEnabled` variable to have test case where EC2 metadata is turned off for ECS integration test.
Test run for CCWA: https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/5731828918/job/15533934402
Test run for CWA: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/5731945038/job/15534084015#step:7:721
Test failed when metadata is disabled. We need to investigate this and have a separate PR to address the issue.

Add metadata flag for ECS test

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

Enhanced container insights control plane metrics do not have units.  
The prometheus receiver that ingests these metrics does not assign them units.  We can add units by correctly configuring the EMF exporter

add units for control plane metrics

---

cfg/aws/credentials.go
cfg/aws/shared_config.go
cfg/aws/shared_config_test.go

The AWS SDK implementation for getting the user home directory for the default shared config files changed from purely environment variables ([v1.44.106](https://github.com/aws/aws-sdk-go/blob/v1.44.106/internal/shareddefaults/shared_config.go#L33)) to a fallback on getting it from the OS in [more recent versions](https://github.com/aws/aws-sdk-go/blame/v1.44.332/internal/shareddefaults/shared_config.go#L32). This change breaks the credential ordering when running as root and the agent with systemd. In the previous version, the environment variables would not resolve properly and would result in the SDK trying to use `.aws/credentials` rather than `/root/.aws/credentials`, which would allow it to fallthrough to the EC2RoleProvider.
Sets the fallback shared config files using the backwards …

Add fallback shared config files for credential ordering.

---

tool/clean/clean_host/clean_host.go

The host cleaner job has been failing repeatedly, leading to a gradual accumulation of unused, active hosts.
* Fixes type mismatch with `MaxResults` field in the DescribeInstances input
* Adds `Ec2IntegrationTest` to the name filter
Successful job execution: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6007121747/job/16292796917

Fix failing host cleaner action due to type mismatch

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

Implementing apiserver flowcontrol metrics
Implementing apiserver_flowcontrol_request_concurrency_limit and apiserver_flowcontrol_rejected_requests_total

Implementing apiserver flowcontrol metrics

---

cfg/aws/credentials.go
handlers/agentinfo/info.go
handlers/agentinfo/info_test.go

We want insight into the potential impact that removing the fallback override logic would have.
Adds a shared config fallback stat to the agent info. Similar to https://github.com/aws/amazon-cloudwatch-agent/pull/838.

Add shared config fallback stat to agent info.

---

receiver/adapter/accumulator/accumulator.go
receiver/adapter/accumulator/accumulator_test.go
receiver/adapter/accumulator/testutil.go

We currently log a warning during metric filtering/conversion with "Filter and convert failed" even when filtering is valid. This is leading to confusion when doing log dives. Metric filtering is fine and is done using the same telegraf functions that we were using before.
Changed the accumulator to only log the warning if the telegraf metric had fields and they were all dropped during our value conversion.
Ran unit tests. Add unit tests.

Remove misleading metric filter warning

---

internal/util/type_conversion.go
internal/util/type_conversion_test.go
metric/distribution/distribution.go
metric/distribution/distribution_test.go
metric/distribution/regular/regular_distribution.go
metric/distribution/regular/regular_distribution_test.go
metric/distribution/seh1/seh1_distribution.go
metric/distribution/seh1/seh1_distribution_test.go
plugins/outputs/cloudwatch/aggregator.go
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go
receiver/adapter/accumulator/accumulator.go
receiver/adapter/accumulator/accumulator_test.go
receiver/adapter/accumulator/metrics_test.go

The CloudWatch Agent doesn't currently account for NaN or Inf values. When we have aggregation enabled, we will add these metrics to the distribution. When the regular distribution is [converted](https://github.com/aws/amazon-cloudwatch-agent/blob/main/plugins/outputs/cloudwatch/util.go#L87) into an SEH one, we're unable to retrieve the counts for the NaN value due to the way GoLang handles NaN lookups. This leads to an empty distribution list and the CloudWatch Agent creates the individual metric datum instead of the aggregate. CloudWatch does not support NaN values.
- Drop NaN/Inf/Out of range values during OTEL conversion.
- Rejects NaN/Inf/Out of range values when they reach the distributions.
- Drop individual MetricDatums with NaN/Inf/Out of range values.
Matches …

Drop unsupported NaN, Inf, and out of range values.

---

plugins/inputs/windows_event_log/windows_event_log.go
plugins/inputs/windows_event_log/windows_event_log_test.go

Currently, when the agent start in windows both log agent and telegraf start the windows log event plugin. As a result, the the plugins generates duplicate logs.
Changed the start function of the plugin to be exclusively ran once to avoid any duplicate plugin calls to be started.
Created and ran a units test this can be seen in  [TestWindowsDuplicateStart](https://github.com/aws/amazon-cloudwatch-agent/blob/95e3f82cafd164ddae91c9e30246187af8bb8484/plugins/inputs/windows_event_log/windows_event_log_test.go#L106)
Also ran integration test:  [this is the instance where there is only logs](https://github.com/aws/amazon-cloudwatch-agent-test/pull/346) …

Fix windows event logs to only starts once

---

plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

Closes https://github.com/aws/amazon-cloudwatch-agent/issues/672
When we create the aggregate dimensions in `ProcessRollup`, we have a check to prevent duplicate dimension sets from occurring. The [reflect.DeepEqual](https://pkg.go.dev/reflect#DeepEqual) comparison requires the order to be the same.
> Slice values are deeply equal when all of the following are true: they are both nil or both non-nil, they have the same length, and either they point to the same initial entry of the same underlying array (that is, &x[0] == &y[0]) or their corresponding elements (up to length) are deeply equal. Note that a non-nil empty slice and a nil slice (for example, []byte{} and []byte(nil)) are not deeply equal. 
This means that if the metric has dimensions `[a, b, c]` and the configuration is `[[a, …

Prevent aggregate dimension duplicates.

---

.github/workflows/otel-fork-replace.yml
go.mod
go.sum

We made the fix for the concurrent decode bug in `pkg/stanza` as part of https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/72, but never added a replace directive in our go.mod to include the change in the agent.
Adds the replace in the go.mod and added it to the `otel-fork-replace.yml` workflow.
Ran an EMF generator with 10 connections/10 threads/~500ms between messages.
`v1.300026.3` saw corrupted messages after a couple minutes.
Built the agent and ran the generator for over an hour. No longer saw corrupted messages.
2. Run …

Replace stanza package to include concurrent decode bug fix.

---

translator/tocwconfig/sampleConfig/base_container_insights_config.yaml
translator/tocwconfig/sampleConfig/complete_darwin_config.yaml
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/complete_windows_config.yaml
translator/tocwconfig/sampleConfig/config_with_env.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/log_ecs_metric_only.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/prometheus_config_linux.yaml
translator/tocwconfig/sampleConfig/prometheus_config_windows.yaml
translator/tocwconfig/sampleConfig/trace_config_linux.yaml
translator/tocwconfig/sampleConfig/trace_config_windows.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

`amazon-cloudawtch-agent` update for this PR: https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/96
1. implement requested aggregations
2. updated tests to pass, and also style fixes like unquoting imds_retries
Tested end to end
Crash:
No crashes:
New kube-apiserver metrics
3. Run `make lint`

update enhanced CI metrics and aggregations and update tests

---

go.mod
go.sum

With OTel upgrade to v0.84.0, it also upgraded `mapstructure` to v1.5.1 that brings along a [change in behavior](https://github.com/mitchellh/mapstructure/pull/266) where empty slices overwrite the OTel defaults that would have been used when unmarshalling from yaml.
An example is where the yaml generated via config translation typically has `service->telemetry->logs->output_paths` set to `[]` and when initializing the OTel collector, the default is `["stderr"]`.
Post this change, the `[]` would overwrite the default `["stderr"]` thus discarding all logs.
As an example, unmarshalling the following into an OTel.Config with v1.5.0 results in `output_paths` being set to the default i.e. `["stderr"]`. But doing the same with v1.5.1 results in `output_paths` being set to `[]`.
```
service: …
```

Pin github.com/mitchellh/mapstructure to v1.5.0

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

`apiserver_storage_size_bytes is duplicated, one of the instances should be `apiserver_storage_db_total_size_in_bytes`
replaced the duplicate instance
unit tests

fix apiserver_storage_db_total_size_in_bytes

---

packaging/linux/amazon-cloudwatch-agent.spec

Can't install rpm on the kernel patchless version of al2 
Use Gzip 6 RPM Compression for rpm build spec
Current binary size 76mb new binary size 96mb 
Current install time 11 seconds new install time 5 seconds 
Manually build on al2 with kernel patch.
Install on al2 without kernel patch. 

Use GZIP 6 RPM Compression To Fix Install On AL2 Without Kernel Patch

---

internal/retryer/imdsretryer.go
translator/util/ec2util/ec2util.go

If imdsv2 fails on windows starting with user data there will be a log line to standard error causing agent to fail. 
Log imds failures to standard out instead so windows user data will not fail. 
None

If IMDSV2 Fails Log fmt.Printf Not log.Printf

---

cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go

Avoid potential misconfiguration exposing agent debug info externally.
Improved the `--help` text for the `--prof-addr` option.
Added a check to ensure that the address is `localhost:nnnn`
- Manual testing:
```
amazon-cloudwatch-agent --pprof-addr 123
2023-10-06T14:46:12Z W! Not starting pprof, it is restricted to localhost:nnnn
2023-10-06T14:46:12Z E! [telegraf] Error running agent: no config file specified
amazon-cloudwatch-agent --pprof-addr localhost
2023-10-06T14:46:18Z I! Starting pprof HTTP server at: http://localhost/debug/pprof
2023-10-06T14:46:18Z E! [telegraf] Error running agent: no config file specified
2023-10-06T14:46:18Z E! listen …
```

restrict pprof-addr to localhost

---

cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
cmd/start-amazon-cloudwatch-agent/path.go
cmd/start-amazon-cloudwatch-agent/path_windows.go
cmd/start-amazon-cloudwatch-agent/start-amazon-cloudwatch-agent.go
tool/paths/paths.go
tool/paths/paths_unix.go
tool/paths/paths_windows.go

The problem is some users directly start the `amazon-cloudwatch-agent` program.
Until recently there was no `-otelconfig` option.
Now there is, and it is breaking some users (missing metrics).
Most of the changes are refactoring some common code from `start-amazon-cloudwatch-agent` into `tools/paths` package. Ultimately I just want to reuse the same variable the `start-amazon-cloudwatch-agent` program uses when it generates the YAML config.
- `make build`, `make test`
- Manually copied the linux_amd64 binaries to a test host and started the agent with the default linux config.
1. Run `make …

Use default value when -otelconfig option not given

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

`apiserver_current_inqueue_requests` was missing
adds `apiserver_current_inqueue_requests` to the declarations
tested end to end

add missing apiserver_current_inqueue_requests declaration

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

Move to container status metrics
See https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/109
Updated metrics/units:
tested end to end, see screenshots aove

update enhanced CI metrics and tests for pod_container_status metrics

---

translator/tocwconfig/sampleConfig/no_skip_log_timestamp.conf
translator/tocwconfig/sampleConfig/no_skip_log_timestamp.json
translator/tocwconfig/sampleConfig/no_skip_log_timestamp_windows.conf
translator/tocwconfig/sampleConfig/no_skip_log_timestamp_windows.json
translator/tocwconfig/sampleConfig/skip_log_timestamp.conf
translator/tocwconfig/sampleConfig/skip_log_timestamp.json
translator/tocwconfig/sampleConfig/skip_log_timestamp_default.conf
translator/tocwconfig/sampleConfig/skip_log_timestamp_default.json
translator/tocwconfig/sampleConfig/skip_log_timestamp_default_windows.conf
translator/tocwconfig/sampleConfig/skip_log_timestamp_default_windows.json
translator/tocwconfig/sampleConfig/skip_log_timestamp_windows.conf
translator/tocwconfig/sampleConfig/skip_log_timestamp_windows.json
translator/tocwconfig/tocwconfig_test.go
translator/translate/agent/ruleLogFile.go
translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go

The customer noticed the issue because we now log the toml output on start of agent. This includes a line with the date format that is old. 
We keep logging the same entry for a bad time stamp config when recording agent logs.
```
{
"agent": {
"logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
},
"logs": {
"logs_collected": {
"files": {
"collect_list": [
{
"file_path": "/var/log/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.log",
"log_group_name": "stage-InstanceLogGroup",
"log_stream_name": "(v124-1) - /var/log/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.log",
"timestamp_format": "%Y-%m-%d%H:%M:%S"
}
]
}
},
"force_flush_interval" : 15
}
}
```
If we have a valid timestamp in the log we will not keep logging the same log line. 
```
{
"agent": …
```

Skip Timestamp For Agent Log

---

plugins/inputs/logfile/logfile_test.go
plugins/inputs/logfile/tail/tail.go
plugins/inputs/logfile/tail/tail_test.go

Previously there this issue - https://github.com/aws/amazon-cloudwatch-agent/issues/381
Which was fixed by - https://github.com/aws/amazon-cloudwatch-agent/pull/452
But now instead of an edge case where the agent will DROP log lines, the issue is that the agent will BLOCK waiting to upload ALL log lines and potentially miss discovering and reporting on a new file.
Consider the following events:
1. File 1 is created, discovered, and reported
2. File 2 is created, and discovered, but the agent is not finished reading File 1, so `LogFile.FindLogSrc()` is blocking.
3. Before `LogFile.FindLogSrc()` completes, another 2 files matching the monitored pattern are created (File 3 and File 4)
4. When the agent is done reading FIle 1 it deletes it and begins monitoring File 2.
5. The Agent discovers …

Auto removal no block

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

pod_interface_network_rx_dropped  & pod_interface_network_tx_dropped will have dimensions of [ClusterName,Namespace] instead of [ClusterName,Namespace, Service]. The rest of the dimension sets are unaffected

Removing service dimension for pod-net metrics

---

cfg/envconfig/envconfig.go
cfg/envconfig/envconfig_test.go
cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
extension/agenthealth/config.go
extension/agenthealth/config_test.go
extension/agenthealth/extension.go
extension/agenthealth/extension_test.go
extension/agenthealth/factory.go
extension/agenthealth/factory_test.go
extension/agenthealth/handler/useragent/handler.go
extension/agenthealth/handler/useragent/handler_test.go
extension/agenthealth/handler/useragent/useragent.go
extension/agenthealth/handler/useragent/useragent_test.go
extension/agenthealth/testdata/config.yaml
go.mod
go.sum
internal/version/version.go
internal/version/version_test.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go

The agenthealth extension implements the `awsmiddleware.Extension` interface and provides the request/response handlers to configure on the AWS Clients. This allows the agent's user agent to be prepended on AWS requests.
Adds the agenthealth extension scaffolding with a user agent handler. There's a singleton user agent that gets updated by its `Set*` functions. On each change, the handler is updated and on each requests, the user agent string is added.
Adds unit tests.

Add agenthealth extension with user agent handler.

---

cfg/aws/credentials.go
cfg/envconfig/envconfig.go
cfg/envconfig/envconfig_test.go
extension/agenthealth/extension.go
extension/agenthealth/extension_test.go
extension/agenthealth/factory.go
extension/agenthealth/handler/stats/agent/agent.go
extension/agenthealth/handler/stats/provider/flag.go
extension/agenthealth/handler/stats/provider/flag_test.go
go.mod
go.sum
plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go
plugins/outputs/cloudwatch/config.go
plugins/outputs/cloudwatch/factory.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go
plugins/outputs/cloudwatchlogs/pusher.go
plugins/outputs/cloudwatchlogs/pusher_test.go
plugins/processors/ec2tagger/ec2metadataprovider.go
translator/config/envconst.go
translator/util/ec2util/ec2util.go

Depends on https://github.com/aws/amazon-cloudwatch-agent/pull/920
With the agenthealth extension set up, all output/exporter components should use the same set up for consistency.
Replaces all uses of agentinfo with agenthealth. TODOs will be resolved after #920 is merged in.

Replace uses of agentinfo with agenthealth.

---

extension/agenthealth/handler/stats/agent/agent.go
extension/agenthealth/handler/stats/agent/agent_test.go
extension/agenthealth/handler/stats/client/client.go
extension/agenthealth/handler/stats/client/client_test.go
extension/agenthealth/handler/stats/handler.go
extension/agenthealth/handler/stats/provider/flag.go
extension/agenthealth/handler/stats/provider/flag_test.go
extension/agenthealth/handler/stats/provider/interval.go
extension/agenthealth/handler/stats/provider/interval_test.go
extension/agenthealth/handler/stats/provider/process.go
extension/agenthealth/handler/stats/provider/process_test.go
extension/agenthealth/handler/useragent/handler.go
extension/agenthealth/handler/useragent/useragent.go
plugins/outputs/cloudwatchlogs/cloudwatchlogs.go

There are a couple of issues that these changes are addressing:
- The payload bytes for the client stats were always 0.
- This was because the client stats were placed at the front of the build step instead of at the back, so the body had not been created yet.
- The new flag stats (RegionType, Mode, etc.) were not showing up.
- This was because they weren't added to the `Stats.Merge` function, so they weren't being included.
- Client stats weren't always present.
- This was due to lock contention.
- Replace some locks with atomics. Change the mutex guarding the `sync.Once` to a `sync.RWMutex` since it is only changed once a minute, so the lock shouldn't block for reads.
- Fix payload measurement by moving the client stats handler to after the rest of the build step handlers.
- Add flag …

Fix client stats payload measurement

---

extension/agenthealth/handler/stats/client/client.go
extension/agenthealth/handler/stats/client/client_test.go

With the introduction of the agenthealth extension, the latency metric increased from ~30-40ms to ~80-90ms. This appears to in part be due to the payload size calculation.
Instead of using `request.GetBody`, which creates a copy of the existing request body, and `io.Copy`, try to use the `request.ContentLength` if it's available. If not, try to follow the [AWS SDK content length calculation method](https://github.com/aws/aws-sdk-go/blob/main/aws/corehandlers/handlers.go#L39). If all of that fails, then fall back on the `io.Copy`.
Updated unit tests. Built and ran the agent. Latency is now ~30-40ms
```
2023-10-27T21:48:08Z D! stats header …
```

Change payload size measurement method for client stats

---

translator/translate/otel/extension/agenthealth/translator.go
translator/translate/otel/extension/agenthealth/translator_test.go

The agenthealth translator was not respecting the `usage_data` field in the `agent` section of the config.
Updated the translator to check the `usage_data` field. If either the field or the environment variable are false, then it will be false.
Updated unit tests.

Check the usage_data in the config.

---

RELEASE_NOTES

Update RELEASE_NOTE for `v1.300030.0` and previous

Update RELEASE_NOTES for 1.300030.0

---

translator/translate/otel/receiver/adapter/translators.go

CloudWatch agent team released major version v1.3x which migrates to OpenTelemetry. Old agent with major version 1.2x silently passes when measurement field is empty because the plugins with empty measurement field will be removed during translation, therefore not emitting anything for that metric.
New version will fail the agent during startup because the OTEL translators will still include the plugins with empty measurement field in the YAML config but the component will not be recognized.
To achieve backward compatibility and avoid breaking existing customers config that may be using the empty measurement field, we will allow empty measurement but print out a warning message to remind the customers.
By submitting this pull request, I confirm that you can use, modify, copy, and …

Fix empty measurement field causing agent crash

---

plugins/processors/awsappsignals/processor.go

The mutator list was being overridden in the start function of the awsappsignalsprocessor. This causes the keep rules to never take effect. This is a bugfix to have the dropper rules by appended, not overwriting the list.
Use append instead of a direct assignment of the list
Manual testing by using the keeper rule on an EKS cluster.

[awsappsignalsprocessor] Bugfix: Append dropper rules to the mutators

---

plugins/outputs/cloudwatchlogs/pusher.go
translator/defaultKeyCase.go
translator/isValid.go
translator/translate/logs/logs_collected/files/collect_list/collect_list_test.go
translator/translate/logs/logs_collected/files/collect_list/ruleLogGroupClass.go
translator/translate/logs/logs_collected/files/collect_list/ruleLogGroupClass_test.go
translator/translate/logs/logs_collected/windows_events/collect_list/collectlist_test.go
translator/translate/logs/logs_collected/windows_events/collect_list/ruleLogGroupClass.go

In regions where the LogGroupClass parameter is not yet deployed, customers are unable to create LogGroups, even with valid configurations.
When a customer defines a config without a `log_group_class`, the agent will no longer send a CreateLogGroup request with a `STANDARD` log group class. Instead, the CreateLogGroup request will be made without the `LogGroupClass` parameter, which the CWL Service also accepts as a `STANDARD` Log Group Class 
On us-gov-west-1, I deployed the following config
```
{
"agent": {
"run_as_user": "root",
"debug": true
},
"logs": {
"logs_collected": {
"files": {
"collect_list": [
{
"file_path": …
```

Removes LogGroupClass parameter in CreateLogGroup request when customer config does not define parameter

---

go.mod
go.sum
translator/translate/otel/common/eksdetector.go
translator/translate/otel/common/eksdetector_test.go

Currently, the CWA is unable to distinguish between EKS and native Kubernetes. 
This change implements an EKS detector which can determine if the agent is on an EKS cluster or native K8s. It does this by checking for the aws-auth configmap in the kube-system namespace, which is only present if it's an EKS cluster.
Unit  tests.
Not being used anywhere currently. Pending confirmation of k8s configurations

implement eksdetector

---

translator/tocwconfig/sampleConfig/appsignals_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/translate/otel/exporter/awsemf/appsignals_config_eks.yaml
translator/translate/otel/exporter/awsemf/appsignals_config_generic.yaml

We want to expand the list of dependency rollup metrics for App Signals with the following dimensions: `[RemoteService, RemoteTarget]` and `[HostedIn.<Attributes>, Service, RemoteService, RemoteTarget]`
Added the following metric rollups to the 2 AppSignal Configuration files.
- `[RemoteService, RemoteTarget]`
- `[HostedIn.<Attributes>, Service, RemoteService, RemoteTarget]`
Followed GH Workflow Environment setup guide in: https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/testing#how-to-test-e2e-resource-changes
Setup E2E GH Workflow tests for EKS+EC2 in personal local fork from: …

[App Signals] Update dependency metric rollups list

---

plugins/processors/awsappsignals/common/types.go
plugins/processors/awsappsignals/config/config.go
plugins/processors/awsappsignals/factory.go
plugins/processors/awsappsignals/internal/cardinalitycontrol/count_min_sketch.go
plugins/processors/awsappsignals/internal/cardinalitycontrol/count_min_sketch_test.go
plugins/processors/awsappsignals/internal/cardinalitycontrol/metrics_limiter.go
plugins/processors/awsappsignals/internal/cardinalitycontrol/metrics_limiter_test.go
plugins/processors/awsappsignals/processor.go
plugins/processors/awsappsignals/processor_test.go
plugins/processors/awsappsignals/rules/keeper.go
plugins/processors/awsappsignals/rules/keeper_test.go
plugins/processors/awsappsignals/rules/replacer.go
plugins/processors/awsappsignals/rules/replacer_test.go
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.json
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.json
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/translate/otel/processor/awsappsignals/testdata/invalidRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigEKS.yaml
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigGeneric.yaml
translator/translate/otel/processor/awsappsignals/translator.go

This PR is an updated version from https://github.com/aws/amazon-cloudwatch-agent/pull/1000, Since @bjrara is not available atm so I create this new PR with a few changes below. 
1. Removed Metrics labels referenece in `MetricData` structure
2. Disabled Metric Limiter by default until AppSignals console team completed the related changes for supporting E2E CX.
Due to the nature of metrics generated from auto-instrumentation, high cardinality metrics may occur if attributes which are intended to have low cardinality, are assigned values with high cardinality.
A new component `metric_limiter` is introduced into `awsappsignalsprocessor` to enhance cardinality control. Customers can set `drop_threshold` to indicate the anticipated number of low cardinality metrics for each `service`. The …

Add metrics cardinality control for Application Signals

---

plugins/processors/awsappsignals/internal/resolver/kubernetes.go
plugins/processors/awsappsignals/internal/resolver/kubernetes_test.go

* set resource attribute `aws.log.group.names` to be the application log group name for Container Insights use case so that later we can correlate application logs with traces
`make test`

add application log group info for AppSignals

---

logger/logger.go
plugins/outputs/cloudwatchlogs/pusher.go

CloudWatch Agent  introduced a warning log when timestamp falls back to an older valid timestamp https://github.com/aws/amazon-cloudwatch-agent/pull/870 
This log isn't throttled and can produce excessive warning logs when timestamp isn't parsing
Set the warning log message to print per set interval time
Manually tested confirmed warning log prints per set interval (default 5 minutes)

Add reduce lastvalid timestamp warn logs frequency

---

translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/otel/exporter/awsxray/translator.go
translator/translate/otel/exporter/awsxray/translator_test.go
translator/translate/otel/pipeline/appsignals/translator.go

E2E EC2 integration tests were failing for appsignals. This was caused by the translation not including the resourcedetection processor for EC2 route.
- Adds logic to include the resourcedetection translation if on EKS or EC2 (Not included if on native K8s)
- Fixes Unit Testing that missed the bug
- Modified xray exporter translation to include the correct attributes depending if on EKS, K8s or EC2
unit tests, passes integ tests

[AppSignals][Bug Fix] Ensure resource detection processor is translated for EC2

---

.github/workflows/integration-test.yml
plugins/processors/awsappsignals/processor.go
plugins/processors/awsappsignals/processor_test.go

The adot/otel language instrumentation sdks sometimes sends metric names in lowercase over otlp. This PR maps the application signals metrics from lowercase to uppercase (ex: error -> Error)
Add a map for lowercase metrics to the uppercase ones for emission
Passed 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7975715500/job/21774963354

awsappsignals processor: check for case insensitivity in metric names

---

internal/util/testutil/testutil.go
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/tocwconfig/sampleConfig/kubernetes_on_prem_config.yaml
translator/translate/otel/exporter/awsemf/translator.go
translator/translate/otel/exporter/awsemf/translator_test.go
translator/translate/otel/exporter/awsxray/translator.go
translator/translate/otel/extension/awsproxy/translator.go

We are currently not setting all the required fields for our components during translation that are required to work on envs when IMDS isnt available.
* Consistently set fields on our components.
* Remove deviation in awsemfexporter translator for APM to make it consistent with remaining plugins.
* Unit tests

[AppSignals] Update components translators to set missing fields

---

plugins/processors/awsappsignals/internal/cardinalitycontrol/metrics_limiter.go
plugins/processors/awsappsignals/internal/cardinalitycontrol/metrics_limiter_test.go

Most of  high cardinality metrics case in AppSignals. the high cardinality values will come from Local and Remote Operation dimensions. and we do want to keep some of the key dimensions if it will not be in the high cardinality situation. So in this changes, we will keep the original dimension value of RemoteService that was previously overrode by MetricLimiter, but change RemoteOperation dimension value to `AllOtherRemoteOperations`
The new MetricLimiter overall aggregation rule, we don't aggregate the dimension of `LocalService`, `RemoteService` and `HostedIn_*` dimensions . We will replace `LocalOperation` to `AllOtherOperations` and `RemoteOperation` dimension into `AllOtherRemoteOperations` . The rest of other dimension values  into "-"
By submitting this pull request, I confirm that …

Do not update RemoteService dimension on the to be aggregated dependency metrics

---

Makefile
amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/localbin/Dockerfile

Docker supports multiple .dockerignore files (https://docs.docker.com/build/building/context/#filename-and-location). This allows us to copy in the built binaries directly instead of copying them around.
Replaces the `localbin` Dockerfile so it follows the pattern in the `source`. Uses a scratch base image. Renamed Makefile targets to separate `build-for-docker`, which builds the binaries, from `docker-build`, which builds the image. Separates the image name into parts to make it easier to replace for dev builds.
Built and pushed the image.
2. Run `make …

Use local dockerignore instead of tmp directories.

---

plugins/processors/awsappsignals/internal/attributes/attributes.go
plugins/processors/awsappsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsappsignals/internal/normalizer/attributesnormalizer_test.go

We want to extract SDK metadata and export them into EMF logs to identify SDK vendor, version, language and instrumentation mode.
Add `SDK` as a new attribute in App Signals metrics.
Output samples:
```
// auto-instrumented sample app using ADOT
SDK: opentelemetry,1.32.0-aws-SNAPSHOT,java,Auto
```
```
// if sdk info is missing
SDK: -,-,java,Manual
```

Add sdk metadata to metric attributes for EMF export

---

plugins/processors/awsappsignals/config/config.go
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/translate/otel/processor/awsappsignals/testdata/invalidRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigEKS.yaml
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigGeneric.yaml
translator/translate/otel/processor/awsappsignals/translator.go

When not explicitly set, the current validate logic doesnt seem to get invoked before the start of the component, so it doesnt respect the default GC collection interval causing an infinite loop leading to CPU maxing out.
Explicitly set the GC collection interval when initializing the config.
Manually tested on an EKS cluster that CPU spike goes away.

[AppSignals] Explicitly set the GCCollectionInterval for MetricsLimiter

---

RELEASE_NOTES
plugins/processors/awsappsignals/config/config.go
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/translate/otel/processor/awsappsignals/testdata/invalidRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfig.json
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigEKS.yaml
translator/translate/otel/processor/awsappsignals/testdata/validRulesConfigGeneric.yaml
translator/translate/otel/processor/awsappsignals/translator.go

(cherry picked from commit fd00839da868b979ea1d3ca568b45143bf98cf05)
See https://github.com/aws/amazon-cloudwatch-agent/pull/1093
See https://github.com/aws/amazon-cloudwatch-agent/pull/1093
See https://github.com/aws/amazon-cloudwatch-agent/pull/1093

[AppSignals] Explicitly set the GCCollectionInterval for MetricsLimiter (#1093)

---

plugins/inputs/logfile/fileconfig_test.go

We experienced timezone issues with other products and want to ensure CloudWatch Agent is also in a good state. After code audit, we are missing edge case unit test where the timezone is set to a valid value from the host timezone options but not allowlisted in the agent.
Add unit test to check for timezone that is not allowlisted by the agent(We only use timezone when it's specified to UTC, if not, default to local)
Unit test

Add unit test to ensure log timestamp defaults to local timezone

---

internal/mapstructure/encoder.go
internal/mapstructure/encoder_test.go
internal/mapstructure/marshaler.go
internal/mapstructure/marshaler_test.go
translator/cmdutil/translatorutil.go

The encoder was added to the OTEL collector core a while back, but getting fixes and further changes has been slow. This has resulted in numerous workarounds like https://github.com/aws/amazon-cloudwatch-agent/blob/487bfcf661fa16067184644fd49685b3aa99d5a8/translator/cmdutil/translatorutil.go#L239
and even forking a component (https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/99) for the sole purpose of fixing marshaling issues.
Moves the mapstructure encoder (https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap/internal/mapstructure) back into the agent.
Adds existing unit tests back.
_Before commit …

Add back mapstructure encoder

---

internal/mapstructure/encoder.go
internal/mapstructure/encoder_test.go
internal/mapstructure/marshaler.go
translator/cmdutil/translatorutil.go
translator/tocwconfig/sampleConfig/advanced_config_darwin.yaml
translator/tocwconfig/sampleConfig/advanced_config_linux.yaml
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/tocwconfig/sampleConfig/base_container_insights_config.yaml
translator/tocwconfig/sampleConfig/complete_darwin_config.yaml
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/complete_windows_config.yaml
translator/tocwconfig/sampleConfig/config_with_env.yaml
translator/tocwconfig/sampleConfig/delta_config_linux.yaml
translator/tocwconfig/sampleConfig/delta_net_config_linux.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/tocwconfig/sampleConfig/log_ecs_metric_only.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/standard_config_linux.yaml
translator/tocwconfig/sampleConfig/standard_config_linux_with_common_config.yaml
translator/tocwconfig/sampleConfig/trace_config_linux.yaml
translator/tocwconfig/sampleConfig/trace_config_windows.yaml

Now that the encoder/marshaler is in the agent again, omitting the `configopaque.String` should be done at the encoder level.
Adds a nil hook and `OmitAllNil` option, which when combined will omit the `configopaque.String`. Replaced `RemoveTLSRedacted`.
Updated unit tests.

Add omit nil option to marshaler

---

internal/cloudwatch/unit.go
internal/cloudwatch/unit_test.go
internal/util/unit/prefix.go
internal/util/unit/prefix_test.go

When converting OTEL units, the CloudWatch Agent is currently case sensitive. This results in warnings like
```
W! cloudwatch: metricname "<metric-name>" has non-convertible unit: "by"
```
"by" should be equivalent to "By"
Make unit conversion case-insensitive by changing the way prefixes are determined.
Updated unit tests.

Make unit conversion case-insensitive

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

They were not very useful in the current format.

Remove per-device EFA Container Insights metrics.

---

go.mod
go.sum
translator/config/schema.json
translator/tocwconfig/sampleConfig/complete_linux_config.json
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/translate/otel/receiver/jmx/translator.go

When rmi ssl is enabled the agent needs to be able to still get metrics
Enable rmi ssl 
Turn on rmi ssl in jar. Enable rmi ssl in collector. Test to see we get metrics

Take JMX Receiver Support JMX When RMI SSL Is Turned On

---

translator/translate/otel/processor/jmxfilterprocessor/translator.go
translator/translate/otel/processor/jmxfilterprocessor/translator_test.go

For hyphenated targets such as `kafka-producer` and `kafka-consumer`, the current default filter that uses these target names ends up filtering out all the metrics since the actual metrics have the pattern `kafka.producer` and `kafka.consumer` respectively.
Update default filter to replace `-` with `.`
* Manually tested for the Kafka usecase
* Update unit tests

Fix jmx default filter for hyphenated targets

---

plugins/processors/gpuattributes/internal/awsneuron_metric_modifier.go
plugins/processors/gpuattributes/internal/awsneuron_metric_modifier_test.go

We found an issue where the scrapper pushes a 0 datapoint with empty type and NoRecordedValue flag as true. This leads to a missing datapoint when the scrapper doesn't find a metric at a scrape because the logic to fill empty metric sees that the metric is present and doesn't fill anything and since the metric is stale it is dropped.
To fix this issue we are updating the metric modifier to reset stale datapoints by converting the exisiting value to a double and resetting the NoRecordedValue flag.
before vs after fix 
updating the metric modifier to reset the stale datapoints
tested in test cluster, unit test added

Ci neuron missing datapoint fix

---

plugins/inputs/logfile/logfile.go

Currently, customers using the logs plugin have a state folder tracking log files on the host that are being watched. This folder gets cleaned up periodically every hour. If the agent dies or crashes before the 1 hour, the agent could end up creating more state files causing excessive inodes to fill up on the host.
We can clean up the state folder on initialization of the logfile plugin, as well as periodically.
pass unit tests

[Logfile] Clean up state folder on init

---

plugins/processors/gpuattributes/processor.go
plugins/processors/gpuattributes/processor_test.go

The bug is that we always emit pod_gpu_ metrics at the Cluster level for GPU Devices which are not assigned to any pod. This is wrong - there should be no metrics at the pod level because no pod owns the GPU.
GPUAttribute processor will drop container/pod level nvidia GPU metrics when there is no active workload. It determines by checking `PodName` attribute on a DCGM metric.
Unit test and with a test cluster.
EMF log validations:
- Without an active workload
---
- **WITH an ACTIVE WORKLOAD**

Drop container/pod level Nvidia GPU metrics when there is no active workload.

---

.github/workflows/deploy-canary.yml

We previously had a canary test against a private S3 bucket.
We stopped updating that private S3 bucket.
We should have a canary test that exercises the same download/install mechanisms that users use.
(aka post release testing)
Related change - https://github.com/aws/amazon-cloudwatch-agent-test/pull/404
The github workflow runs on a CRON schedule - once a day at 15:00 UTC.
The workflow just launches a long lived EC2 instance which has a local CRON job that runs a Go test.
The Go test will download, install, configure, and start the agent.
The test reports a few custom metrics.
And the agent obviously reports some metrics based on the simple config it is given.
After this change is merged I will add alarms on these various metrics in our test account.
By submitting this pull request, I …

launch canary test once a day

---

plugins/processors/awsapplicationsignals/common/types.go
plugins/processors/awsapplicationsignals/internal/attributes/attributes.go
plugins/processors/awsapplicationsignals/internal/cardinalitycontrol/metrics_limiter_test.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go
plugins/processors/awsapplicationsignals/internal/prune/metric_pruner.go
plugins/processors/awsapplicationsignals/internal/prune/metric_pruner_test.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver_test.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes_test.go
plugins/processors/awsapplicationsignals/processor.go
translator/tocwconfig/sampleConfig/appsignals_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_and_k8s_config.yaml
translator/tocwconfig/sampleConfig/appsignals_fallback_and_eks_config.yaml
translator/tocwconfig/sampleConfig/appsignals_over_fallback_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_config.yaml
translator/tocwconfig/sampleConfig/base_appsignals_fallback_config.yaml
translator/translate/otel/exporter/awsemf/appsignals_config_eks.yaml
translator/translate/otel/exporter/awsemf/appsignals_config_generic.yaml
translator/translate/otel/exporter/awsemf/appsignals_config_k8s.yaml

1. Unify EMF attribute naming
2. Metric validations
3. Bugfix.
1. Rename attributes in EMF log
1. Enforce limits on metric attributes and prune invalid metrics ([that contains non-ascii characters in attributes](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html)).
1. Fix missing instance id in trace.
5. Run `make lint`

[GA] ApplicationSignals attribute renaming and validation

---

extension/agenthealth/handler/stats/provider/flag_test.go
extension/agenthealth/handler/stats/provider/interval_test.go
extension/agenthealth/handler/stats/provider/process_test.go

The stats provider unit tests are flaky especially on windows and macOS. https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8924916332/job/24512409204?pr=1156
```
--- FAIL: TestIntervalStats (0.02s)
interval_test.go:24: 
Error Trace:	D:/a/amazon-cloudwatch-agent/amazon-cloudwatch-agent/extension/agenthealth/handler/stats/provider/interval_test.go:24
Error:      	Condition never satisfied
Test:       	TestIntervalStats
FAIL
coverage: 50.0% of statements
FAIL	github.com/aws/amazon-cloudwatch-agent/extension/agenthealth/handler/stats/provider	0.055s
```
Skips the tests. Will revisit and fix them at a later time.
Ran the tests and they were …

Skip flaky stats provider unit tests.

---

go.mod
go.sum
service/defaultcomponents/components.go
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/translate/otel/pipeline/jmxpipeline/translator.go
translator/translate/otel/processor/jmxresourceattributeprocessor/translator.go
translator/translate/otel/processor/jmxresourceattributeprocessor/translator_test.go

telemetry.sdk.version and telemetry.sdk.name dimensions are not needed for jmx metrics
Remove them from resource attributes in collector

Remove telemetry.sdk.* Resource Attributes From JMX Metrics

---

packaging/dependencies/amazon-cloudwatch-agent-ctl

Some customers who do not have a toml config in the config directory are seeing a panic when running ` /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a cond-restart`
```
[ec2-user@ip-172-31-22-51 ~]$ sudo rm /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
[ec2-user@ip-172-31-22-51 ~]$ sudo touch /opt/aws/amazon-cloudwatch-agent/etc/restart
[ec2-user@ip-172-31-22-51 ~]$ sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a cond-restart
amazon-cloudwatch-agent is not configured. Applying amazon-cloudwatch-agent default configuration.
Successfully fetched the config and saved in /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default.tmp
Start configuration validation...
2024/05/08 17:43:55 Invalid mode --config. Valid …
```

[Bugfix] pass mode to resolve amazon-cloudwatch-agent-ctl restart panic

---

plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go

1. OTEL resource detection processor is unable to detect ECS cluster information.
```
2024-05-01T18:23:58Z I! {
"caller": "internal/resourcedetection.go:139",
"msg": "detected resource information",
"kind": "processor",
"name": "resourcedetection",
"pipeline": "traces/application_signals",
"resource": {}
}
```
1. This PR reads ECS cluster name from CWA if it's not populated from SDK side.
3. This PR completes a TODO after semconv version has bumped to 1.22.
4. Run `make lint`

[GA] Autofill ECS cluster info if it's missing

---

extension/agenthealth/handler/useragent/useragent_test.go
go.mod
go.sum

Update awsemfexporter and awsxrayexporter with changes in the contrib repo from commit: https://github.com/amazon-contributing/opentelemetry-collector-contrib/commit/e0e66ca9e79c7026664325c185257856e9b7c504
Modified go.mod to point to the commit hash `e0e66ca9e79c7026664325c185257856e9b7c504`
```
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter => github.com/amazon-contributing/opentelemetry-collector-contrib/exporter/awsemfexporter e0e66ca9e79c7026664325c185257856e9b7c504
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter => github.com/amazon-contributing/opentelemetry-collector-contrib/exporter/awsxrayexporter e0e66ca9e79c7026664325c185257856e9b7c504
```
then ran `go mod tidy`
By submitting this pull request, I confirm …

Update awsemfexporter and awsxrayexporter from contrib

---

.github/workflows/application-signals-java-e2e-eks-test.yml

The image is changing but the old image value is incorrectly showing the same as the new image. This is likely an indication of some weird behaviour when overriding the CW Agent image that causes the new image to persist between separate installations. Will take a follow up item to investigate, but making this change to unblock the release.

[E2E] Comment CW Agent change check

---

plugins/processors/gpuattributes/processor.go
plugins/processors/gpuattributes/processor_test.go
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go
translator/translate/otel/processor/metricstransformprocessor/translator.go

This PR includes 1 bug fix and and enhancement to add NVIDIA GPU count metrics including `_limit`, `_request` and `_total` at `pod`, `node` and `cluster` levels
- GPU count metrics
- Add NVIDIA GPU count metric replication logic to `metricstrasformprocessor` translator
- Update AWS EMF exporter metric declarations to include GPU count metrics with dimensions
- Bug fix 
- Fix the bug where the agent emits pod GPU metrics when there is no active workload
Related PR in contrib: https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/214
Tested with a cluster with 2 GPU (`g4dn.12xlarge`) instances with a workload which requires 2 …

nvidia gpu count metrics and bugfix 

---

RELEASE_NOTES

To keep in line with other releases of this version.
Removes ethtool change from release notes.
N/A

Remove ethtool change from Release Notes for 1.300041.0

---

.github/workflows/PR-build.yml
.github/workflows/test-build-packages.yml

GitHub has deprecated macOS 11 and is removing the runner image on 6/28/2024 (https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/). They have started a brownout of jobs using that image, so they will no longer run.
Bumps the macOS version to 12, which is the oldest available version (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
Ran the PR build workflow.

Update macos version in GitHub actions

---

.github/workflows/PR-build.yml
.github/workflows/test-build-packages.yml
translator/translate/otel/receiver/otlp/translator.go
translator/translate/otel/receiver/otlp/translator_test.go

Need to receiver jmx metrics over otlp
Add default jmx metrics over otlp to otlp receiver
Unit Tests 

Add Default JMX HTTP Endpoint To OTLP Receiver

---

plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go

Application Signals want to support metric-log correlations for EC2 and other customized platforms. In those platforms, we want users to specify the application log groups associated with a service by using the following command: 
```
export OTEL_RESOURCE_ATTRIBUTES="aws.log.group.names=log-group1&log-group2,service.name=my-service"
```
We want to save these information about log groups into the emf logs so that later the backend can find out the relevant log groups given a metric. The current change is just to copy the relevant field from resource attributes to the attributes so that aws emf exporter will write the info into emf logs. We are not attempting to do any parsing in cloudwatch agent to get the list of log groups because backend decides to handle that due to some limitation …

copy aws.log.group.names from resource attributes to attributes

---

plugins/processors/awsapplicationsignals/internal/resolver/kubernetes.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes_test.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes_utils.go

The memory utilization of CloudWatch Agent is high after enabling Application Signals. In an EKS cluster of ~7k Pods, the memory usage went up to 90% for leader instance, 70% for follower instances.
From heap profiling, it was confirmed that the issue was caused by `applicationsignalsprocessor` which list/watch Pods and Services cluster-wise for IP/Service translation.
This PR does the following changes to `applicationsignalsprocessor`:
1. Reduce the memory usage of list/watching.
It is achieved by customizing transformer in informers to empty fields that might contain big objects. By applying the changes, the memory usage went down from 90% to 50% for leader, 70% to 40% for followers.
1. Remove logics of setting RemoteService to UnknownRemoteService due to IP translation failure.
Forcing …

Optimize the memory utilization of Kubernetes resolver in Application Signals

---

plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go

Updating tests to resolve lint errors
Updating tests to resolve lint errors from [PR-1230](https://github.com/aws/amazon-cloudwatch-agent/pull/1230)
Ran
- make build
- make check_secrets amazon-cloudwatch-agent-linux && make prepackage package-rpm

Updating tests to resolve lint errors

---

translator/tocwconfig/sampleConfig/jmx_config_linux.yaml
translator/translate/otel/receiver/jmx/translator.go
translator/translate/otel/receiver/jmx/translator_test.go

The support for a JMX plugin was recently introduced, however, the default collection interval was set to 10 secs as opposed to the default collection interval of 60 secs used by all our other plugins.
Updating the default collection interval for JMX to be inline with the rest of the plugins by setting it to 60 secs.
Updated unit tests

Update JMX default collection interval to be 60 secs

---

plugins/outputs/cloudwatchlogs/pusher_test.go

The test `TestLongMessageGetsTruncated` is flaky and failing in a lot of PRs, as an example https://github.com/aws/amazon-cloudwatch-agent/actions/runs/9653140668/job/26624834119.
The problem is that it is waiting 10ms after putting an event to a channel. This makes the test flaky because it might take more than 10ms for the event to be [added to the events array](https://github.com/aws/amazon-cloudwatch-agent/blob/70db9a331f0445a43ac4e2a5450fc06917b3ba1a/plugins/outputs/cloudwatchlogs/pusher.go#L176) because it runs in another goroutine.
**Why are other tests not affected by this?**
Other tests are not asserting the length of the events received, just that they don't exceed a certain threshold.
Waiting in a loop after adding the event to the channel which will wait until event gets added …

Fix flakiness for TestLongMessageGetsTruncated test

---

internal/cloudwatch/unit.go
internal/cloudwatch/unit_test.go

JMX Tomcat and Kafka metrics are sent to the agent with non-standard and non-convertible units. This currently results in consistent warning logs.
Adds an allowlist of known non-convertible units and includes the Tomcat/Kafka ones. Reduced the warning to a debug log.

Reduce logging for known non-convertible JMX metric units.

---

Makefile
plugins/inputs/windows_event_log/service_monitor.go
plugins/inputs/windows_event_log/service_monitor_test.go
plugins/inputs/windows_event_log/windows_event_log.go
plugins/inputs/windows_event_log/wineventlog/wineventlog.go

Currently, if the Windows `EventLog` service crashes and gets restarted, the CloudWatch agent no longer picks up events. This is because the event handle used by the subscription is no longer valid. The CloudWatch agent needs a way to detect that the service has restarted and then re-open the subscription.
Adds a service monitor that uses the [golang.org/x/sys/windows/svc/mgr](https://pkg.go.dev/golang.org/x/sys@v0.22.0/windows/svc/mgr) package to periodically (every 10 seconds) detect if the `eventlog` service's PID has changed. If it has changed, it notifies each of the `wineventlog` subscriptions to re-subscribe. This prevents the plugin from trying to re-subscribe if the service is down.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add windows event log service restart detection and resubscribe

---

translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/jmx_config_linux.yaml
translator/translate/otel/common/common.go
translator/translate/otel/common/common_test.go
translator/translate/otel/common/options.go
translator/translate/otel/common/options_test.go
translator/translate/otel/pipeline/host/translator.go
translator/translate/otel/pipeline/jmx/translator.go
translator/translate/otel/pipeline/jmx/translator_test.go
translator/translate/otel/processor/cumulativetodeltaprocessor/translator.go
translator/translate/otel/processor/cumulativetodeltaprocessor/translator_test.go

There are quite a few JMX metrics (e.g. `kafka.message.count`, `kafka.network.io`, etc.) that are reported as cumulative sums/histograms. In CloudWatch, these metrics are more useful as deltas, which will allow for easier alarming and anomaly detection. We've made the decision to convert all applicable JMX metrics to deltas.
Adds the cumulativetodelta processor to all JMX pipelines.

Add cumulative to delta conversion for JMX metrics.

---

.github/workflows/PR-build.yml
README.md

Currently `codecov` tries to upload on every PR build and fails due to being outdated.
Removed `codecov` for now to un-block PRs. We can add `codecov-4` later on. 
Ran PR-build

[chore] Remove Codecov Upload on every PR

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/build-test-artifacts.yml
.github/workflows/integration-test.yml

The `integration-test.yml` workflow has exceeded the reusable workflow limit of 20 (https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#limitations) due to changes in the nested reusable workflows in the `application-signals-e2e-test.yml` workflow and no longer runs (https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10221982238).
>Invalid workflow file: .github/workflows/integration-test.yml#L1 too many workflows are referenced, total: 25, limit: 20
There isn't currently a way to increase the limit.
One way around this limitation is to move the application signals E2E workflow out of the integration test workflow. The build jobs that were previously in the integration test workflow have been separated out into their own workflow since …

Separate build jobs for artifacts and trigger tests with workflow_run

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/build-test-artifacts.yml
.github/workflows/integration-test.yml

The [`workflow_run` event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run) doesn't provide the necessary context to run on non-default branches. This makes it difficult to test changes prior to merging the code and doesn't prevents concurrent runs.
Switches to the `workflow_dispatch` event for the dependent tests and uses the GitHub CLI [`workflow run` command](https://cli.github.com/manual/gh_workflow_run) to start them. Each of the tests will now use the GitHub CLI [`run view` command](https://cli.github.com/manual/gh_run_view) to check if the build-test-artifacts run has succeeded.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

[chore] Replace workflow_run with workflow_dispatch

---

translator/tocwconfig/sampleConfig/advanced_config_darwin.yaml
translator/tocwconfig/sampleConfig/advanced_config_linux.yaml
translator/tocwconfig/sampleConfig/complete_darwin_config.yaml
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/delta_config_linux.yaml
translator/tocwconfig/sampleConfig/delta_net_config_linux.yaml
translator/tocwconfig/sampleConfig/jmx_config_linux.yaml
translator/tocwconfig/sampleConfig/standard_config_linux.yaml
translator/tocwconfig/sampleConfig/standard_config_linux_with_common_config.yaml
translator/translate/otel/processor/cumulativetodeltaprocessor/translator.go
translator/translate/otel/processor/cumulativetodeltaprocessor/translator_test.go

The default configuration for the cumulativetodelta processor sets the initial value behavior to:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/cumulativetodeltaprocessor/README.md
> auto (default): Send if and only if the startime is set AND the starttime happens after the component started AND the starttime is different from the timestamp. Suitable for gateway deployments, this heuristic is like drop, but keeps values for newly started counters (which could not have had previous observed values).
This results in spikes during restarts of the agent. This does not match the behavior of the [prometheus plugin](https://github.com/aws/amazon-cloudwatch-agent/blob/main/plugins/inputs/prometheus/delta_calculator.go#L41) or the [telegraf delta …

Change cumulative to delta conversion to drop initial value

---

internal/cloudwatch/unit.go

The CloudWatch agent has a warning when units cannot be converted. We've previously added suppression for known JMX units (https://github.com/aws/amazon-cloudwatch-agent/pull/1244), but missed the "sessions" unit for `tomcat.sessions`.
- Tomcat (https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/src/main/resources/target-systems/tomcat.groovy):
- `tomcat.sessions`: `session`
- `tomcat.errors`: `errors`
- `tomcat.request_count`: `requests`
- `tomcat.threads`: `threads`
Adds "sessions" to the list.
N/A

Suppress sessions unit warning

---

internal/cloudwatch/unit.go
internal/cloudwatch/unit_test.go

Currently, nanosecond metrics are converted to microseconds before being published to CloudWatch because CloudWatch does not support nanosecond unit. The closest unit is microseconds.
Unfortunately, this implicit conversion can be confusing for metrics with `ns` in the name like `kafka.producer.io-wait-time-ns-avg` because the value/unit in CloudWatch will actually be Microseconds which is inconsistent with the metric name. This also results in a loss of precision.
This change removes the conversion of nanosecond metrics. Instead, they are published unmodified with a unit of "None".
Kicked off integration tests for that branch. Checked the …

Stop converting nanosecond metrics

---

extension/entitystore/serviceprovider.go
extension/entitystore/serviceprovider_test.go
plugins/processors/ec2tagger/constants.go

There was an issue with agent users retrying EC2 DescribeTag API calls on a high frequency and causing throttle errors. The agent also retry on non-throttle errors which is not a recommended behavior
For DescribeTags API calls, follow the behavior below: 
- Successful Calls - Retry every hour
- Throttling Error - Retry 3 times on an exponential backoff of 0, 60, 180 seconds
- Other errors - Do not retry
Unit tests

Fix DescribeTags retry on high-frequency and delay refresh interval

---

extension/entitystore/extension.go

Resolving issue where the region is not specified when creating the STS and EC2 metadata clients.
Adds region to the AWS config when instantiating the clients.
Manual in us-east-1

Specifying region in EC2 and STS clients in entity store

---

plugins/processors/awsapplicationsignals/common/types.go
plugins/processors/awsapplicationsignals/internal/attributes/attributes.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go

Add a new log attribute in EMF logs which is to store AWS Resource CloudFormation Primary Identifier value for AWS resources recognized by AppSignals instrumentation SDKs. https://github.com/aws-observability/aws-otel-python-instrumentation/pull/264
Rename SDK attribute `aws.remote.resource.cfn.primary.identifier` to EMF logs attribute `RemoteResourceCfnPrimaryIdentifier`
unit test

Add new aws resource cloudformation primary identifier attribute in EMF

---

plugins/processors/awsapplicationsignals/common/types.go
plugins/processors/awsapplicationsignals/config/config.go
plugins/processors/awsapplicationsignals/config/config_test.go
plugins/processors/awsapplicationsignals/config/resolvers.go
plugins/processors/awsapplicationsignals/internal/attributes/attributes.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver_test.go
plugins/processors/awsapplicationsignals/internal/resolver/ecs.go
plugins/processors/awsapplicationsignals/internal/resolver/ecs_test.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes.go
translator/tocwconfig/sampleConfig/appsignals_and_ecs_config.conf
translator/tocwconfig/sampleConfig/appsignals_and_ecs_config.json
translator/tocwconfig/sampleConfig/appsignals_and_ecs_config.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/otel/processor/awsapplicationsignals/translator.go
translator/translate/otel/processor/resourcedetection/configs/ecs_config.yaml
translator/translate/otel/processor/resourcedetection/translator.go
translator/translate/otel/processor/resourcedetection/translator_test.go

Currently, traffic from ECS is recognized as from generic platform. This PR adds ECS as a supported platform, and includes more ECS specific attributes in the Application Signals EMF log.
In addition, it removes resource detection for Task related attributes, and relies on client side to provide the accurate values. This is mainly to support deploying CloudWatch agent as Daemon or a standalone service on an ECS Cluster.
Integration tests
https://github.com/aws-observability/aws-application-signals-test-framework/actions/workflows/python-ecs-canary.yml
https://github.com/aws-observability/aws-application-signals-test-framework/actio …

Add full support for ECS in Application Signals

---

go.mod
go.sum

Bumping telegraf version so that we can fix mac os build constraint for the agent:
https://github.com/aws/telegraf/pull/162

Bumping telegraf version to fix build constraint

---

cmd/config-translator/translator_test.go
translator/config/sampleSchema/invalidOTLPMetrics.json
translator/config/sampleSchema/validOTLPMetrics.json
translator/config/schema.json
translator/tocwconfig/sampleConfig/otlp_metrics_config.conf
translator/tocwconfig/sampleConfig/otlp_metrics_config.json
translator/tocwconfig/sampleConfig/otlp_metrics_config.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/metrics/config/registered_metrics.go
translator/translate/otel/pipeline/host/translator.go
translator/translate/otel/pipeline/host/translators.go
translator/translate/otel/pipeline/host/translators_test.go
translator/translate/otel/processor/cumulativetodeltaprocessor/translator.go
translator/translate/otel/processor/cumulativetodeltaprocessor/translator_test.go
translator/translate/otel/receiver/adapter/translators.go
translator/translate/otel/receiver/otlp/testdata/metrics/config.json
translator/translate/otel/receiver/otlp/testdata/metrics/config.yaml
translator/translate/otel/receiver/otlp/translator.go
translator/translate/otel/receiver/otlp/translator_test.go

Introduce support for the OTLP receiver for Metrics. This change adds the OTLP receiver to the existing `hostDeltaMetrics` pipeline that also uses a Cumulative to Delta processor and an AWS CloudWatch exporter.
* Introduces new `otlp` section under `metrics -> metrics_collected` that can either be a json blob or an array of json blobs for multiple listeners.
* OTLP Metrics are setup to flow through our current `hostDeltaMetrics` pipeline using:
* `otlpreceiver` - to receive the metrics on both HTTP and gRPC endpoints
* `cummulativetodelta` processor - to convert cumulatives to deltas by default when publishing to CloudWatch
* AWS `cloudwatch` exporter - to publish via PutMetricData API calls to CloudWatch
* Supports `append_dimensions` as expected.
* We treat this as a passthrough plugin …

Add support for OTLP Receiver for Metrics

---

tool/clean/clean_ami/clean_ami.go

We run a daily GitHub workflow ([AWS Daily Resources Cleaner](https://github.com/aws/amazon-cloudwatch-agent/actions/workflows/clean-aws-resources.yml)) to delete AMIs older than 60 days. This works for non-macOS AMIs because we use ImageBuilder to handle building them. However, macOS AMIs are not currently supported by ImageBuilder. As a result, our macOS AMIs are deleted by the workflow when they cross the 60 day threshold and are not automatically replaced, leaving a gap in our integration testing. 
I modified the logic of the script to specifically handle macOS AMIs. If there is only one image, it won't be deleted regardless of age. If there are multiple images and they are all past the expiration date, the script will keep the youngest and delete the rest. Otherwise, it'll keep the …

Update AMI cleaner script to properly handle macOS images

---

.github/workflows/application-signals-e2e-test.yml

[aws-application-signals-test-framework](https://github.com/zzhlogin/aws-application-signals-test-framework/tree/main) recently added ECS E2E support: [PR](https://github.com/aws-observability/aws-application-signals-test-framework/pull/222), we want to add ECS E2E entry to build-test-artifacts workflow.
Add ECS E2E entry to build-test-artifacts workflow.
Local test.

Add ECS E2E entry to build-test.

---

internal/util/config/config.go
internal/util/config/config_test.go

On ECS, the `/etc/cwaconfig` directory may not be available. This currently causes a panic because the `DirEntry` is nil.
Adds a check to make sure this doesn't change the current behavior.
Updated unit tests.

Fix config detection when path is invalid.

---

cmd/config-translator/translator_test.go
translator/config/sampleSchema/invalidJMX.json
translator/config/schema.json
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/jmx_config_linux.yaml
translator/tocwconfig/sampleConfig/jmx_eks_config_linux.conf
translator/tocwconfig/sampleConfig/jmx_eks_config_linux.json
translator/tocwconfig/sampleConfig/jmx_eks_config_linux.yaml
translator/tocwconfig/tocwconfig_unix_test.go
translator/translate/otel/common/options.go
translator/translate/otel/common/options_test.go
translator/translate/otel/exporter/debug/translator.go
translator/translate/otel/exporter/debug/translator_test.go
translator/translate/otel/pipeline/applicationsignals/translator.go
translator/translate/otel/pipeline/host/translators.go
translator/translate/otel/pipeline/jmx/translator.go
translator/translate/otel/pipeline/jmx/translator_test.go
translator/translate/otel/pipeline/jmx/translators.go
translator/translate/otel/pipeline/jmx/translators_test.go
translator/translate/otel/processor/filterprocessor/translator.go
translator/translate/otel/processor/filterprocessor/translator_test.go
translator/translate/otel/processor/resourceprocessor/translator.go
translator/translate/otel/processor/resourceprocessor/translator_test.go
translator/translate/otel/receiver/otlp/translator.go
translator/translate/otel/receiver/otlp/translator_test.go

JMX on EKS relies on a different method to collect metrics, so the pipeline needs to be a bit different.
In a container environment,
- Adds the OTLP receiver to the JMX pipeline.
- Adds a `resource` processor to support `append_dimensions` if configured.
- Separates the `cloudwatch` and `amp` exporters into separate pipelines.
- Removes the `cumulativetodelta` processor from the AMP pipeline.
- Removes `endpoint` from the JSON schema requirements for `jmx`. This will be enforced by the translator instead on EC2.
Added unit tests. Built and tested the image. …

Add JMX pipeline for container environments

---

cfg/envconfig/envconfig.go
cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent_test.go
cmd/amazon-cloudwatch-agent/testdata/base+env.yaml
cmd/amazon-cloudwatch-agent/testdata/base.yaml
internal/merge/confmap/confmap.go
internal/merge/confmap/confmap_test.go

On ECS, the agent can be configured by setting the `CW_CONFIG_CONTENT` environment variable to a valid JSON string. The `/etc/cwagentconfig` directory that is available on EKS is not used.
Adds a `CW_OTEL_CONFIG_CONTENT` environment variable that can be used in a container environment if no other supplemental YAML is provided. Must be a valid YAML formatted string.
Follows the `CW_CONFIG_CONTENT` usage conditions
https://github.com/aws/amazon-cloudwatch-agent/blob/5cdba47e87d55f65d31ba8162c8c91cc151ec4a5/translator/cmdutil/translatorutil.go#L196-L198
1. Run `make fmt` and …

Support supplemental configuration on ECS

---

extension/agenthealth/handler/useragent/useragent.go
extension/agenthealth/handler/useragent/useragent_test.go

If the configuration has a JMX receiver or EMF exporter in the pipelines, but not in the components, the useragent check will panic when trying to de-reference a nil value.
Adds a type assertion check before trying to access fields.
Added unit test.

Add nil check to user agent.

---

extension/entitystore/ec2Info.go
extension/entitystore/ec2Info_test.go
extension/entitystore/extension.go
extension/entitystore/extension_test.go
extension/entitystore/factory.go
extension/entitystore/serviceprovider.go
extension/entitystore/serviceprovider_test.go

With LogsAgent plugin, Agent has a race condition that can cause some customers to lose logs as the agent panics.
The panic is due to LogsAgent calling the CreateLogFileEntity method in entity store extension before the extension is initialized/started. Added a null check for serviceProvider to return nil when it is not initialized.
Also added null checks in other methods of entitystore extension to avoid panics.
Unit Tests
1. Run `make fmt` …

Add null checks to service provider in entitystore extension

---

.github/workflows/PR-build.yml
.golangci.yml
Makefile

Currently, the CloudWatch Agent only performs basic linting checks. This pull request introduces an enhanced lint checker to ensure that all future code merges adhere to high standards of formatting and quality.  
Since the current codebase may contain existing linting conflicts, a parameter `new-from-dev` has been introduced, set to the commit `3221f769358168c0602e58918c1fb7b6083e33af`. This parameter ensures that lint checks are only applied to commits made after this point, avoiding unnecessary conflicts with legacy code.  
---
- Added a lint checker to the CloudWatch Agent to enforce consistent code formatting and quality for future development.  
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your …

Adding Lint Checker

---

src/common/Constant.ts
src/containers/PerformanceReport/data.d.ts
src/containers/PerformanceReport/index.tsx
src/containers/PerformanceTrend/data.d.ts
src/containers/PerformanceTrend/index.tsx

The Performance Page displays missing data values as `-1`, which causes confusion.  Also commit details are currently missing from the tooltip view
1. Removes commits from graph if the displayed metric is missing a value.
2. Re-enables usage of Github api call to retrieve commit data
3. Run `make lint`
-----
-----
-----

Modify graphs to ignore missing data and to retrieve commit data

---

.github/workflows/PR-build.yml
Makefile

There have been cases of race conditions in the past that were not detected prior to merging the PRs. Go has race detectors built into `go test`.
Adds a job to run the race detector with the `go tests`. There are several packages with data races either in the code or in the tests:
- `extension/entitystore`
- `extension/server`
- `internal/publisher`
- `internal/retryer`
- `internal/tls`
- `plugins/inputs/logfile`
- `plugins/inputs/logfile/tail`
- `plugins/outputs/cloudwatch`
- `plugins/outputs/cloudwatchlogs`
- `plugins/processors/awsapplicationsignals`
- `plugins/processors/ec2tagger`
Omits those packages.
Ran the tests with the race detector …

Add data race test to PR build

---

tool/clean/clean_ami/clean_ami.go

Some of our integration tests fail due to no AMI existing for the particular architecture. This is because our ami cleanup script deletes any AMI older than 60 days.
Refactor the clean ami script to use selected filters from our image builder pipeline to determine the list of images used for testing for each architecture, then check if at least 1 exists even if its older than 60 days to ensure tests pass.
Workflow: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12145498729/job/33867278441

[CleanAMI] Ensure at least 1 AMI exists for each test image architecture

---

.github/workflows/PR-build.yml
.github/workflows/test-build-packages.yml

GitHub has deprecated the macos-12 runners (https://github.com/actions/runner-images/issues/10721).
Swap them out for macos-13 runners (https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md). 
Ran PR tests. Validating package build is unimpacted by change: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12147539114

Bumping macos runner due to deprecation of macos-12

---

.github/workflows/integration-test.yml

- `kubectl rollout` fails with timeout when checking the status of nvidia device plugin
```
Waiting for daemon set "nvidia-device-plugin-daemonset" rollout to finish: 0 of 1 updated pods are available...
error: timed out waiting for the condition
```
- destroy fails with unknown `beta` var
```
╷
│ Error: Invalid value for input variable
│ 
│   on variables.tf line 39:
│   39: variable "beta" {
│ 
│ Unsuitable value for var.beta set using -var="beta=...": a bool is
│ required.
```
- Replace `kubectl rollout` with simple sleep
- Drop `beta` vars in terraform commands
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12165006108
_Before …

Fix GPU E2E test failures

---

extension/entitystore/extension_test.go
extension/entitystore/serviceprovider.go
extension/entitystore/serviceprovider_test.go
internal/ec2metadataprovider/ec2metadataprovider.go
plugins/processors/ec2tagger/ec2tagger_test.go

The `application`, `app` and `service` service name provider ec2 tags are currently case sensitive, there are also bugs in exactness in how these are being compared due to excessive use of `strings.Contains`
Update `InstanceTags` to return a `[]string` with the tag keys instead of the raw newline delimited list.  This is a more friendly API to reason about.  We can then convert it to a map with lowercase keys that we use for comparison.
I also fixed the asg lookup to also be an exact match instead.  These matches are relatively efficient as I am converting the arrays to maps for O(1) lookups instead of having to repeatedly loop through the whole strings using Contains or slices.Contains
Related to: https://github.com/aws/amazon-cloudwatch-agent/pull/1474
By submitting this pull request, I …

Case insensitive service provider

---

plugins/processors/awsentity/factory.go
plugins/processors/awsentity/factory_test.go
plugins/processors/awsentity/processor.go
translator/tocwconfig/sampleConfig/base_container_insights_config.yaml
translator/tocwconfig/sampleConfig/complete_darwin_config.yaml
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/complete_windows_config.yaml
translator/tocwconfig/sampleConfig/config_with_env.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_kueue_config.yaml
translator/tocwconfig/sampleConfig/kueue_container_insights_config.yaml
translator/tocwconfig/sampleConfig/log_ecs_metric_only.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/pipeline/emf_logs/translator.go
translator/translate/otel/pipeline/emf_logs/translator_test.go

We want the ability to send entities for customers forwarding EMF logs using the EMF forwarding plugin: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_CloudWatch_Agent.html
To do this, we should add the awsentity processor which contains logic providing entity attributes to cloudwatch exporters.
- Add `awsentity` processor to EMF log pipeline.
Note that this change does not change the telemetry yet, it just sets up the pipeline for future modifications.
Unit test.

[processor/awsentity] Add awsentity processor into EMF pipeline

---

extension/entitystore/serviceprovider.go

Fixes https://github.com/aws/amazon-cloudwatch-agent/issues/1479. Entity store's operations to read and write the logFile and logGroups maps can occur from diff go routines corresponding to files monitored by the agent and can lead to a panic if accessed concurrently.
Use a mutex lock to prevent concurrent access to the log maps.
Wrote up a script to generate a high load of 1000 logs being constantly written to and monitored by the agent. Prior to fix, I see the agent crash every few mins:
```
$ journalctl -u amazon-cloudwatch-agent --since "2 minutes ago" -f | grep "concurrent"
Jan 03 19:19:17 ip-172-31-27-109.ec2.internal …
```

Fix concurrent read write error for entity store

---

package.json
src/common/Axios.ts
src/common/Constant.ts
src/containers/PerformanceReport/data.d.ts
src/containers/PerformanceReport/index.tsx
src/containers/PerformanceReport/service.ts
src/containers/PerformanceTrend/data.d.ts
src/containers/PerformanceTrend/index.tsx
src/containers/PerformanceTrend/service.ts
src/core/table.tsx

Fixes issues with PerformanceReport Page
1. replaces dummy commit data
2. hides missing performance data
3. Fixes bug where duplicate rows display
1. Fixes issue where data is not correctly loading into the Performance report table
Date shows as Dec 31, 1969, this is due to commit data missing in DynamoDB and will be resolved by another PR in the CWAgent Integ tests
1. Validated in local environment using data from lambda and github api
4. Run `make lint`

Fix issues with PerformanceReport Page (commit data, hiding missing data)

---

go.mod
go.sum

There is an issue in scraping disk usage on macOS systems. The problem stems from gopsutil's reliance on unix.Statfs, which is not accurately retrieving disk usage data on macOS. While unix.Statfs is generally reliable on many Unix systems, it seems to be incompatible with macOS's specific filesystem (APFS) implementation or reporting mechanisms. This leads to inaccurate disk usage metrics (where all reported mount points have same used space values), impacting macOS customers' observability to their resources.
PR in aws/telegraf https://github.com/aws/telegraf/pull/167
Test results https://github.com/aws/telegraf/pull/167
_Before commit the code, …

update telegraf module for disk usage metrics fix on macOS

---

.github/workflows/deploy-canary.yml
.github/workflows/ec2-integration-test.yml
.github/workflows/eks-e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/soak-test.yml
.github/workflows/start-localstack.yml

Integration tests are failing because of the following error:
```
/home/runner/work/_temp/850921c8-782b-4ebe-88ba-9a5873e052ae.sh: line 1: terraform: command not found
```
It appears terraform isn't on the github runners by default, so we're adding a step to install terraform to each of the workflows using: https://github.com/hashicorp/setup-terraform. Thanks for paramadon for finding and solving this issue.
Terraform is working again in the integration test workflows: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12832239476
2. Run `make …

Add setup terraform step to integration tests

---

.github/workflows/deploy-canary.yml
.github/workflows/integration-test.yml

EKSIntegrationTest fails because terraform is not installed: 
```bash
/home/runner/work/_temp/7f0421f7-4fb8-4bb9-bf66-99ddfc508068.sh: line 1: terraform: command not found
```
See job: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12834512020/job/35792035900
Continuation of https://github.com/aws/amazon-cloudwatch-agent/pull/1507. Missed installing terraform for the EKS integration test workflow.
* Install terraform for EKS integration test workflow
* Move terraform installation step for deploy canary workflow in case the workflow needs to terminate the old canary first
_Before commit the code, …

Add setup terraform step to EKS integration test

---

.github/workflows/e2e-test.yml

We recently implemented comprehensive E2E tests that check complex monitoring configurations with the CloudWatch Agent across different branches of the agent, operator, and helm charts repositories on full customer environments (e.g. an EKS cluster) to validate proper resource creation and metric emission for robust regression detection. Currently, these E2E tests are only configured to be triggered manually, which makes sense for testing feature branches prior to a release. However, we don't have a scheduled run of our E2E tests across our main branches, which is important for detecting regressions for changes merged into main that weren't tested as part of feature branches.
* Added `schedule` workflow trigger with a `cron` set to run every Monday at 12 PM EST.
* Added `|| …

Run E2E tests weekly

---

plugins/outputs/cloudwatchlogs/internal/pusher/batch.go
plugins/outputs/cloudwatchlogs/internal/pusher/batch_test.go

https://github.com/aws/amazon-cloudwatch-agent/pull/1499 changed the `perEventsHeaderBytes` from 200 to 26 to match the [PutLogEvents API specifications](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html)
> The maximum batch size is 1,048,576 bytes. This size is calculated as the sum of all event messages in UTF-8, plus 26 bytes for each log event.
The size was originally mistakenly raised in https://github.com/aws/amazon-cloudwatch-agent/pull/913.
This is causing the batches to be larger and have more log events, which is increasing the memory usage in the stress tests.
- Reverts the per event header bytes to 200
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Revert per events header bytes to 200

---

.github/workflows/ec2-integration-test.yml
.github/workflows/eks-e2e-test.yml
.github/workflows/integration-test.yml

Caching was intially put in place to reduce the number of tests that needed to be re-run on partial failures in an effort to speed up testing. It currently is put in place to skip passing tests on re-runs. But since GitHub workflows supports [re-running failed jobs](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow), which already covers the purpose of the caching. Caching conflicts have also resulted in false positives for passing tests like the stress tests.
This pr removes caching to avoid false negatives.
Integration test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12997888061

Removing Caching from integ test

---

.github/workflows/ec2-integration-test.yml
cfg/aws/credentials.go
cfg/aws/credentials_test.go
cfg/envconfig/envconfig.go

To support confused deputy prevention, the CloudWatch Agent needs to be able to pass confused deputy context keys in the headers of STS AssumeRole calls so that dependent service teams can allow their customers to use confused deputy context keys in their role policies.
For background on the confused deputy problem, see: https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html
Enable the CloudWatch Agent to resource confused deputy context keys from environment variables and include the key values in the STS AssumeRole request headers.
I noticed while testing my new integration test that the destroy step was always failing because terraform wasn't initialized. Example: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13013756921/job/36303755191. This wound up …

Add Confused Deputy Prevention

---

translator/translate/otel/common/appsignals.go
translator/translate/otel/common/common.go
translator/translate/otel/exporter/awsemf/prometheus.go
translator/translate/otel/processor/awsapplicationsignals/translator.go
translator/translate/otel/processor/awsentity/translator.go
translator/translate/otel/processor/awsentity/translator_test.go
translator/translate/otel/processor/resourceprocessor/translator.go
translator/translate/otel/receiver/awscontainerinsight/translator.go
translator/translate/otel/receiver/awscontainerinsightskueue/translator.go

When running on a Kubernetes cluster, the only way the CloudWatch Agent can detect the cluster name is:
1) If it's provided in the configuration:
```
"kubernetes": {
"cluster_name": "<cluster-name>",
"enhanced_container_insights": true
},
"application_signals": {
"hosted_in": "<cluster-name>"
}
```
2) By making a `ec2:DescribeTags` call.
Ideally, the agent should minimize external API calls, so we should implement a global way to retrieve the cluster name in case it isn't provided in the configuration. We can fetch the `K8S_CLUSTER_NAME` environmental variable, which is populated by the Amazon CloudWatch Observability EKS add-on / Helm chart.
> [!IMPORTANT]
> **Co-PR:** https://github.com/aws-observability/helm-charts/pull/167
- Create `GetHostedIn` function, which looks for cluster name …

Improve cluster detection for entity and app signals processors

---

extension/server/extension.go

When agent is installed using the Container Insights YAML as part of https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-metrics.html , this error log clutters up the agent logs and gives customers an impression that something is wrong with the agent 
```
2025-01-23T04:50:37Z E! {"caller":"tls/certWatcher.go:89","msg":"failed to read certificate","kind":"extension","name":"server","error":"could not read certificate \"/etc/amazon-cloudwatch-observability-agent-client-cert/tls-ca.crt\": open /etc/amazon-cloudwatch-observability-agent-client-cert/tls-ca.crt: no such file or directory","stacktrace":"github.com/aws/amazon-cloudwatch-agent/internal/tls.(*CertWatcher).ReadTlsConfig\n\tgithub.com/aws/amazon-cloudwatch-agent/internal/tls/certWatcher.go:89\ngithu …
```

Changing log level of cert watcher from error to debug

---

.github/workflows/stop-localstack.yml

The `StopLocalStack` workflow is failing with: `/home/runner/work/_temp/a9bdcdd2-65bc-4117-81be-cbad70401c8d.sh: line 1: terraform: command not found`.
To fix this, we must install terraform in our runner.
- Add terraform install to StopLocalStack.
[View Workflow Run #13195436716](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13195436716)

Add terraform install to StopLocalStack

---

.github/workflows/ec2-integration-test.yml

Whenever we cancel our EC2 integration tests that don't use the `terraform/ec2/linux` directory, we get the following error:
```
This module is not yet installed. Run "terraform init" to install all
modules required by this configuration.
```
This is caused by not going into the correct directory when we run `terraform destroy`.
- Set to correct directory for destroy.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13232946491/job/36933626388

Fix terraform destroy for ec2 integration tests

---

translator/util/eksdetector/eksdetector.go
translator/util/eksdetector/eksdetector_test.go
translator/util/eksdetector/eksdetectortestutil.go

To detect whether the CloudWatch Agent is running on EKS, we look for a ConfigMap named `aws-auth`, which is only supported for EKS and maps IAM users/roles to K8s RBAC for API access. However, `aws-auth` is now deprecated and isn't created on new EKS clusters, which marks the CloudWatch Agent as running on native K8s, not EKS, **which is not accurate.**
A suggestion from an issue is to inspect the `serviceaccount` token and look for the issuer field (`iss`). It contains the unique OIDC url for the EKS cluster.
> Relevant issue: https://github.com/aws/amazon-cloudwatch-agent/issues/1249.
- Add logic to query API server for issuer field as a fall-back.
- Update unit tests to reflect changes.
- `resetTestState()` forces re-evaluation of the `IsEKS()` singleton for each test.
By submitting …

Fix EKS cluster detection

---

plugins/outputs/cloudwatchlogs/internal/pusher/queue_test.go
plugins/outputs/cloudwatchlogs/internal/pusher/sender.go
plugins/outputs/cloudwatchlogs/internal/pusher/sender_test.go
plugins/outputs/cloudwatchlogs/internal/pusher/target.go
plugins/outputs/cloudwatchlogs/internal/pusher/target_test.go

The agent processes PutRetentionPolicy on monitored log groups synchronously every time it restarts, which can lead to API throttling in large deployments. This throttling may cause delays in pushing logs while it is active.
- Add a new goroutine in TargetManager to process PRP using a retention processing channel
- Make the retention update channel as blocking channel so no updates get dropped when it's full
- Check existing retention policy of a target using `DecribeLogGroups` then skip PRP is there is no change
- Add backoff and jittering which don't exceed max wait time of 30sec
- Use `rand` when calculating jitter
- Skip DLG for newly created log groups
- Add unit tests to cover this new path
- Separate channels for DLG and PRP and process them separately
- Use `seededRand` which …

skip PutRetentionPolicy by checking existing policy 

---

.github/workflows/build-test-artifacts.yml

`inputs.test-image-before-upload` was added as part of https://github.com/aws/amazon-cloudwatch-agent/pull/1445 as a requirement to start the integration tests after a build. Push events will not have an `inputs` context.
Update the workflow so it triggers the integration tests on merge again.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
> `github.event_name` |	string	| The name of the event that triggered the workflow run.
1. Run `make fmt` and …

Fix run integration tests on merge

---

plugins/outputs/cloudwatchlogs/internal/pusher/target.go
plugins/outputs/cloudwatchlogs/internal/pusher/target_test.go

Same change as https://github.com/aws/amazon-cloudwatch-agent/pull/1566
If there are multiple instances of the CloudWatch agent that are trying to create the same log group, there are cases where streams within those log groups will not be created because `CreateLogGroup` returns `ResourceAlreadyExists`.
https://github.com/aws/amazon-cloudwatch-agent/blob/af960d73a8df75ed2d23b53f34a5813727829018/plugins/outputs/cloudwatchlogs/internal/pusher/target.go#L72
Resource already exists shouldn't be considered a failure to create the resource. Only add the target to the cache if the log stream was created or already exists.
Added more unit test cases to …

Only add to cache if log stream is created

---

.github/workflows/test-artifacts.yml

The `StopLocalStackCN` job consistently fails
Example: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12834512020/job/35934901829
Add OutputEnvVariables job as dependency for `StopLocalStackCN`. This matches what we have for `StopLocalStack` and `StopLocalStackITAR`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. ✅ 
Integration Test: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13658401201/job/38188807290
1. Run `make fmt` and `make fmt-sh` ✅ 
2. Run `make lint` ✅

Fix the StopLocalStackCN job

---

.github/workflows/ec2-integration-test.yml
.github/workflows/integration-test.yml
.github/workflows/test-artifacts.yml

The current workflow job names are hardcoded above the character limit actions, making it difficult to identify individual test runs easily. This can lead to confusion when reviewing test results and logs.
This change updates the job names in the workflow files to use dynamic names from the test matrix array (`${{matrix.arrays.testName}}`). This will allow each test to have a unique and descriptive name, improving clarity and traceability.
Needs: https://github.com/aws/amazon-cloudwatch-agent-test/pull/474
The following tests have been conducted:
- Verified that the workflow files successfully parse with the updated job names.
- Ensured that the …

Update Workflow Job Names for Clarity

---

plugins/processors/awsapplicationsignals/internal/resolver/endpointslicewatcher.go

In the case when application signals is enabled, when the application pod restarts, the endpointSliceWatcher handleSliceUpdate function is passing the arguments in reverse order. This could mess the ipToWorkload and serviceToWorkload mapping used for generating the corresponding workload for appsignal metrics and traces
Corrected the order to send arguments
Validated with OTLP custom metrics entity change using the same endpointslice watcher. …

fixed the issue with endpointSliceUpdate handle in application signals

---

tool/clean/clean_eks/clean_eks.go

_We need to clean up our clusters more frequently to ensure that resources are not being held for too long._
_This change updates the expiration duration for clusters from four days to one day. I think we need to clean up more frequently to optimize resource usage and reduce costs._
[GHA Run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13905834216/job/38908553206)

Increase EKS Cluster Cleanup Frequency

---

.github/workflows/clean-aws-resources.yml
tool/clean/clean_security_group/clean_security_group.go
tool/clean/clean_security_group/clean_security_group_test.go

This pull request adds a new workflow job to clean up old security groups in AWS. The issue is related to managing outdated security groups to maintain a clean and secure AWS environment.
- Added a new job `clean-security-groups` in the GitHub Actions workflow `.github/workflows/clean-aws-resources.yml`.
- Created a new Go file `clean_security_group.go` with a function to clean security groups and adjusted the context timeout to 10 minutes.
- Created a new test file `clean_security_group_test.go` for the security group cleaning functionality.
[GHA Run](https://github.com/aws/amazon-cloudwatch-agent/actions/runs/13930209980)
And ran unittest
```
ok …
```

Added Security Group Clean Up Script

---

cfg/envconfig/envconfig.go
cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
extension/agenthealth/handler/useragent/useragent.go

Currently, there is no way to determine how many CloudWatch Agents (CWA) have SELinux enabled. This PR addresses that by introducing an environment variable (`SELINUX`), which is set using the SELinux installation script and stored in the systemd override file for the CloudWatch Agent service.  
- A new environment variable, **SELINUX**, is set to `true` or `false` based on whether SELinux is enabled.  
- This variable is written to `/etc/systemd/system/amazon-cloudwatch-agent.service.d/override.conf`.  
- The systemd override file remains unchanged when the CloudWatch Agent is updated, ensuring SELinux status tracking persists across versions.  
- The agent reads the **SELINUX** environment variable and includes it in the user-agent string.  
- This provides insight into SELinux usage …

Add SELinux Status using useragent

---

cfg/envconfig/envconfig.go
cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
extension/agenthealth/handler/useragent/useragent.go

Currently, there is no way to know the number of CloudWatch Agent's running on ROSA. This PR addressing this issue by introducing a new env. variable (`RUN_ON_ROSA`), which is set by helm charts. 
- A new environment variable, **RUN_ON_ROSA**, is set to `true` or `false` based on whether  the cluster is ROSA.  
-  This variable is set by helm chart when ROSA flag is passed. 
- The agent reads the **rosa** environment variable and includes it in the user-agent string.  
- Enables visibility into Rosa adoption among CloudWatch Agent users.  
- Assists in debugging and understanding system security configurations.  
- Ensures the change is persistent across agent updates with minimal disruption.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Agent Health Metric for ROSA

---

plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

When collecting OTLP custom metrics, if a sample application isn't configured properly, it can sometimes send faulty non-distribution metrics that don't include a value.
```
│   ],                                                                                                                                                                                                                                                                                                                                   │
│   MetricName: "http.server.duration", …
```

[Bug Fix] Drop metric if it has nil value in cloudwatch exporter

---

RELEASE_NOTES

This pr is to update release notes for 1.300054.0 release. Below are the changes for this pr:
Features:
- Added Elastic Network Interface (ENI) ID as a dimension to EFA (Elastic Fabric Adapter) metrics
- Added support for using Kubernetes secret file for bearer token when accessing apiserver Prometheus endpoint
Enhancements:
- [ContainerInsights]: Switched to using EndpointSlices instead of Endpoints for improved performance in large EKS clusters
- [Logs]: Added option to trim timestamp from log messages if enabled by customer
- [EC2Tagger]: Set separate refresh intervals for tags (default 0) and volumes (default 5 minutes if VolumeId configured)
Bug Fixes:
- [CloudWatch Exporter]: Fixed issue with nil metric values by dropping metrics with nil values
- [Logs]: Implemented fixed-size …

Update RELEASE_NOTES 1.300054.0 release

---

.github/workflows/test-artifacts.yml

This will be used to programmatically search for the workflow kicked off programmatically since the GitHub API doesn't return the workflow ID
We want to build a system that will automatically start the integration tests on candidate release artifacts. Right now, the system can kick off integration tests using the GitHub REST API by essentially running the following:
```
% curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer <TOKEN>" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/aws/amazon-cloudwatch-agent/actions/workflows/test-artifacts.yml/dispatches \
-d '{"ref":"main","inputs":{"build_id":"1.300053.0b1047"}}'
```
Unfortunately, this API call does not return the created workflow ID ([see …

Add workflow step that is named after the build_id input

---

tool/clean/clean_log_group/clean_log_group.go
tool/clean/clean_log_group/clean_log_group_test.go

This PR updates the getLastLogEventTime function to correctly handle pagination in the DescribeLogStreams API call. The changes ensure that all pages of log streams are processed, the function finds the latest timestamp across all streams in all pages, and the NextToken is properly used to fetch subsequent pages of results.
With the current implementation, the unit test fails. This modification allows the function to accurately determine the most recent event timestamp across all log streams in a log group, even when the results span multiple pages, enabling the test to pass.
_Before commit the code, please do …

Fix TestGetLastLogEventTime Unit test

---

plugins/processors/awsentity/processor.go
plugins/processors/awsentity/processor_test.go

Agent can be now deployed as deployment and statefulset along with daemonset. In the entity attributes retrieval logic for K8s env, Agent can only get its own instance Id. This Agent instance id will be the same as Application instance id in case of daemon set. But in deployment and statefulset, its not the case.
Agent Entity processor will not attach instance Id to the attributes if the node name of agent is different from node name of application metrics.
Unit Tests
Manual Test
1. Created an EKS …

Add Instance id entity attribute only if the application node is same as agent node

---

.github/workflows/clean-aws-resources.yml
.github/workflows/deploy-canary.yml
.github/workflows/ec2-integration-test.yml
.github/workflows/eks-e2e-test.yml
.github/workflows/soak-test.yml
.github/workflows/start-localstack.yml
.github/workflows/stop-localstack.yml
.github/workflows/test-artifacts.yml
.github/workflows/test-build-docker.yml
.github/workflows/test-build-packages.yml
.github/workflows/test-build.yml
.github/workflows/upload-dependencies.yml

`aws-actions/configure-aws-credentials@v2` is causing some PR builds to fail. 
Example: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14408093789/job/40412633269?pr=1644
This change updates to `aws-actions/configure-aws-credentials@v4` to eliminate any errors during the PR build step 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. ✅ 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14409196465
1. Run `make fmt` and `make fmt-sh` ✅ 
2. Run `make lint` ✅

Update configure-aws-credentials version

---

extension/k8smetadata/extension.go
internal/k8sCommon/k8sclient/endpointslicewatcher.go
internal/k8sCommon/k8sclient/endpointslicewatcher_test.go
internal/k8sCommon/k8sclient/kubernetes_utils.go
internal/k8sCommon/k8sclient/kubernetes_utils_test.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes_test.go

When a kubernetes service is backed by a deployment with only one pod, we will observe the wrong service ip to workload mapping when the pod is killed. This is due to the following race:
- Pod termination triggered a 2-min delayed deletion for the service ip to workload mapping.
- A new pod started quickly and re-added the service ip to workload mapping.
- The delayed deletion erroneously removed the new mapping because deletion was based solely on key.
This change introduces TimedDeleterWithIDCheck, which only deletes the mapping if the value’s UUID
remains unchanged. This ensures that if the mapping is updated (even with the same string content),
it won’t be deleted …

Fix service ip to workload mapping in an edge case

---

.github/workflows/PR-test.yml

Currently we have a run that tests for multiple different linux os's but we only want to test for al2 and al2023. Here is the an example run. https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14477540108/job/40606719207?pr=1628
This pr removes other os's from test and just keeps al2 and al2023.

Removing unwanted os's test for selinux in pr-test 

---

.github/workflows/e2e-test.yml
.github/workflows/eks-e2e-test.yml

This PR adds parallel test paths for both Helm and Addon deployment methods in the EKS E2E test workflow. The changes include:
1. Renamed existing e2e tests jobs to include "Helm" suffix:
- EKSE2EJVMTomcatTest → EKSE2EJVMTomcatTestHelm
- EKSE2EKafkaTest → EKSE2EKafkaTestHelm
- EKSE2EJMXContainerInsightsTest → EKSE2EJMXContainerInsightsTestHelm
2. Added new corresponding test jobs for EKS Add-on:
- EKSE2EJVMTomcatTestAddon
- EKSE2EKafkaTestAddon
- EKSE2EJMXContainerInsightsTestAddon
3. Added `eks_installation_type` flag to indicate Helm Charts of EKS Add-on installation
These changes will allow us to validate both deployment methods in parallel, ensuring compatibility and functionality across different installation approaches.
By submitting this pull request, I confirm that you can use, …

Add eks addon e2e tests and update original helm charts e2e tests

---

.github/workflows/repackage-release-artifacts.yml

Integration tests for release candidate artifacts are failing because it is unable to find the AMD64 version of the .pkg files. 
There is a typo in the repackaging workflow that uploads the AMD64 version of the files to the ARM64 path, which then gets overwritten by the real ARM64 artifacts.
Ran the updated commands manually, re-executed integration tests, AMD64 Mac tests are successful.

Fix typo in repackaging for Mac AMD64

---

.github/workflows/test-build-docker.yml

Before this change, the linux images published to ECR are layered with an Attestation created by default by the docker build-push-action. As a result, a top level image index is created with the expected amd64/arm64 tag. Lack of tag on the nested linux images prevents automated identification of the linux image manifests (ex: for filtering CVE scan results)
This change sets the docker build-push-action flag for `providence` to false to stop creating the Attestation and top level image index. This now allows the actual CWA image to be published to ECR with the expected tags `linux-amd64` and `linux-arm64`
Additionally, builds the multi-architecture manifest list using `docker create manifest` since the above change removes the linux image index. We can now point directly to the CWA linux …

Remove Attestation from Linux image manifests in ECR for Nightly Build

---

.github/workflows/test-artifacts.yml

The LinuxOnPremIntegrationTest doesn't run because the input variable is empty. This causes the `Run Integration Tests` workflow to fail even though all the steps succeed: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14519244551
Looking through the history, it appears this test never ran or worked
Removing LinuxOnPremIntegrationTest for now so that our workflows succeed. We can re-implement it later.
Running integ tests now: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/14673425065

Remove LinuxOnPremIntegrationTest

---

plugins/processors/awsapplicationsignals/internal/attributes/attributes.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go

*Callout*: Original PR: https://github.com/aws/amazon-cloudwatch-agent/pull/1673
In this change, we are supporting new attribute copying behaviour for ApplicationSignals. This will allow customers to specify which/all attributes they want to be present in their EMF records. 
If the following key is present in the resource attributes: `aws.application_signals.metric_resource_keys`, we will copy attributes specified in the value (or all attributes if `all_attributes`) from resource to metric. Note that we do not copy attributes that are already copied/normalized by exisiting ApplicationSignals processor logic, to avoid data duplication. Also note that we prefix all copied attribute keys with `otel.resource` to avoid collisions with existing metric attributes.
By submitting this pull …

[ApplicationSignals] Support copying resource attributes to metric attributes for EMF export

---

.github/workflows/deploy-canary.yml
.github/workflows/ec2-integration-test.yml
.github/workflows/eks-e2e-test.yml
.github/workflows/soak-test.yml
.github/workflows/start-localstack.yml
.github/workflows/stop-localstack.yml
.github/workflows/test-artifacts.yml

Currently terraform version 1.12.1 breaks our integ test so in order to fix this issue we want to dowgrade to version 1.12.0 which works.
Here is the failing tests with terraform version 1.12.1: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15166429108. If you check the 
Here is the passing tests with terrafomr version 1.12.0: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15118083578
Branch Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15168159406

fixing terraform for integ tests

---

plugins/processors/awsapplicationsignals/processor.go
plugins/processors/awsapplicationsignals/processor_test.go

This PR fixes a panic issue described in https://github.com/aws/amazon-cloudwatch-agent/pull/1702.
`golang.org/x/text/cases.Caser.String` is not goroutine safe. In this PR, we initialize a new Caser when a metric processed by Application Signals is found with camel case naming.
Added a unit test.
Before the change:
The unit test returned with 
```
goroutine 7 [running]:
golang.org/x/text/cases.(*context).copyXOR(0xc000016280)
golang.org/x/text/cases.title(0xc000016280)
golang.org/x/text/cases.(*titleCaser).Transform(0xc000016280, {0xc0004bc000, 0x80, 0x80}, {0xc0004bc080, 0x5, 0x80}, 0x1)
golang.org/x/text/transform.String({0x130064088, …
```

fix panic under concurrency in application signals processor

---

translator/config/schema.json
translator/tocwconfig/sampleConfig/compass_linux_config.json
translator/tocwconfig/sampleConfig/compass_linux_config.yaml
translator/translate/otel/pipeline/host/translator.go
translator/translate/otel/pipeline/host/translator_test.go
translator/translate/otel/processor/awsentity/translator.go
translator/translate/otel/processor/awsentity/translator_test.go
translator/translate/util/entityutil.go
translator/translate/util/entityutil_test.go

For existing plugins supported as Service entity for Explore Related integrations, customers have the option to configure the service name and environment name. We need to do the same for OTLP metrics.
1. Add translation for detecting configuration value for `service.name` and `deployment.environment`.
2. Sets `AWS.ServiceNameSource` as `UserConfiguration` when the configuration is detected.
3. Configuration allowed for both CloudWatch And EMF exporter. Example:
```
{
"metrics": {
"metrics_collected": {
"otlp": {
"service.name": "config-service-name",
"deployment.environment": "config-environment-name"
}
}
}
}
```
```
"logs": {
"metrics_collected": {
"otlp": {
"service.name": "otlp-level-service",
"deployment.environment": "otlp-level-environment",
"grpc_endpoint": "127.0.0.1:4317", …
```

[translator/awsentity] Allow service and environment configuration for OTLP in EC2

---

.github/workflows/PR-test.yml

Reduce unnecessary integration test runs triggered each commit that is pushed to a PR
Adds a step to check for the `ready for testing` label on a PR before running the PR-test workflow.
Tests **skipped** when label is not present on PR
Tests **ran** when label is present on PR

Add step to check for `ready for testing` label before running integration tests

---

plugins/processors/awsapplicationsignals/internal/attributes/attributes.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver_test.go

ApplicationSignalsProcessor relies on the resource attribute `deployment.environment` as a customer-provided override for ApplicationSignals `Environment`. However, `deployment.environment` has been deprecated and replaced with `deployment.environment.name` in the upstream.
In this PR, we are adding support for the new attribute, while maintaining support for the old attribute, since customers may still specify `deployment.environment`, for example, if they are running on older OTEL versions.
Callout: We are no longer getting these attribute names from semconv as:
1. We were relying on go.opentelemetry.io/collector/semconv/v1.22.0, which does not have `deployment.environment.name`
2. https://pkg.go.dev/go.opentelemetry.io/collector/semconv has been deprecated
3. It's replacement, …

Add support for deployment.environment.name

---

.github/workflows/eks-performance-cluster-scaling.yml

We are working towards implementing EKS performance testing on a large scale EKS cluster. The cluster is already created and static.
Implemented a github workflow that does the following:
1. Connects to EKS cluster
2. Uses aws eks cli to scale the nodegroups up and down. 
Success Case: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/16332007802/job/46136527659
Failure Case: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/16331406386/job/46134643323
Defaults and variables work for both.
4. Run `make lint`
-------
To run …

[EKS Performance Testing] Implement github action for scaling up and down eks performance cluster

---

.github/workflows/eks-performance-cluster-addon-install.yml

To enable performance testing on the large scale testing EKS cluster created [here](https://github.com/aws/amazon-cloudwatch-agent/pull/1776), we need to ensure that the AWS Observability addon gets installed upon cluster sclaing action. This task implements a github action that will do this via helm.
- Created GitHub action for installing addon with helm
- Builds the latest versions of the operator and agent and uplaods it to ECR
- Installs it using helm command
- Triggers upon completion of the `EKS Cluster Scaling` workflow
- Can also be ran manually with workflow_dispatch
- Cleans/removes helm chart on 2 conditions: If the task fails/is canceled or node count is 0 which means a scale down was completed
By submitting this pull request, I confirm that you can use, modify, copy, and …

Implement workflow to install addon/helm on performance cluster

---

.github/workflows/eks-performance-cluster-addon-install.yml
.github/workflows/eks-performance-cluster-scaling.yml
.github/workflows/eks-performance-cluster-tests.yml

As part of an initiative to improve our performance testing on large scale eks clusters, we need to implement workflows that scale up, install addon and execute test that runs on our 5k node cluster.
1. eks-performance-cluster-scaling.yml - Responsible for scaling eks-performance cluster (5k node cluster). 
- Updated to also scale up leader node group dynamically. This node group has max of 1 node t3.xlarge
- Scales up on Sunday 9am, scales down Monday 9pm
2.  eks-performance-cluster-addon-install.yml - Responsible for installing the addon upon successful completion of scaling workflow
- adds the `cwagent-target="true"` label to all t3.medium instances in the cluster (non leader node). This ensures that cloudwatch-agent non leader pods are installed on these nodes
- gets the hostname …

[EKS Scalability Testing] Implement workflows to execute large scale performance test

---

tool/clean/clean_ecs/clean_ecs.go

This allows the ecs cleanup script to handle deletion of clusters whose services have failed tasks, or have tasks that have been open for more than a week.
See old output of buggy ECS Resource Cleanup run (clean-ecs-clusters): https://github.com/aws/amazon-cloudwatch-agent/actions/runs/16610452973/job/46992332357
1. Add logic to scale down ecs cluster services before deleting them to avoid getting a 400 on deletion of active services
Ex: 
```
2025/07/30 00:29:15 Error operation error ECS: DeleteCluster, https response error StatusCode: 400, RequestID: 3162fff1-ae25-4a19-8723-efd1610f8702, ClusterContainsServicesException: The Cluster cannot be deleted while Services are active. terminating cluster arn:aws:ecs:us-west-2:506463145083:cluster/cwagent-integ-test-cluster-04e4c49e62995d6e
``` …

Delete Clusters with Active Services during ECS Cleanup

---

.github/workflows/clean-aws-resources.yml
tool/clean/clean_ecs/clean_ecs.go

Inactive ECS Task Definitions pile up in the integ test account. Introduce automation to clean them up as part of the daily resource cleaning action
1. Introduces ECS Task Def cleanup that deletes inactive task definitions
2. Accepts a regional flag to direct resource cleanup to us-west-2 
1) Validated by running the Github Action (clean-ecs-resources): https://github.com/aws/amazon-cloudwatch-agent/actions/runs/16633942082/job/47070224114
2) Validated locally
```
cd ./tool/clean && go run --tags clean ./clean_ecs/clean_ecs.go us-west-2 
```
2. Run …

Auto Cleanup ECS inactive TaskDefs

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

Adding new Neuron Core and EFA capacity metrics. Same as:
* https://github.com/aws/amazon-cloudwatch-agent/pull/1815
* https://github.com/aws/amazon-cloudwatch-agent/pull/1816
See PRs above.
-------

Add Neuron Core and EFA capacity metrics

---

plugins/processors/prometheusadapter/processor.go
translator/translate/otel/extension/ecsobserver/translator.go
translator/translate/otel/extension/ecsobserver/translator_test.go
translator/translate/otel/receiver/prometheus/translator_test.go

Updates ECS Observer Config Translator for parity with existing Ecs Service Discovery defaults
List of modifications
* Dynamically retrieve default value for clusterName and clusterRegion when not provided (make them optional)
* Update refreshDuration default to `1m`
* Update ResultFile default to `/tmp/cwagent_ecs_auto_sd.yaml`
* Update JobNameLabel default to `job`
* Update MetricPathLabel default to `ECS_PROMETHEUS_METRICS_PATH`
Updated unit tests & all tests pass
```
make test
make fmt
make fmt-sh
make lint
```
-------
To run …

Ecs Observer config

---

tool/processors/defaultConfig/standardPlan/plan.go

When using the config wizard, if the user answers `no` to `Do you want to monitor cpu metric per core` and then selects `Standard` or `Advanced` default section, the wizard creates a useless and somewhat confusing cpu section of the generated agent configuration because the `resources` section is empty and `totalcpu` is set to false, so no CPU metrics are collected.
```
$ /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard
================================================================
= Welcome to the Amazon CloudWatch Agent Configuration Manager =
=                                                              =
= CloudWatch Agent allows you to collect metrics and logs from =
= your host and send them to CloudWatch. Additional CloudWatch =
= charges may apply. …
```

[config-wizard] Only include CPU section if requested

---

translator/tocwconfig/sampleConfig/container_insights_jmx.yaml
translator/tocwconfig/sampleConfig/jmx_eks_config_linux.yaml
translator/translate/otel/processor/transformprocessor/transform_jmx_config.yaml
translator/translate/otel/processor/transformprocessor/transform_jmx_drop_config.yaml
translator/translate/otel/processor/transformprocessor/translator_test.go

Currently for CWA addon version v4.2.0 when jmx is configured we never set the error_mode for context in the transform processor as we never updated the default yamls. This causes the CWA to generate error_mode: "" in its generated yaml which leads to an error as error_mode can't be an empty string. A similar issue also occurred during the Otel Bump to v0.124.1 and the fix was to initialize error_mode to the default which is "propagate". This is the contrib pr that added error_mode to the context statement: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/9280ca1c515d86a10da6378154a27404472ac56c. 
Adding "propagate" as default error_mode value for transform processor's default agent yaml to fix empty string initialization for the CWA. 
Ran the addon version v4.2.0 …

Fixing CWA error_mode bug in addon v4.2.0 

---

go.mod
go.sum

Configures "job" label for ecs_service_discovery by pulling in bug-fix
Bug fix does not modify the job label when optional JobLabelName is omitted. Previously, omitting JobLabelName caused unexpected behavior of "job" label to be renamed to empty string
Unit tests & integration tests pass
Validated "Job" label is no longer overwritten in the ecs_sd result file on disk
```
make test 
make fmt
make fmt-sh
make lint
```
-------

Pull in otel-collector-contrib go mod tidy

---

translator/tocwconfig/sampleConfig/prometheus_customer_relabel_config_linux.conf
translator/tocwconfig/sampleConfig/prometheus_customer_relabel_config_linux.json
translator/tocwconfig/sampleConfig/prometheus_customer_relabel_config_linux.yaml
translator/tocwconfig/testdata/prometheus_customer_relabel.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/otel/receiver/prometheus/translator.go
translator/translate/otel/receiver/prometheus/translator_test.go

When a customer provides prometheus scrape config relabel configs, we should not overwrite them. Additionally, the customer provided config must be processed last, after the default relabel config. This is to retain backwards compatibility given the new labels generated by the OTEL plugin for prometheus file-based service discovery (ECS Observer).
This change detects customer provided relabel configs and appends them to the dynamically configured relabel configs so that they can be processed after
ex: 
Customer provides
```		Action:       relabel.Replace,
SourceLabels: model.LabelNames{"StartedBy"},
TargetLabel:  "CustomStartedBy",
Regex:        relabel.MustNewRegexp("(.*)"),
```
then the generated relabelConfig must look like this so that the Customer's action on `StartedBy` does not …

Append customer prometheus scrape configs

---

go.mod

This reverts commit ed3141ea953caedee6fb7a3d574eb270ef5bfaae.
The Go bump PR didn't actually test anything because it pulled from the github cache and we're now running into issues. The linter we use is incomaptible with go1.25 and unit tests are regularly failing on windows-2022: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/17499483424/job/49712282164?pr=1849
Reverting the commit. We will re-do the Go bump.
-------
To run integration tests against this PR, add the `ready for …

Revert "Bump Go (#1845)"

---

go.mod
go.sum
translator/tocwconfig/sampleConfig/prometheus_customer_relabel_config_linux.yaml
translator/tocwconfig/sampleConfig/prometheus_ecs_sd_config_linux.yaml
translator/translate/otel/receiver/prometheus/translator.go
translator/translate/otel/receiver/prometheus/translator_test.go

Support labelmap actions for ecs service discovery for all docker labels.
By default, ECS Observer will prefix all docker label config with `__meta_ecs_container_labels_` and therefore prometheus receiver will drop them. The Telegraf-based ecs_service_discovery feature captured docker labels without the prefix, preventing the prometheus receiver from dropping them. As a result, this change serves to loop through all dockerlabels captured by the otel-based ecs observer, and discard the prefix to restore parity with the telegraf-based ecs service discovery.
Ex: `__meta_ecs_container_labels_app_x` will be relabeled to `app_x`
Ex: `__meta_ecs_container_labels_ECS_PROMETHEUS_EXPORTER_PORT` will be relabeled to `ECS_PROMETHEUS_EXPORTER_PORT`
Pulls in otel …

Support labelmap relabel for ecs sd

---

translator/tocwconfig/sampleConfig/prometheus_customer_relabel_config_linux.yaml
translator/tocwconfig/sampleConfig/prometheus_ecs_sd_config_linux.yaml
translator/tocwconfig/tocwconfig_test.go
translator/translate/otel/receiver/prometheus/translator.go
translator/translate/otel/receiver/prometheus/translator_test.go

Adding tests for prometheus clusterName readin
This validates the correct clusterName is read in when configured multiple ways. 
Also leverages the existing code in the ecs and eks utils, rather than using new custom code.
Introduced translator unit testing and config translation testing
```
make test
make lint
make fmt
make fmt-sh
```
-------

Add tests for Prometheus ClusterName
