aws/amazon-cloudwatch-agent

plugins/inputs/win_perf_counters/win_perf_counters_test.go

fix: win_perf_counters test case wrong int to string conversion

---

RELEASE_NOTES

Update release_notes for 1.247345.34 release

Add release notes for 1.247345.34 release

---

plugins/processors/emfProcessor/emfProcessor.go
plugins/processors/emfProcessor/emfProcessor_test.go
plugins/processors/emfProcessor/metricDefinition.go
plugins/processors/emfProcessor/metricDefinition_test.go
translator/config/schema.go
translator/config/schema.json
translator/totomlconfig/sampleConfig/prometheus_config_linux.conf
translator/totomlconfig/sampleConfig/prometheus_config_linux.json
translator/totomlconfig/sampleConfig/prometheus_config_windows.conf
translator/totomlconfig/sampleConfig/prometheus_config_windows.json
translator/totomlconfig/toTomlConfig_test.go
translator/translate/logs/metrics_collected/prometheus/emfprocessor/ruleMetricUnit.go
translator/translate/logs/metrics_collected/prometheus/prometheus.go

_Register prometheus config rule for Windows OS; Prometheus EMF metrics unit support_
_Register prometheus config rule for Windows OS; Prometheus EMF metrics unit support_
_make release; test local build rpm on linux instance, local exe builds on Windows instance_

Register prometheus config rule for Windows OS; Prometheus EMF metrics unit support

---

translator/config/sampleSchema/validLinuxMetrics.json
translator/config/schema.go
translator/config/schema.json
translator/totomlconfig/sampleConfig/statsd_config.json
translator/totomlconfig/sampleConfig/statsd_config_linux.conf
translator/totomlconfig/sampleConfig/statsd_config_windows.conf
translator/translate/metrics/metrics_collect/statsd/ruleAllowedPendingMessages.go
translator/translate/metrics/metrics_collect/statsd/statsd_test.go

Make allowed_pending_messages to be configurable for Statsd

Make allowed_pending_messages to be configurable for Statsd

---

RELEASE_NOTES

update release note

---

Makefile

check if there is aws credentials in the package.
check if there is aws credentials in the package.
make

add check secrets

---

amazon-cloudwatch-container-insights/CHANGELOG.md
amazon-cloudwatch-container-insights/container-insights-manifest-update.sh
amazon-cloudwatch-container-insights/ecs-task-definition-templates/deployment-mode/daemon-service/cwagent-ecs-instance-metric/cloudformation-quickstart/cwagent-ecs-instance-metric-cfn.json
amazon-cloudwatch-container-insights/ecs-task-definition-templates/deployment-mode/daemon-service/cwagent-ecs-instance-metric/cwagent-ecs-instance-metric.json
amazon-cloudwatch-container-insights/ecs-task-definition-templates/deployment-mode/replica-service/cwagent-prometheus/cloudformation-quickstart/cwagent-ecs-prometheus-metric-for-awsvpc.yaml
amazon-cloudwatch-container-insights/ecs-task-definition-templates/deployment-mode/replica-service/cwagent-prometheus/cloudformation-quickstart/cwagent-ecs-prometheus-metric-for-bridge-host.yaml
amazon-cloudwatch-container-insights/ecs-task-definition-templates/deployment-mode/replica-service/cwagent-prometheus/cwagent-prometheus-task-definition.json
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/cwagent/cwagent-daemonset.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluentd/fluentd.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/prometheus-eks.yaml
amazon-cloudwatch-container-insights/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/prometheus-k8s.yaml

Update the manifest files for container insights based on latest changes in https://github.com/aws-samples/amazon-cloudwatch-container-insights.

Sync manifest files for container insights

---

cmd/start-amazon-cloudwatch-agent/path_linux.go

The container image does not run agent as PID 1, so it won't get signal (`SIGTERM`) from container runtime to shutdown gracefully. Besides running one process in container is the best practice.
Use `exec` instead of `fork+exec` when starting agent binary from `start-amazon-cloudwatch-agent`
- build the image, `docker run` and ctrl + c (foreground) or `docker stop` the exit code is 0.
- if you use publish image like `amazon/amazon-cloudwatch-agent`, you will get 2
- deploy the newer image as ECS task and stop the task

container: Run agent as PID 1 for graceful shutdown

---

.gitmodules
Makefile
README.md
THIRD-PARTY
Tools/src/create_deb.sh
Tools/src/create_rpm.sh
Tools/src/create_win.sh
cmd/config-downloader/downloader.go
licensing/THIRD-PARTY-LICENSES
packaging/debian/cwagent-otel-collector.conf
packaging/debian/postinst
packaging/dependencies/amazon-cloudwatch-agent-ctl
packaging/dependencies/cwagent-otel-collector.service
packaging/linux/amazon-cloudwatch-agent.spec
packaging/linux/cwagent-otel-collector.conf
packaging/windows/amazon-cloudwatch-agent-ctl.ps1
packaging/windows/install.ps1

Package aws-otel-collector into amazon-cloudwatch-agent
* Use command `sudo /usr/bin/amazon-cloudwatch-agent-ctl -a fetch-config -o default -s` to start otel collector.
```
git submodule init && git submodule update
make release
```
```
> sudo /usr/bin/amazon-cloudwatch-agent-ctl -a fetch-config -o default -s
> ps -eaf | grep cwagent-otel-collector
cwagent   8522     1  0 06:07 ?        00:00:00 /opt/aws/amazon-cloudwatch-agent/bin/cwagent-otel-collector --config /opt/aws/amazon-cloudwatch-agent/cwagent-otel-collector/etc/cwagent-otel-collector.yaml
```

Composite agent

---

RELEASE_NOTES

Update RELEASE_NOTE for 1.247347.0
```
git submodule init && git submodule update
make release
```

Update RELEASE_NOTE for 1.247347.0

---

.github/workflows/build.yml
.gitmodules
Makefile
README.md

use relative path for submodule
```
git submodule update --init
make release
```

chore: use relative path for submodule

---

plugins/inputs/cadvisor/extractors/net_extractor.go

The value of network is to huge some times, it is incredible.
add debug log to check if the value is negative.

chore: add debug log to network in cadvisor plugin

---

packaging/darwin/amazon-cloudwatch-agent-ctl

Add `all` option for `remove-config`
- `all` option in ctl script
- misc fixes 
(internal) integration test

mac: Add remove-config all

---

.github/workflows/build.yml
plugins/inputs/logfile/tail/file_deleting_checker.go
plugins/inputs/logfile/tail/file_deleting_checker_darwin.go
plugins/inputs/logfile/tail/file_deleting_checker_windows.go

add Macos build into the workflow
1. add Macos build into the workflow
2. build the deletion detection logic into macos

add macos into the workflow

---

RELEASE_NOTES

Release version 1.247347.5

---

plugins/inputs/cadvisor/cadvisor_windows.go
translator/util/platform_windows.go

Fix https://github.com/aws/amazon-cloudwatch-agent/issues/181
`\n` x 2

build: Add space after +build

---

metric/distribution/seh1/seh1_distribution.go
tool/processors/migration/linux/knownConfigKeys.go
tool/processors/migration/windows/windows_migration_core.go
translator/translate/logs/logs_collected/windows_events/collect_list/collectlist.go
translator/translate/metrics/config/registered_instances.go

Internal amazon links are in the repo
Remove internal links
Only comments were changed thus no testing was done.

Remove Internal Links

---

plugins/inputs/logfile/tail/file_deleting_checker_windows.go
plugins/inputs/logfile/tail/tail.go
plugins/inputs/logfile/tail/tail_test.go

Dropped log counts need to be made visible.
Added logging for dropped log counts when the tail is stopped with StopAtEOF.
Added unit test for tail for the dropped log scenarios.

Changed tail to use the telegraf logger.

---

internal/retryer/logthrottle.go
internal/retryer/logthrottle_test.go

Follow-up to https://github.com/aws/amazon-cloudwatch-agent/pull/243 .

Some improvements to throttle event logging.

---

translator/cmdutil/userutil.go
translator/cmdutil/userutil_darwin.go
translator/cmdutil/userutil_test.go

Follow-up to https://github.com/aws/amazon-cloudwatch-agent/pull/241 .

Small fixes to file ownership change logic.

---

.github/workflows/integrationTest.yml
.gitignore
Makefile
integration/localstack/docker-compose.yml
integration/localstack/ls_tmp/snakeoil.conf
integration/terraform/ec2/linux/main.tf
integration/terraform/ec2/linux/providers.tf
integration/terraform/ec2/linux/variables.tf
integration/test/agent_util.go
integration/test/ca_bundle/ca_bundle_test.go
integration/test/ca_bundle/resources/integration/ssl/with/combine/bundle/common-config.toml
integration/test/ca_bundle/resources/integration/ssl/with/combine/bundle/config.json
integration/test/ca_bundle/resources/integration/ssl/with/original/bundle/common-config.toml
integration/test/ca_bundle/resources/integration/ssl/with/original/bundle/config.json
integration/test/ca_bundle/resources/integration/ssl/without/bundle/common-config.toml
integration/test/ca_bundle/resources/integration/ssl/without/bundle/config.json
integration/test/ca_bundle/resources/integration/ssl/without/bundle/http/common-config.toml
integration/test/ca_bundle/resources/integration/ssl/without/bundle/http/config.json
integration/test/empty/empty_test.go

Support running integration tests on more than 1 linux ami 
Add run integration test to al2 and ubutnu
Integration tests where on my test account.

Add al2 support

---

README.md

Links to nightly build not in read me
Add Links of nightly build to read me
None

Add Links To Nightly Builds

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.247350.0.
Compare against the list of commits:
https://github.com/aws/amazon-cloudwatch-agent/compare/v1.247349.0...v1.247350.0
None.

Update RELEASE_NOTES for 1.247350.0.

---

RELEASE_NOTES

Remove release notes until packages for 1.247350.0 are available.
Remove the last update to release notes.
None.

Remove release notes until packages for 1.247350.0 are available.

---

.github/workflows/build-test-windows.yml
.github/workflows/build.yml

Tests are not being cached
Adding GOCACHE folder to cache

Runner cache folders

---

.github/workflows/codeql-analysis.yml

Add CodeQl analysis for security vulnerabilities, bugs, and other errors. For more information on one of CodeQL result, please [check this article ](https://github.blog/2021-03-16-using-github-code-scanning-and-codeql-to-detect-traces-of-solorigate-and-other-backdoors/)
Test with [adot-collector](https://github.com/aws-observability/aws-otel-collector/blob/main/.github/workflows/codeql-analysis.yml). The result of this can be shown through https://github.com/aws-observability/aws-otel-collector/actions/runs/1786358559
CodeQL: https://codeql.github.com/docs/codeql-overview/about-codeql/

Add CodeQL analysis for security checks, errors

---

integration/test/agent_util.go
integration/test/sanity/resources/verifyLinuxCtlScript.sh
integration/test/sanity/sanity_test.go

Sanity test agent
Add integration test sanity
Ran code on ec2 instance

Add Verify Linux Ctl Integration Test

---

go.mod
go.sum

Integration tests failing for go mod tidy
Run go mod tidy
None

Run Go Mod Tidy

---

.github/workflows/integrationTest.yml
integration/terraform/ec2/linux/README.md
integration/terraform/ec2/linux/main.tf
integration/terraform/ec2/linux/variables.tf
integration/terraform/ec2/localstack/main.tf
integration/terraform/ec2/localstack/variables.tf

Need to run integration testing inside personal aws accounts
Add extra var and readme on how to test in personal aws accounts 
Followed the readme

Support Local Testing Of Terraform

---

.github/workflows/integrationTest.yml
integration/msi/tools/create_msi.ps1
integration/terraform/ec2/linux/README.md
integration/terraform/ec2/linux/main.tf
integration/terraform/ec2/linux/variables.tf
integration/terraform/ec2/win/main.tf
integration/terraform/ec2/win/variables.tf

Need a way for people to test on their own fork
Add ability to test on your fork
Tested on my fork with my aws account not the integration tests main account.

Support Fork Testing On Personal AWS

---

.github/workflows/integrationTest.yml
integration/pkg/tools/create_pkg.sh
integration/pkg/tools/manifest.yaml
integration/pkg/tools/postinstall.sh
integration/pkg/tools/preinstall.sh

There is no way to build pkg on github actions
Add building of pkg on github actions
Ran on my local fork.

Build Mac PKG

---

.github/workflows/integrationTest.yml
integration/pkg/tools/create_pkg.sh
integration/terraform/ec2/linux/README.md

We need to sign our packages with gpg
Sign packages with gpg
Ran on my fork

Add GPG Signing For Packages Fixes (#420)

---

.github/workflows/integrationTest.yml
integration/terraform/ec2/win/variables.tf

Need an auto retry
Add nick-invision/retry@v2
Ran on my fork

Add Retry To Integration Test

---

.github/workflows/clean_ami.yml
.github/workflows/clean_dedicated_host.yml
.github/workflows/internal-pipeline-dedicated-host-cleaner.yml
Makefile
integration/clean/README.md
integration/clean/clean_ami/clean_ami.go
integration/clean/clean_dedicated_host/clean_dedicated_host.go

Need a way to clean dedicated hosts 
Clean host that have been created 26 hr ago
Ran the cleaner.

Clean Dedicated Hosts From AWS Account For Mac Tests

---

integration/clean/clean_dedicated_host/clean_dedicated_host.go

View dedicated host state in logs 
Print dedicated host state in logs

Print Out Dedicated Host State In Clean Action

---

Makefile
amazon-cloudwatch-container-insights/k8s-yaml-templates/cwagent-kubernetes-monitoring/cwagent-configmap.yaml
amazon-cloudwatch-container-insights/k8s-yaml-templates/cwagent-kubernetes-monitoring/cwagent-daemonset.yaml
go.mod
go.sum
internal/k8sCommon/k8sclient/endpoint.go
internal/k8sCommon/k8sclient/k8logger.go
plugins/inputs/k8sapiserver/k8sapiserver.go
plugins/inputs/prometheus_scraper/start.go

Add k8 Logging

---

packaging/debian/preinst
packaging/linux/amazon-cloudwatch-agent.spec
packaging/windows/amazon-cloudwatch-agent-ctl.ps1

Creates a system user, "aoc", for the AWS Distro for OpenTelemetry collector without a shell, or updates an existing "aoc" user on the host so that the existing "aoc" user has no shell.

AOC system user update (#477)

---

plugins/outputs/cloudwatch/cloudwatch.go
plugins/outputs/cloudwatch/cloudwatch_test.go

Increase max batch for calling PutMetricData, update associated tests
Ran `cloudwatch_test.go` and verified that tests still pass

update PMD limits

---

.github/workflows/integrationTest.yml

Owner of the GH action changed their username to `vimtor`
Update GH action to reflect the correct repository

update GH Action to reflect correct GH user

---

.github/workflows/clean_ami.yml
.github/workflows/clean_dedicated_host.yml
.github/workflows/integrationTest.yml
.github/workflows/releaseTest.yml
integration/terraform/ec2/README.md

We do not want hard coded creds 
Use assume role
N/A

Created Terraform Assume Role

---

.github/workflows/integrationTest.yml

Issue with assuming role
Add permission to assume role https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931805471
Ran on fork

Add Permissions

---

.github/workflows/integrationTest.yml

Not making msi
Use correct dir to build msi
My fork

Fix Create MSI

---

src/helpers/BasicTable.js
src/helpers/grapher.js
src/helpers/table.css
src/pages/graphics.js
src/pages/home.js
src/pages/page.js
src/pages/settings.css
src/pages/settings.js
src/pages/table.js

Bugs including table TPS out of order, graph displaying incorrect data on start, and more exist.
Bugs have been fixed. A few QOL features added such as warning popup going away after a short time, table commit hyperlink is shown, table color codes header when TPS "all" is selected, table "CommitDate" changes to "Date" to save space when "all" TPS is selected, settings pane is collapsable.
@okankoAMZ authored the graph fixes, warning message timer, and settings pane collapsing.
Ensure bug fixes work via building/running site on local machine. Built website on forked repo.
1. Run `make fmt` and …

Website bug fixes & QOL features

---

src/pages/wiki.js

Unused variable caused build error.
Removed unused variable.
Run website on local.

Perf Benchmark Removed Unused Variable

---

src/helpers/reciever.js

Release names were cut off so it was not possible to distinguish between them (since it is version).
Don't cut the names of release versions off, link to proper release page.
Ran on local to ensure the change works.

Added release visual fixes

---

.github/workflows/internal-pipeline-dedicated-host-cleaner.yml

Too many mac hosts in ap-southeast-1 
Clean those hosts
N/A

Clean More Regions Deprecated Pipeline

---

.github/workflows/internal-pipeline-dedicated-host-cleaner.yml

Need to clean more regions 
Clean more regions 
N/A

Clean internal more region

---

.github/workflows/internal-pipeline-dedicated-host-cleaner.yml

Opt in regions fail 
Remove opt in regions
N/A

Remove Opt-in Regions

---

.github/workflows/deploy-to-gh-pages.yml
package-lock.json
package.json
src/helpers/reciever.js
src/pages/wiki.js

The website is not ready to be deployed publicly but it is also not currently available internally.
Adds authentication to lock the website out unless you have the internal beta-testing password. Every database request must be authenticated with the password.
Build and test locally to ensure the website functions properly.

Performance Benchmark Website Internal Authentication

---

.github/workflows/integrationTest.yml
integration/generator/resources/ec2_gpu_test_matrix.json
integration/generator/test_case_generator.go

Windows tests create a password from ssh key
Remove windows test for now
N/A

Remove Windows Tests Until We Figure Out SSH Without Windows Password

---

.github/workflows/integrationTest.yml

Tests not running
Remove comments since it was causing test not to run
N/A

Fix Broken Tests Not Being Run

---

integration/generator/resources/ec2_linux_test_matrix.json
integration/terraform/ec2/linux/vpc.tf
integration/terraform/ec2/localstack/vpc.tf
integration/terraform/ec2/win/vpc.tf

Add support for 22.04 Ubuntu
[Running integration test on my fork](https://github.com/khanhntd/amazon-cloudwatch-agent/runs/8173575518?check_suite_focus=true). 

Add support for 22.04 Ubuntu

---

integration/test/agent_util_linux.go
integration/test/metric/metric_value_query.go
integration/test/metric_value_benchmark/base_test.go
integration/test/metric_value_benchmark/cpu_test.go
integration/test/metric_value_benchmark/metrics_value_benchmark_test.go
integration/test/metric_value_benchmark/placeholder_test.go
integration/test/status/test_result.go

When CPU value sanity test was added, the test package wasn't fully prepared to guide future test addition.
-  Refactoring & organization for future tests
-  Created test suite so that summary for all the future tests can be printed together
Print format isn't the most ideal, but I will leave improvement for that to anyone who has a good idea. 
^ Done

Refactor benchmark test package for future tests

---

.github/workflows/integrationTest.yml

Test failure due to this added change during last PR
Fix how env variables are referenced in github workflow file
ongoing test in my fork

Fix Env variable failure

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-macos.yml
.github/workflows/build-test-windows.yml
.github/workflows/codeql-analysis.yml
.github/workflows/integrationTest.yml
CONTRIBUTING.md
README.md

Updates to adapt to default branch as main
Minor updates. The workflows should test the updates upon merge.

Updates to adapt to default branch as main

---

.github/workflows/integrationTest.yml

Need to cherry-pick this commit form private repo to sync changes
Cherry-pick 
https://github.com/aws/private-amazon-cloudwatch-agent-staging/actions/runs/3518425349/jobs/5897421803
No longer failing to setup jobs

Change nick-invision/retry to nick-fields/retry

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.247356
N/A

Update RELEASE_NOTES for 1.247356

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.247357
Update RELEASE_NOTES for 1.247357
none

Update RELEASE_NOTES for 1.247357

---

.github/workflows/integrationTest.yml

Changing the branch name according to this PR https://github.com/aws/amazon-cloudwatch-agent-test/pull/70. Only merge after that PR is merged
By apply this changes, I have run this on my fork
Performance Tracking Test: https://github.com/khanhntd/amazon-cloudwatch-agent/actions/runs/4070853647/jobs/7012314979
Other tests https://github.com/khanhntd/amazon-cloudwatch-agent/actions/runs/4070754614

Update the branch for ecs fargate and ecs ec2

---

.github/workflows/GH-Pages.yml
.gitignore

Delete environment key and update GitIgnore

Delete environment key and update GitIgnore

---

Makefile

We do not want or need a stack trace with the full GOPATH which is specific to the build system.
Just need filenames.
Example of current stack trace:
```
adamym@88665a370425 amazon-cloudwatch-agent % ./build/bin/darwin_amd64/amazon-cloudwatch-agent --crashtest
2023/02/28 09:57:23 Crashing in 1 second...
2023-02-28T15:57:24Z I! Crashing in goroutine
panic: runtime error: integer divide by zero
goroutine 89 [running]:
main.main.func1()
/Users/adamym/go/src/github.com/aws/amazon-cloudwatch-agent/cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go:357 +0x4a
created by main.main
/Users/adamym/go/src/github.com/aws/amazon-cloudwatch-agent/cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go:353 +0xf1
```
This is what we want:
```
adamym@88665a370425 amazon-cloudwatch-agent % …
```

Add -trimpath to go build command.

---

.github/workflows/clean-aws-resources.yml
tool/clean/clean_host/clean_host.go

We have internal hosts we need to terminate after 1 day.
Clean hosts that need to be terminated after 1 day. 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/4326874506

Clean host

---

.github/workflows/integration-test.yml

-Add support for `terraform_dir` argument from test matrix
Tested with a forked repo

support terraform_dir param in integration Github action

---

RELEASE_NOTES

Updating release notes for 1.247359.0 and 1.247360.0
Updating release notes for 1.247359.0 and 1.247360.0
none

Updating release notes for 1.247359.0 and 1.247360.0

---

README.md

Adding blurb about usage data and opt-out
Adding blurb about usage data and opt-out
none

Adding blurb about usage data and opt-out

---

.github/workflows/integration-test.yml

Hard to find which street test is failing
Echo street test info
N/A

Echo Stress Test Info

---

src/common/Axios.ts
src/common/Dialog.tsx
src/containers/PerformanceReport/index.tsx
src/containers/PerformanceReport/service.ts
src/containers/PerformanceTrend/index.tsx
src/containers/PerformanceTrend/service.ts
yarn.lock

Authentication on the webpage points to a dead link.
Uses a new backend for authenticating. Changed request and response structure to accommodate for the different format. Added some placeholder/dummy data to work around issues with Github API. 
Note: commented code is kept because I made a temporary workaround with Github API. Will be uncommented in the future.
Built and ran app on my local.

Update webpage authentication

---

go.mod
go.sum
plugins/outputs/cloudwatchlogs/pusher.go
tool/gzip.go
tool/persistentqueue/diskqueue/diskqueue.go
tool/persistentqueue/persistentqueue.go

Persistent queue

---

README.md
RELEASE_NOTES

Update RELEASE_NOTES for v1.300025.0 to v1.300026.3 and README.md
N/A

Update RELEASE_NOTES for v1.300025.0 to v1.300026.3 and README.md

---

handlers/agentinfo/info.go
handlers/agentinfo/info_test.go
plugins/processors/ec2tagger/ec2metadataprovider.go
translator/util/ec2util/ec2util.go

Get Stats For IMDSV2 Fallback Succeed

---

RELEASE_NOTES

Preparing for release of 1.300028.0.
Update the release notes with changes.
N/A

Update release notes for 1.300028.0

---

RELEASE_NOTES

The release of 1.300028.0 was delayed due to an emergent issue. This was resolved by https://github.com/aws/amazon-cloudwatch-agent/pull/847. 
Updating the release notes in preparation to restart the release.
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/6148771680

Update release notes for 1.300028.0.

---

go.mod
go.sum

Logrus out of date
Upgrade logrus
unit tests

Upgrade Logrus

---

.github/workflows/PR-build.yml
.github/workflows/integration-test.yml
.github/workflows/otel-fork-replace.yml
.github/workflows/test-build.yml

Using old golang
Upgrade to latest golang
Unit tests

Upgrade Golang Version

---

RELEASE_NOTES

update the release notes for `1.300031.0`
PRs included in this release:
- https://github.com/aws/amazon-cloudwatch-agent/pull/929
- https://github.com/aws/amazon-cloudwatch-agent/pull/945
- https://github.com/aws/amazon-cloudwatch-agent/pull/946

Update RELEASE_NOTES for 1.300031.0

---

RELEASE_NOTES

Inaccurate release notes
edits release notes
agent tests

RELEASE_NOTES edit

---

RELEASE_NOTES

update release notes for v1.300031.1

Update release notes for v1.300031.1

---

RELEASE_NOTES

Update release notes for 1.300032.0

update release notes for 1.300032.0

---

plugins/processors/awsappsignals/processor.go
plugins/processors/awsappsignals/processor_test.go
plugins/processors/awsappsignals/rules/common.go
plugins/processors/awsappsignals/rules/dropper.go
plugins/processors/awsappsignals/rules/dropper_test.go
plugins/processors/awsappsignals/rules/keeper.go
plugins/processors/awsappsignals/rules/keeper_test.go
plugins/processors/awsappsignals/rules/replacer.go
plugins/processors/awsappsignals/rules/replacer_test.go

Add unit test for awsappsignals processor
To avoid bug issue like https://github.com/aws/amazon-cloudwatch-agent/pull/946.

Add test case for awsappsignals processor

---

cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go
translator/translate/otel/translate_otel.go

Internal only issue
Have the yaml log file path be the same as the toml log file path not just the json file path
Internal only 

Set YAML Log File Path Correctly

---

tool/clean/clean_host/clean_host.go

Currently. we are not cleaning up any NvidiaDataCollector instance.
Added NvidiaDataCollector-* to the filter list to clean-up any instance left.
Added regions so that clean-up will work on other regions as well such as us-east-1
Ran `go run clean_host.go` and  terminate the instance  in both regions

Added Nvidia Test to cleanup filter

---

tool/clean/clean_eks/clean_eks.go

The eks cleaner script is not cleaning clusters used for the operator helm chart tests causing errors: 
Test run: https://github.com/aws/amazon-cloudwatch-agent-operator/actions/runs/7731754026/job/21080141509
Error:
```
Error: creating EKS Cluster (cwagent-operator-helm-integ-4090895b15ab104d): operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: 3f743e72-f57c-4448-9958-318c1eb75fbf, ResourceLimitExceededException: Cluster limit exceeded for account.
```
This is because the cluster name is not allow listed to be cleaned `cwagent-operator-helm-integ-*`
I added a list of cluster names to the clean_eks script to include `cwagent-operator-helm-integ-` as a prefix.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add list of cluster names to clean_eks script

---

.github/workflows/integration-test.yml

With new test update branch is required for localstack start up
Add branch main to localstack
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/7965568387/job/21745789788

Allow Pass In Branch To Localstack

---

go.mod
go.sum

Outdated crypto library 
Upgrade crypto library
N/A

Upgrade Crypto Dep

---

.github/workflows/integration-test.yml

No pre release testing for CN region
Add EC2 integration tests for CN
Github tests https://github.com/aws/amazon-cloudwatch-agent/actions/runs/8024134275

Add CN tests

---

translator/translate/otel/receiver/jmx/translator.go
translator/translate/otel/receiver/jmx/translator_test.go

Random port required for jmx
Ask for random port by config
Manual

Use Random Port By Default For OTLP

---

service/defaultcomponents/components_test.go

Unit test failure
Update processor name in a unit test to align with the actual processor name
```
go test -v ./service/defaultcomponents -count=1
=== RUN   TestComponents
--- PASS: TestComponents (0.00s)
PASS
ok      github.com/aws/amazon-cloudwatch-agent/service/defaultcomponents        2.449s
```

Fix unit test

---

cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go

Create a file if the agent fails to start
Create a file if the agent fails to start
Tested in internal pipeline

Create Error File On Telegraf Failure

---

RELEASE_NOTES

Update RELEASE_NOTES for v1.300034.1
N/A

Update RELEASE_NOTES for v1.300034.1

---

translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/translate/otel/exporter/awsemf/kubernetes.go
translator/translate/otel/exporter/awsemf/translator_test.go

Add support for Elastic Fabric Adapter (EFA) metrics.

Add support for Elastic Fabric Adapter (EFA) metrics.

---

.github/workflows/clean-aws-resources.yml
tool/clean/clean_host/clean_host.go

Test hosts in China where not being cleaned
Add an action to clean hosts in China 
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/9007731713/job/24748208241

Clean Test Hosts In China

---

tool/clean/clean_eks/clean_eks.go

EKS beta clusters are not getting terminated by the [daily cleaner job](https://github.com/aws/amazon-cloudwatch-agent/blob/main/.github/workflows/clean-aws-resources.yml). 
- Add a step to clean up EKS beta clusters
Ran the change manually to delete beta clusters.

Delete beta clusters created by Github Actions

---

plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer.go
plugins/processors/awsapplicationsignals/internal/normalizer/attributesnormalizer_test.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver.go
plugins/processors/awsapplicationsignals/internal/resolver/attributesresolver_test.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes.go
plugins/processors/awsapplicationsignals/internal/resolver/kubernetes_test.go

Reverted the previous PR https://github.com/aws/amazon-cloudwatch-agent/pull/1165, and resubmit a new one.

[GA] Autofill ECS cluster info if it's missing

---

RELEASE_NOTES

Update release notes for 1.300040.0

---

translator/context/context.go
translator/tocwconfig/sampleConfig/complete_linux_config.conf
translator/tocwconfig/sampleConfig/complete_linux_config.json
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/translate/agent/ruleOmitHostname.go
translator/translate/otel/processor/ec2taggerprocessor/translator.go
translator/translate/otel/processor/ec2taggerprocessor/translator_test.go
translator/translate/otel/receiver/jmx/testdata/config.yaml
translator/translate/otel/receiver/jmx/translator.go
translator/translate/otel/receiver/jmx/translator_test.go

JMX metrics require having host just like cpu metrics.
Add host as a metric to jmx metrics unless omit_hostname is true
```
{
"agent": {
"debug": true
},
"namespace": "HostnameTest",
"metrics_collected": {
"cpu": {
"resources": [
"*"
],
"measurement": [
{"name": "cpu_usage_idle", "rename": "CPU_USAGE_IDLE", "unit": "Percent"},
{"name": "cpu_usage_nice", "unit": "Percent"},
"cpu_usage_guest"
],
"totalcpu": false,
"drop_original_metrics": [ "cpu_usage_guest" ],
"metrics_collection_interval": 10
},
"jmx": [
{
"endpoint": "localhost:2020",
"jvm": []
}
]
}
}
}
```
```
{
"agent": {
"debug": true,
"omit_empty": true
},
"metrics": {
"append_dimensions": { …
```

Add Host To JMX Metrics

---

RELEASE_NOTES

Just updating the release notes.
No code change

Updated Release Notes for 1.300042.0

---

.github/workflows/application-signals-e2e-test.yml

Updating the release testing workflow to point to the main branch now that the changes have been merged
Test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10047179129

Update release test to point to main

---

RELEASE_NOTES

Updating Release Notes for 1.300043.0

---

RELEASE_NOTES

Updating RELEASE_NOTES for 1.300043.0

---

RELEASE_NOTES

Updating release notes since the following PRs are not included in the 1.300043.0 release
https://github.com/aws/amazon-cloudwatch-agent/pull/1262
https://github.com/aws/amazon-cloudwatch-agent/pull/1275

Update RELEASE_NOTES for 1.300043.0

---

RELEASE_NOTES

Updated Release Notes for 1.300044.0
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10391606934

Updated Release Notes for 1.300044.0

---

RELEASE_NOTES

Release `1.300045.0`
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/10462377538

Updated Release Notes for 1.300045.0

---

.github/workflows/application-signals-e2e-test.yml

*Issue #, if available:*
Updated e2e test file name in this [PR](https://github.com/aws-observability/aws-application-signals-test-framework/pull/178)
*Description of changes:*
Update the file names to point to the new ones
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Update E2E test file name

---

RELEASE_NOTES

Preparing for the 1.300045.1 release.
Updates the RELEASE_NOTES.
https://github.com/aws/amazon-cloudwatch-agent/compare/v1.300045.0...main
N/A

Update Release Notes for 1.300045.1

---

RELEASE_NOTES

Preparing for the 1.300046.0 release.
Updates the RELEASE_NOTES.
N/A

Updated Release Notes for 1.300046.0

---

RELEASE_NOTES

Fix typo in release notes

---

RELEASE_NOTES

Updated Release Notes for 1.300047.0
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11076698200

Updated Release Notes for 1.300047.0

---

RELEASE_NOTES

Update Release Notes for 1.300048.0

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.300049.0

---

RELEASE_NOTES

Update release note for 1.300049.1
Update release note for 1.300049.1

Update RELEASE_NOTES 1.300049.1

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.300050.0
N/A

Update RELEASE_NOTES for 1.300050.0

---

.github/workflows/integration-test.yml

GPU E2E Integ test is failing with missing metrics and dimensions
- Reorder `kubectl` apply commands so that GPU burn pod starts after nvidia device plugin is installed
- Update metrics-dims sets to the latest to include or drop GPU count metrics and their names
- Update EKS and Addon versions to the latest
- Use variables from the generated test matrix json instead hard-coded values
Github test run: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12127752653
```
2024/12/02 15:46:15 >>>>>>>>>>>>>><<<<<<<<<<<<<<
2024/12/02 15:46:15 >>>>>>>>>>>>>>Successful<<<<<<<<<<<<<<
2024/12/02 15:46:15 ==============EKS_GPU_NVIDIA============== …
```

Fix GPU E2E integ test

---

RELEASE_NOTES

Updating Release Notes for 1.300051.0

1.300051.0 release

---

plugins/processors/awsentity/factory.go
plugins/processors/awsentity/factory_test.go
plugins/processors/awsentity/processor.go
translator/tocwconfig/sampleConfig/base_container_insights_config.yaml
translator/tocwconfig/sampleConfig/complete_darwin_config.yaml
translator/tocwconfig/sampleConfig/complete_linux_config.yaml
translator/tocwconfig/sampleConfig/complete_windows_config.yaml
translator/tocwconfig/sampleConfig/config_with_env.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_config.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_gpu_config.yaml
translator/tocwconfig/sampleConfig/emf_and_kubernetes_with_kueue_config.yaml
translator/tocwconfig/sampleConfig/kueue_container_insights_config.yaml
translator/tocwconfig/sampleConfig/logs_and_kubernetes_config.yaml
translator/translate/otel/pipeline/emf_logs/translator.go
translator/translate/otel/pipeline/emf_logs/translator_test.go

This reverts commit dfd207047018b0d7afe1905bdd747790241c0cfa.
Reverting commit so we can move it to a feature branch
Revert commit dfd207047018b0d7afe1905bdd747790241c0cfa.

Revert "[processor/awsentity] Add awsentity processor into EMF pipeline (#1482)"

---

RELEASE_NOTES

Update RELEASE_NOTES for 1.300053.0

---

plugins/outputs/cloudwatchlogs/internal/pusher/target.go
plugins/outputs/cloudwatchlogs/internal/pusher/target_test.go

If there are multiple instances of the CloudWatch agent that are trying to create the same log group, there are cases where streams within those log groups will not be created because `CreateLogGroup` returns `ResourceAlreadyExists`.
https://github.com/aws/amazon-cloudwatch-agent/blob/af960d73a8df75ed2d23b53f34a5813727829018/plugins/outputs/cloudwatchlogs/internal/pusher/target.go#L72
Resource already exists shouldn't be considered a failure to create the resource. Only add the target to the cache if the log stream was created or already exists.
Added more unit test cases to cover the issue. Added checks for cache sizes after each test.
```
=== RUN …
```

Only add to cache if log stream is created

---

.github/pull_request_template.md

Add ready for testing label instructions to PR template

---

RELEASE_NOTES

https://github.com/aws/amazon-cloudwatch-agent/compare/1.300057.0-release...main
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/15687508626/job/44202160156

Updated Release Notes for 1.300057.0

---

RELEASE_NOTES

Updating Release Notes for 1.300058.0
-------

Updated Release Notes for 1.300058.0

---

plugins/inputs/logfile/logfile_test.go

The TestLogsFileWithRangeGaps test will sometimes fail. This usually means that the GH action for the unit tests need to be retried which is tedious.
Check for the events out of order. This can happen due to the asynchronous process. Made updates to TestLogsFileWithRangeGaps and TestLogsFileWithEOFRangeGaps
1. Unit tests
3. Run `make lint`
-------
- Don't think this is necessary - there are no logic changes

Fix flaky concurrency logs test

---

RELEASE_NOTES

Updating Release Notes for 1.300059.0
N/A
3. Run `make lint`

Updated Release Notes for 1.300059.0

---

RELEASE_NOTES

updating release notes
-------
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/17805120972/job/50615390542

Updating Release Notes for 1.300060.0
